### ISSUE TITLE
jr:choice-name works for select_one, not select_multiple

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#1495]
The `jr:choice-name` function works as expected for select_one fields, but returns empty for `select_multiple` fields even when items are selected. 

This will likely need to be filed upstream, but wanted a placeholder so that this doesn't get lost/forgotten.

Still to do:
- [ ] Build test form
- [ ] Confirm bug with Enketo proper
- [ ] Report result

**Comment by alxndrsn** [comment]
N.B. from the current `master` of enketo-core:

> `TODO: this needs to work for all expressions (relevants, constraints), now it only works for calulated items`
> — _https://github.com/enketo/enketo-core/blob/cbe68f63befc16326e73f6a44b75790118896352/src/js/Form.js#L159_

**Comment by abbyad** [comment]
Removing from milestone as we don't need it anymore for the field-test.

**Comment by abbyad** [comment]
@vimemo was this covered by the latest Enketo work?

**Comment by vimemo** [comment]
I don't think so. @abbyad, this is enketo-core stuff.

**Comment by jkuester** [comment]
I ran into this recently and wanted to record my findings.  Using the current version of enketo-core (`5.18.0`) deployed out on  https://getodk.org/xlsform/ I tested the support for the `jr:choice-name` function with `select_multiple` questions. 

On that version of Enketo, the `jr:choice-name` function would properly return the localized label for the answer of a `select_multiple` question so long as _only one_ choice was selected.  If multiple choices were selected, then `undefined` would be returned.  This behavior seems to properly align to the documentation for the [jr:choice-name](https://docs.getodk.org/form-operators-functions/#jr:choice-name) function (and with the way that references to select_multiple questions are handled).  When a select_multiple question is referenced by a variable, it returns a space-delimited array of the _names_ of the selected values.  The jr:choice-name function only accepts a single choice_name to lookup, so when it is given multiple names in an array, it does not find any values.

The only way I have come up with to actually get the labels for the selected answers to a select_multiple question is a brute-force approach using `count-selected` and `selected-at` functions. E.g.:

> This will print the labels of up to 3 of the selected colors.

type | name | label | calculation
-- | -- | -- | --
select_multiple color | select_color | Pick some colors |  
calculate | color_count |   | count-selected(${select_color})
calculate | color_1 |   | jr:choice-name(selected-at(${select_color}, 0), '${select_color}')
calculate | color_2 |   | jr:choice-name(selected-at(${select_color}, 1), '${select_color}')
calculate | color_3 |   | jr:choice-name(selected-at(${select_color}, 2), '${select_color}')
calculate | color_label |   | if(${color_count} = 1, ${color_1}, if(${color_count} = 2, concat(${color_1}, ‘ ‘, ${color_2}), concat(${color_1}, ‘ ‘, ${color_2}, ‘ ’, ${color_3})))
note | color_note | Colors: ${color_label} | 

Once we have completed uplifting enketo-core in #6345 we should revisit this issue to see if the CHT now supports similar behavior.

**Comment by jkuester** [comment]
@medic/quality-assurance With the update to the new version of enketo-core, now we expect the behavior of the `jr:choice-name` function to match what I have described above (for the behavior of https://getodk.org/xlsform/): 

> On that version of Enketo, the jr:choice-name function would properly return the localized label for the answer of a select_multiple question so long as only one choice was selected. If multiple choices were selected, then undefined would be returned. This behavior seems to properly align to the documentation for the jr:choice-name function (and with the way that references to select_multiple questions are handled). When a select_multiple question is referenced by a variable, it returns a space-delimited array of the names of the selected values. The jr:choice-name function only accepts a single choice_name to lookup, so when it is given multiple names in an array, it does not find any values.

If the CHT still does not match this behavior, or this behavior does not seem sufficient for our use cases, we should not accept these changes as addressing this issue.

**Comment by tatilepizs** [comment]
Using branch `6345-enketo-uplift` the `jr:choice-name` function behavior is the expected. (Form used to test: [enketo_test](https://docs.google.com/spreadsheets/d/1PeVjtA_9sAdVuM-kzgBEmDPmrEKnF1zfAnQQlnuXMQs/edit#gid=1910514219))

- Selecting one option, the correct value will be returned.

![image](https://user-images.githubusercontent.com/94494491/149812664-98ac061c-0fd5-45a9-ab2c-1340e18e09a7.png)

- Selecting more than one option, `undefined` will be returned.

![image](https://user-images.githubusercontent.com/94494491/149812879-3a65fde7-c968-4dee-b487-125287128761.png)

**Comment by kawerewagaba** [comment]
tried this approach, but getting this error (screenshot):
i believe it's due to the arguments passed to `jr:choice-name()`. the spec expects a `node` and a `string`, but i believe a string is returned by `selected-at()` for the first arg. however, it doesn't mean that switching the arguments fixes it either - cuz i'm getting an empty string from `jr:choice-name`.

<img width="481" alt="Screenshot 2022-03-25 at 10 14 05" src="https://user-images.githubusercontent.com/24539185/160113282-1f91f61b-1906-4245-9498-418ee3283773.png">

**Comment by jkuester** [comment]
@kawerewagaba I assume the approach you are talking about is the pattern I mentioned above in [this comment](https://github.com/medic/cht-core/issues/1495#issuecomment-894312535).  I am pretty sure that general pattern is valid (since it was basically copied from the [ODK docs](https://docs.getodk.org/form-operators-functions/#id13)). but maybe there is something in your specific case that is affecting the functionality.

Looking at your error message: `The string 'jr:choice-name(\"\", \"/r/n/message_to_resume \")' is not a valid XPath expression.` it does indeed appear that `selected-at` is returning an empty string (which [is expected](https://docs.getodk.org/form-operators-functions/#selected-at) if the index does not exist because that amount of choices was not selected).  Does this error affect the functionality?  (Once you select some choices from your `select_multiple` question, do you see the expected output from `jr:choice-name`?  If so, then you may just need to wrap the call to `jr:choice-name` in an if-block based on [`count-selected`](https://docs.getodk.org/form-operators-functions/#count-selected) to avoid logging the error.  Something like: 

```
if(count-selected(${select_color}) > 0, jr:choice-name(selected-at(${select_color}, 0), '${select_color}'), '')
```
