### ISSUE TITLE
Improve sync status UI

### ISSUE THREAD

**Issue by alxndrsn** [medic/cht-core#3977]
# Context

* resticted user
* chrome desktop
* connection throttled to 1kBps up and down

# Observed behaviour

* request to `_revs_diff` times out after 30s
* sync information in hotdog menu does not change from:

<img width="252" alt="screen shot 2017-10-19 at 11 15 16" src="https://user-images.githubusercontent.com/191496/31760887-d67d95a0-b4be-11e7-8d93-5e3aa0bb2da9.png">

# Expected behaviour

* sync information should say e.g. before `_revs_diff` endpoint returns successfully:

<img width="280" alt="screen shot 2017-10-19 at 11 16 44" src="https://user-images.githubusercontent.com/191496/31760956-106cb6f6-b4bf-11e7-9732-a6ac7c977a69.png">

* provide some useful feedback such as "last synch timed out"
* even better if we can differentiate between poor connection and no connection and inform the user

cc @samkanga @smbuthia

**Comment by garethbowen** [comment]
@michaelkohn Is this blocked or can a developer pick it up?

**Comment by michaelkohn** [comment]
@garethbowen I started looking into this one yesterday and have been keeping track of things in [this](https://docs.google.com/document/d/1hPp6RdBMqpTscmKHMkfHbDDD0_C6C28KivicLzC6FwQ/edit) doc. I was going to try to come up with some suggestions today and then schedule a chat with you in the next day or two to figure out what we can/cannot do.

Some of the other related issues / content I found (some just for context) were: 
#4805 , #3967 , #4874 , #5738 , #5207 , #5861 , [this](https://forum.communityhealthtoolkit.org/t/for-offline-users-how-often-does-the-app-try-to-refresh-if-there-is-an-available-internet-connection/503) forum post, and the [nav redesign doc](https://docs.google.com/document/d/1GU3iWlnTz8H3WknnHVtPbMvWQpflUCeDPozk2Gm1Tx0/edit#heading=h.872ra0q7xppf).

**Comment by michaelkohn** [comment]
Currently, we show these 4 sync statuses:

<img width="895" alt="Screen Shot 2019-11-27 at 6 07 30 PM" src="https://user-images.githubusercontent.com/10096985/69740000-b24e9280-1149-11ea-8b8a-42446eb9a29d.png">

We'd like to provide some more detailed information to the user:

- [ ] Sync statuses when sync fails
- [ ] Address "Unknown" status
- [ ] Add "Last sync .... ago" information

### Sync statuses when sync fails
At a minimum, we would like to add the following:

- Connection timeout
- Connection offline  

These would only be displayed after a failed sync attempt (not, for example, if the user just happens to be offline) and those statuses would remain until the next sync attempt (either automatically or manually), or if the user closes the app/browser.

### "Unknown" status
The **Unknown** status shows for a period when you first load the app or if you refresh the page... especially on slower connections. Click [here](https://drive.google.com/file/d/1ERzYfGGFlmmrOo3HaiJ0awYz2HImVzlU/view?usp=sharing) for a video example with the developer console open.

If it is possible to get rid of the need for the **Unknown** status (perhaps by not clearing the "Last successfull replication to/from..." times), that would be great. Otherwise, if there is some more meaningful message we could provide, I'm open to suggestions.


### "Last sync ... ago" information
We know the "Last successful replciation to the server" and the "Last successful replication from the server" (it's on the **About** page). We would like to add a line under the sync status that shows the relative elapsed time since the last successful sync. If they are/can be different, I'd recommend we use the "replication **_to_**" value for the last sync time since CHWs are most likely trying to sync because they need to sync reports up to the server.


## UI suggestions
<img width="954" alt="Screen Shot 2019-11-27 at 6 50 30 PM" src="https://user-images.githubusercontent.com/10096985/69739975-a662d080-1149-11ea-839d-4060df79327c.png">

**Comment by michaelkohn** [comment]
@garethbowen should be ready to go... let me know if you have any questions!

**Comment by garethbowen** [comment]
Unfortunately pouchdb doesn't expose any difference between "connection timeout" and "connection offline" or any other error so I'm using the same generic message for both "Unable to connect".

We don't connect for the first 10 seconds because we don't want to try and do too much as the app is starting up. I thought about adding a "pending" status but I think that's just unnecessary and have decided to leave it blank. After the first 10 seconds it'll be replaced by a status message and never go back to blank again.

These are the states now:

### On load

![Screenshot from 2019-11-29 13-16-46](https://user-images.githubusercontent.com/2064938/69836084-4dab4900-12ab-11ea-99f0-fae98fe76fce.png)

### After success

![Screenshot from 2019-11-29 13-16-10](https://user-images.githubusercontent.com/2064938/69836087-58fe7480-12ab-11ea-818c-4ca891631be9.png)

### After sync failed

![Screenshot from 2019-11-29 13-15-51](https://user-images.githubusercontent.com/2064938/69836097-61ef4600-12ab-11ea-916d-fff608d2b236.png)

### After sync failed with local changes to send

![Screenshot from 2019-11-29 13-16-33](https://user-images.githubusercontent.com/2064938/69836110-74697f80-12ab-11ea-9b60-117f7fe04402.png)

**Comment by michaelkohn** [comment]
Great. Couple comments / questions...

####  "Last sync 13:16"
  
- Once the last sync time is more than 24h in the past, how do we display it?

#### On load

- Cool, good idea.


#### Status updates
Based on your comments, this is how I understand things would work. Does this look accurate to you?
_(`-` means "no change". )_

`#` | Current Status | Scenario | New Status | New Last sync
-- | -- | -- | -- | --
1 | All reports synced | Sync succeeds | - | Last sync xxx
2 |   | Sync fails | Unable to connect | -
3 |   | Local changes made | Reports to sync | -
4 | Reports to sync | Sync succeeds | All reports synced | Last sync xxx
5 |   | Sync fails | - | -
6 |   | Local changes made | - | -
7 | Unable to connect | Sync succeeds | All reports synced | Last sync xxx
8 |   | Sync fails | - | -
9 |   | Local changes made | Reports to sync | -


- If the user starts or goes offline without any reports to sync, wouldn't the status basically start and stay in "Unable to connect" until they either successfully sync or make local changes?
- Since scenario 5 doesn't change the sync status, we aren't really giving explicit feedback to the user that their sync failed. They have to infer it based on the Last Sync time not changing. As a user, if I manually initiate a sync and the end result is that nothing changes, I'd probably just think the app was broken.
- Since scenario 5 doesn't change the sync status if they have reports to sync, it means that "Unable to connect" would actually only ever show if there are _no reports to sync_, right?

#### Suggestion

What if we did something like this? It would always be clear whether or not the user has documents to sync, but also give an indication of the connection status. It would also be less of a change from what they are used to now.

![image](https://user-images.githubusercontent.com/10096985/69859811-f5be1380-12a5-11ea-9ad5-25f596cdc72d.png)



`#` | Current Status | Scenario | New Status | New Last sync
-- | -- | -- | -- | --
1 | All reports synced | Sync succeeds | - | Last sync xxx
2 |   | Sync fails | - | No connection. Last sync 13:16
3 |   | Local changes made | Reports to sync | -
4 | Reports to sync | Sync succeeds | All reports synced | Last sync xxx
5 |   | Sync fails | - | No connection. Last sync 13:16
6 |   | Local changes made | - | -

**Comment by SCdF** [comment]
@garethbowen we are able to detect general offline / online state (ignoring Pouch) with https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine , we may be able to fold that into the mix

**Comment by garethbowen** [comment]
@michaelkohn 

> Once the last sync time is more than 24h in the past, how do we display it?

It's consistent with the other relative date formatting in the app, eg: "Last sync yesterday", "Last sync 3 days ago".

> Based on your comments, this is how I understand things would work. Does this look accurate to you?

Yes!

> If the user starts or goes offline without any reports to sync, wouldn't the status basically start and stay in "Unable to connect" until they either successfully sync or make local changes?

Yes. In this scenario it's impossible to know if there are changes to pull down from the server.

> Since scenario 5 doesn't change the sync status, we aren't really giving explicit feedback to the user that their sync failed. They have to infer it based on the Last Sync time not changing. As a user, if I manually initiate a sync and the end result is that nothing changes, I'd probably just think the app was broken.

I think this is the rationale behind [creating a dialog](https://github.com/medic/cht-core/issues/5207) for this so you can see the status of the current replication attempt.

> Since scenario 5 doesn't change the sync status if they have reports to sync, it means that "Unable to connect" would actually only ever show if there are no reports to sync, right?

Correct. We can determine whether or not there are docs to replicate to the server so that message shows in preference to the less specific "unable to connect" message.

> What if we did something like this?

I believe the middle panel is misleading because it's making it look like everything's up to date when it's possible there are new configurations, edited contacts, signed off reports, etc to come. That's why we had the greyed out "unknown" state before as an intermediate step between "all good" and "out of date".

Do you think we can reintroduce some intermediary state, perhaps grey or yellow, and rethinking the wording so it more clearly communicates what's happening?

**Comment by michaelkohn** [comment]
> I believe the middle panel is misleading because it's making it look like everything's up to date when it's possible there are new configurations, edited contacts, signed off reports, etc to come.

I hear ya, and agree... though the third panel has that same problem (remote changes might have happened at 15.28). The difference is that the third panel is conveying the outcome of the last sync, whereas the second panel was intending to convey the current state of local changes.

Perhaps for this issue, we can stick with what you proposed in https://github.com/medic/cht-core/issues/3977#issuecomment-559623740 , but change the "Unable to connect" to grey and, ideally, use an `i` (for "information") instead of `?`. The reason I think we should use grey is that (1) grey often conveys offline; and (2) it will only ever be in this status if they don't have any local changes to sync anyway.

**Comment by garethbowen** [comment]
I've updated the third panel:

![Screenshot from 2019-12-10 10-42-14](https://user-images.githubusercontent.com/2064938/70475686-f1adb380-1b39-11ea-9d41-4f1442eac5d0.png)

**Comment by garethbowen** [comment]
Ready for AT in `3977-sync-status-updates`

**Comment by dianabarsan** [comment]
Assigning myself for AT.

**Comment by dianabarsan** [comment]
The changes look good to me and are consistent with the first table in this comment: https://github.com/medic/cht-core/issues/3977#issuecomment-559730492

After load:
![after-load](https://user-images.githubusercontent.com/35681649/70613027-a6b29f80-1c10-11ea-8b18-51c35325604f.png)

After successfull sync (no changes):
![after-successfull-sync](https://user-images.githubusercontent.com/35681649/70613051-b0d49e00-1c10-11ea-9764-ecf29c578269.png)

Failed sync (offline) after successfull sync (no changes):
![failed-sync-after-successfull-sync](https://user-images.githubusercontent.com/35681649/70613077-bd58f680-1c10-11ea-86cb-64152c2b5410.png)

After submitting local changes:
![after-adding-local-changes](https://user-images.githubusercontent.com/35681649/70613103-c6e25e80-1c10-11ea-93ca-5324b0ffcfa3.png)

Failed sync (offline) after submitting local changes:
![after-failed-sync-with-local-changes](https://user-images.githubusercontent.com/35681649/70613118-ccd83f80-1c10-11ea-9a1e-3a70ccd4073a.png)

After successfull sync with local and remote changes:
![after-successfull-sync-local-remote-changes](https://user-images.githubusercontent.com/35681649/70613141-d366b700-1c10-11ea-9081-991d97616197.png)

The date displayed as "last sync" is the date of the last successful upwards sync. This is also updated if the downwards sync fails. The date is displayed as a relative date:

![after-load](https://user-images.githubusercontent.com/35681649/70614247-d6fb3d80-1c12-11ea-91a6-df2c4c5ac7a3.png)

![last-sync-yesterday](https://user-images.githubusercontent.com/35681649/70614219-ce0a6c00-1c12-11ea-9ce7-cbd3b8362c09.png)

![last-sync-10-days](https://user-images.githubusercontent.com/35681649/70614213-cc40a880-1c12-11ea-8137-0631b1afa471.png)
