### ISSUE TITLE
Cache view results in api migrations

### ISSUE THREAD

**Issue by alxndrsn** [medic/cht-core#4117]
Each view should be called max. once per migration.  This should prevent multiple rebuilds slowing down a view.

**Comment by alxndrsn** [comment]
@SCdF you said you thought this almost certainly isn't a problem.  Are you able to confirm?

**Comment by SCdF** [comment]
To be clear I meant that I didn't think we were doing this non-optimally in a way that can be solved.

However, thinking about how we're doing batching I actually see what could be done to fix this in some cases. Specifically, if you're walking through a collection of documents to change, and you get that document from a view, only call that view once and cache all the ids. As long as you're not also using a view in some part of your transformation, because that would cause views to be regenerated anyway.

I'll go through the migrations we have and see if there are any obvious candidates where we call the view once per batch instead of fully at the start, and we also don't call views internally to the loop.

**Comment by SCdF** [comment]
Migrations that both have view calls in a batch where it (probably) doesn't need to have any:
 - add-uuid-to-scheduled-tasks (2017/1/05)
 - associate-records-with-people (2015/5/13)
 - clean-up-corrupted-users (2016/12/5)
 - extract-read-status (2017/6/7) (uses db-batch)
 - namespace-form-fields (2015/9/19)
 - separate-audit-db (2016/2/18)

In terms of large people on old versions:
 - Muso is on 2.8.3
 - Brac UG is on 2.8.6
 - LGU is on 2.11.1
 - LGK is on 2.11.3

Various others are in or around the 2.11->2.12 mark.

In terms of migrations that might be relevant:
 - 2.8.0 (2016/8/31)
    - clean-up-corrupted-users (2016/12/5)
    - add-uuid-to-scheduled-tasks (2017/1/05)
 - 2.11.0 (2017/4/12)
    - extract-read-status (2017/6/7) (uses db-batch)

Of those I think only extract-read-status is general enough to be worth looking into the efficiency of it.

**Comment by garethbowen** [comment]
Closing this as ancient. We haven't used bulk migrations in a while, and if we do in future it will be implemented in a quite different way.
