### ISSUE TITLE
Import medic-specific functions from openrosa-xpath-extensions

### ISSUE THREAD

**Issue by alxndrsn** [medic/cht-core#4517]
In https://www.npmjs.com/package/openrosa-xpath-evaluator, we have added some medic-specific functions.  These should instead be in `webapp/src/js/enketo/medic-xpath-extensions.js`.

**Comment by garethbowen** [comment]
@vimemo This is relevant to what you're working on currently.

**Comment by vimemo** [comment]
Sounds good, @garethbowen. I'll extract the medic specific functions.

**Comment by jkuester** [comment]
@medic/quality-assurance The main thing done to address this issue was taking the `difference-in-months` function that was [removed from openrosa-xpath-evaluator](https://github.com/enketo/openrosa-xpath-evaluator/issues/17) and adding it to our own [set of xPath extensions](https://github.com/medic/cht-core/blob/d09fcfd739423544699d873f7c97a7e81ad5c6c0/webapp/src/js/enketo/medic-xpath-extensions.js#L148).  

We know this change is successful if a form that uses the `difference-in-months` function (e.g. in a `calculate`) behaves the same as it did in previous CHT versions.

**Comment by ngaruko** [comment]
Tested with local install ...
Date of birth calculation works : 
DOB 
![image](https://user-images.githubusercontent.com/6979995/149678808-76145d85-492c-4b20-ab69-c360dbc754ac.png)
Calculated age as expected 
![image](https://user-images.githubusercontent.com/6979995/149678830-5ea2eeb3-19da-451f-8e84-34ed4d89d762.png)
Will do more form testing during  AT of #6345  and RT
