### ISSUE TITLE
Move to Angular latest

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#4750]
Upgrade from angularjs to angular v6 (or above). Use [these instructions](https://angular.io/guide/upgrade) for how to upgrade. Use `ngUpgrade` to do as little work as possible - we can migrate individual components one by one in future releases. Benchmark the size of the javascript and performance metrics to ensure performance hasn't regressed too far.

**Comment by garethbowen** [comment]
Also read this blog post which documents a new tool and a forum to make upgrading easier: https://blog.angular.io/migrating-to-angular-fc9618d6fb04

**Comment by garethbowen** [comment]
Initially when working on this I attempted to go straight to Angular 6 [in this branch](https://github.com/medic/medic-webapp/tree/4750-angular-6) which worked fine but caused a significant performance reduction. I tried to improve the performance by turning on ahead of time compilation but it didn't work, in part, because our templates were being included separately so they weren't being compiled in.

Then I decided to follow the instructions and convert all the code to components first [in this branch](https://github.com/medic/medic-webapp/tree/4750-convert-to-components-first) which should make the templates available for compilation. It's also something that can be merged before the rest of the Angular 6 conversion, and even better it can be merged one component at a time to reduce conflicts.

Unfortunately I haven't found the time to get this ready for merge so I'm unassigning myself for now so it doesn't get blocked on my availability.

**Comment by rmhowe** [comment]
As far as I can tell these are the steps needed upgrading to latest Angular (now 7.x)

1. **Update `ui-router`**. Necessary to allow the use of components (PR [here](https://github.com/medic/medic-webapp/pull/5276))
2. **Move to TypeScript**. This is not a necessity but it will make the migration easier assuming the eventual plan is to be on Angular 7 with TS. I assumed this was the case based on @garethbowen's work on the `4750-angular-6` branch which introduces TS, but if we don't want TS obviously this step can be skipped. No real code migration needs to happen here, simply the introduction of the TS compiler along with renaming files from `.js` to `.ts`.
3. **Update the state model for webapp**. Angular 2 and above have removed `$scope` as well as broadcast events. This is because the focus has shifted from having inherited scopes to having discrete (but interconnected) components which all have their own isolate scope. Moving data around the app now needs to be much more explicit, or contained in some kind of service. Here we have two major options:
    - Use a state management library/pattern. While most of the important app information management is taken care of by PouchDB, there is still quite a lot of view logic kicking about throughout the app (pretty much everything currently attached to `$scope`) which could be greatly simplified by a state management library/pattern. The most popular ones for Angular seem to be NgRx (which is based on redux) and redux. I've used redux before and was very happy with it, I think it would add a lot in terms of readability of the code, and make it much easier to understand data flows through the app.
    - Don't use a state management library/pattern. This would involve passing a lot of data directly between components (branching out from a high-level component such as `inbox`). In my experience this can get messy quite quickly, particularly for an app of this size and especially when you start to break the code out into smaller components (which I think would be a good first step after the migration to Angular 7), however it would be quicker than implementing a library.
4. **Refactor all controllers/templates into components**. This should hopefully be pretty straightforward once the state management has been sorted out, but will involve moving a lot of code and files around. The Angular style guide recommends organising components by feature (eg. having a folder for `contacts` which would contain all relevant contact editing/creating etc JS and HTML). This will involve updating the router to use components as we go along as well.
5. **Fix up the inevitable leftovers**. There will surely be various small incompatibilities that will need to be cleaned up in the final migration to Angular 7.

From the above I think there are three major questions (provided this does actually seem like the best path forward) which I would love input for from anyone who has an interest in the frontend (@garethbowen @SCdF not sure who else):
- Do we want to use TypeScript? (If so, just webapp or api and sentinel as well?)
- Do we want to use NgRx/redux?
- Do we want to adopt the Angular-recommended file structure?

**Comment by SCdF** [comment]
# !!HI ROBBIE!! ❤️ 💃 🎉 🍕 

> Do we want to use TypeScript? (If so, just webapp or api and sentinel as well?)

100%, and ideally everywhere. The only real downside is we need a compilation step for api / sentinel now as well right?

> Do we want to use NgRx/redux?

Almost certainly I think. One of the reasons-- actually:

> Do we want to adopt the Angular-recommended file structure?

Yeah. As above, one of the various reasons we want to move to AngularN is that it's more supported / having more development happen against it. So AFAICT we'd want to adhere as close to what a typical Angular app would do. And while both of these last points sound like work / pain, I imagine it's worth it :-)

**Comment by rmhowe** [comment]
**Hi Stefan!!** 🎉 🎉 

All sounds good to me.

> I was planning to do steps 3 and 4 at the same time one component at a time. Do you think there's value in finishing 3 before starting on 4?

My main thinking was to try to leave webapp in the least confusing state possible, and that having both `$scope` and redux around might get confusing, but now that you mention it doing both at the same time will help iron out the kinks in the state management approach which is probably more valuable, and as long as there's no major UI work going on it shouldn't be too confusing. I think the best approach would be to try to make a reasonable design for the store including all app state (without making code changes), and then implement it one component at a time dealing with problems as they come up.

> We also want (maybe need) to move from Browserify to webpack but that might have to wait till we're ready to go to Angular 7+ (step 6).

Sounds good, I’ll look into it but happy to leave it until later.

> I was planning to leave step 2 (TS) until we switch to webpack and angular 7+. Are there advantages to doing it first?

I mainly included it there because the Angular migration docs suggest doing it first, I think so that you can move services and controllers over to TS classes while you’re refactoring. I don’t think there’s any significant benefit either way to be honest, I’m happy to leave it until later so that I can properly get started with steps 3 and 4. It’s also something that can be picked up in parallel if anyone wants to.

**Comment by rmhowe** [comment]
**AT**: This is an ongoing ticket with multiple PRs and is essentially one giant refactor of a lot of the webapp code. The PRs are getting quite big and touching lots of the code so it's starting to be worth ATing, there will be more PRs to come in the next few months that will touch more of the codebase, but for now [the most recent PR](https://github.com/medic/medic/pull/5502) needs AT which updates all references to `selected`. This refers to the currently selected contact/report/message/etc (ie looking at one in a detailed view on the RHS), and also the situation when multiple reports are selected for bulk actions. Any workflow involving these will need to be tested.

**Comment by garethbowen** [comment]
@rmhowe Nice one!

In terms of AT and tracking I think it'd be worth creating new issues for each step (eg: "Move `selected` into redux"). That way we won't have to reopen the same issue for each trip through AT.

**Comment by rmhowe** [comment]
@garethbowen sounds good will do!

**Comment by rmhowe** [comment]
The story so far...

### Major steps in the move
(Strikethrough means it's done)
- ~~Update `ui-router`~~
- Update the state model for webapp
  - ~~Move properties off `$scope` and onto controller or into the redux store~~
  - [Convert `$scope` functions into redux actions](https://github.com/medic/medic/issues/5791) (this will most likely involve removing `$scope.$broadcast` as well, so [this ticket](https://github.com/medic/medic/issues/5624) is probably not needed). This work has been started and there is a WIP branch, details on the ticket.
- Convert all existing controllers into components (should be purely syntax changes)
- Migrate to Angular 7 in one (probably large) merge
  - Replace `uib-modal` with `ng-bootstrap`'s modal component
  - Switch to TypeScript compiler
  - Move all `$scope.$on('$destroy')` to the relevant Angular component lifecycle method

&nbsp;
### General approach taken on work so far
- First preference for properties and functions alike that need to be accessed from a template should be to put them on the controller
- If they need to be used in disparate parts of the app, they should be put in the store (properties) or become an action (function)
- Broadly there are simple action dispatchers (just dispatch an action with a payload), and complex action dispatchers (dispatch multiple actions and may make asynchronous requests)
- `ServicesActions` has been created as part of the WIP [5791](https://github.com/medic/medic/issues/5791) branch to avoid circular dependencies, I don't know whether this a good approach.

&nbsp;
### Changes to be aware of
- Action bar no longer has `selected`, need to read from redux store. This was done because there should only be a single source of truth, app state should not be duplicated anywhere.
- Interface to ContactViewModelGenerator has completely changed, now exposes functions to be called in sequence (rather than exposing one function that does everything for you). This was done as the existing code relied on the state being mutable which is no longer the case.
- Any property that was on scope is now either on a controller or in the redux store. If you can't find it check the relevant controller first then look to the store.

**Comment by garethbowen** [comment]
> Replace uib-modal with ng-bootstrap's modal component

This will also require upgrading to bootstrap 4.

**Comment by latin-panda** [comment]
The documentation for migration to Angular 10 is [here](https://docs.google.com/document/d/18kEKGNmVyu45zg3OH81eFqMMH_sYJE8Q1V35I9SxuMM/)

**Comment by dianabarsan** [comment]
Ready for AT on `master`.
