### ISSUE TITLE
Replace Date.now() with performance.now() in client-side code when not timestamping 

### ISSUE THREAD

**Issue by alxndrsn** [medic/cht-core#4883]
There are a few uses of `Date.now()` where it looks like `performance.now()` would be more appropriate:
```
webapp/src/js/bootstrapper.js:44:    var dbSyncStartTime = Date.now();
webapp/src/js/bootstrapper.js:62:        var duration = Date.now() - dbSyncStartTime;
webapp/src/js/enketo/widgets/countdown-widget.js:159:            animate(Date.now());
webapp/src/js/enketo/widgets/countdown-widget.js:164:        var offset = Date.now() - start;
```
For background, see https://developers.google.com/web/tools/lighthouse/audits/date-now.

**Comment by gudipatiharitha** [comment]
The performance.now() , being  introduced as part of  High-Resolution Time specification(https://www.w3.org/TR/hr-time/) describes the main usecases where Date.now() doesn't suffice and performance.now() would be beneficial is
 a) when sub-millisecond time resolution is needed 
 b) when duration should not be impacted by system clock skew. 

Below are the 3 cases, in  cht-core code base,  where Date.now() - start is used to calculate duration 
1. webapp/src/js/bootstrapper/index.js : The duration from Date.now() is converted from the milliseconds to seconds , so sub-millisecond is not needed 
 _return replicator.then(() => {
      const duration = Date.now() - dbSyncStartTime;
      console.info('Initial sync completed successfully in ' + (duration / 1000) + ' seconds');_
2. In countdown-widget : the offset calculated is compared to "LIM*2" which is "500*@*duration" the default value of duration is 60 , here again, we do not need the sub milli-second precision
_. if(offset < LIM*2) {
const LIM = duration * 500; // Half of the time the animation should take in milliseconds
new TimerAnimation(canvas[0], DIM, DIM, parseInt($el.val()) || DEFAULT_TIME);_
3. It is also use d in check-date.service.ts which also compares duration to MARGINOFERROR which is 10 minutes 
_const delta = Date.now() - timestamp;
        if (Math.abs(delta) < MARGIN_OF_ERROR) {
          // Date/time differences of less than 10 minutes are not very concerning to us
          return;
        }_

Since we are anyways using Date.now() for timestamping and since system clock skew and sub millisecond time duration is not relevant in any of the above scenarios, I think we should not move to performance.now() from Date.now() in the above mentioned scenarios.

Hence, this issue should be marked resolved/won't fix.

**Comment by garethbowen** [comment]
@gudipatiharitha I tend to agree. The description of this issue doesn't explain enough _why_ it would be beneficial to make the switch, given that we don't need that level of precision. It looks like the resource linked would have explained it but now redirects to StackOverflow so that doesn't help.

Closing as won't fix. Please re-open with more info if there's a tangible benefit to switching.
