### ISSUE TITLE
Update text on admin app SMS page

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5387]
Assumes that #5381 is already completed.

**Basic SMS settings tab**
- [ ] Change “Phone number conversion” to say “Country code conversion”

**SMS forms tab**
- [ ] Change the “Import” button to say “Upload”
- [ ] Add text at the top of the upload forms section “You need to choose both an XML file and a Meta file before clicking the upload button. You may only upload one app form file at a time and any existing forms will be overwritten.”
- [ ] Change "Upload forms" title to "Upload SMS forms"
- [ ] Add titles/headers above the table columns in the installed forms section (e.g. "form icon",  "form title").

**Test message tab**
- [ ] Add a page title at the top "Test message"
- [ ] Add description below the title: “Use this page to send a test message to the production application without going through the SMS Gateway. Be sure to use a phone number registered to a CHW’s profile to mimic a report coming from him or her about a particular patient.”
- [ ] Change “Message body” to “Message”
- [ ] Add text description below “Message” field title: “Limit of 144 characters”
- [ ] Change “From” title to “From phone number” 
- [ ] Add text below "From phone number" stating “Please enter a valid phone number without dashes or punctuation”.
- [ ] Change “Submit” button to “Send message”

**Comment by garethbowen** [comment]
Ready for AT in `5387-admin-app-sms-page`

**Comment by ngaruko** [comment]
LGTM.
Just a little nitpick. I think we should hide or enable the `Download` button when there are no forms installed... but since this is not related to the issue ( and it applies to many instances of `download/export` throughout the application),  we will raise another issue for it.
![image](https://user-images.githubusercontent.com/6979995/70582813-9aced980-1c20-11ea-9e49-663fef8e168c.png)
