### ISSUE TITLE
Support a Muso Target - % of families which have received 2 home visits this month

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#5493]
In Muso-land, a "home visit" can occur up to once per day per family. For any given family on any give day, the home visit has occured if either a) any member of the family has a report created on that day (which also meets some specific criteria that isn't important for this bug); or b) the family (clinic) has a home visit report created on that day.

A primary goal for Muso's CHWs is to visit every family twice per month. Muso has requested that a target be written which tracks this goal for CHWs. This number can't be calculated by inspecting the reports for any single contact, it is an aggregation of information from many contacts or many emitted target instances. Since nools does not preserved any state information from one contact to the next, I'm unsure how to build this target in either declarative config or the older nools.rules system.

I suspect we need a product change to support this requirement from Muso.

[Target code for total number of home visits](https://github.com/medic/medic-projects/blob/muso-declarative/muso_declarative/targets.js#L3)

**Comment by SCdF** [comment]
So the two obvious options that I can see here are:
 - Muso changes how they are writing forms so they write a stable form they wish to track against a stable target: in this case a "home visit" form that is always against the family
 - We change how we scope forms in rules to either have no scope, or contain all forms from everyone below the contact under test

Neither of those two ideas in the latter point immediately sound like great ideas to me, though mostly because it would make any eventual movement to server side tasks next to impossible (because having unbounded scope in that situation would be hard to scale).

In terms of the former, we have some very basic ability to create child forms out of parent forms. We might want to consider fleshing out that feature as an alternative to altering the current rules scoping.

**Comment by abbyad** [comment]
The closest I can think of doing this is by manually setting the `_id` to that of the home (eg `${clinic._id}-${target.id}`), and applying it to all contacts of type `clinic` to make sure to get the denominator. To include reports submitted to family members you could dedupe on the id, but there is no sense of how many of those were on same day and shouldn't be included. Also, this wouldn't really solve the request, since the threshold for a pass would be 1 visit, not 2, as used by Muso. 

Unless someone has an idea of how it can be done, I would say this is not feasible with our current system. As opposed to changing the scope for rules, perhaps the request here is to have a new widget (eg `percent_uhc_coverage` instead of `percent`) that handles this scenario, which would also take into account the date window and threshold set in app_settings. 

We should determine if this is necessary now, or better to leave it for a future improvement to UHC mode. cc @MaxDiz

**Comment by kennsippell** [comment]
@abbyad I have written the target to track home visits [here](https://github.com/medic/medic-projects/blob/muso-declarative/muso_declarative/targets.js#L142). As you mention, the hard part is counting iff it happens twice.

It isn't feasible with our current system - this is a feature request from Muso. 

*I'm not saying this is a good solution - it illustrates there is a solution.* The most bare-bones implementation I can think of would be to alter the logic which we use to [merge and count target instances](https://github.com/medic/medic/blob/master/webapp/src/js/services/target-generator.js#L58) to track n occurrences of instances. The instance emitted by nools would need to be altered to split the id into two parts - the first part is the id of the unique thing to be counted (in this case the family id), and the second part is the unique id of the occurrence (in this case, the date). Then we count a given unique instances only when the set of unique occurrences is larger than n.

I have no idea if this request is _important_ -- but it can certainly be done. Ideally, it would be nice to build it in either a general manner which would be useful to other projects, or which uses an extensibility pattern such that it only runs for Muso. Both of these paths would likely take thought and discussion.

**Comment by kennsippell** [comment]
[Here](https://github.com/medic/medic-projects/commit/4b5eb91da71f7049b53fe817d5df9156b0536b7b#diff-fea27642d3def321e19d0f41eec7d3bbR167) is an example of how https://github.com/medic/medic-conf/pull/165 can be used to implement this rule.

I also attempted to do this using "nools rules" but was not able to do so without a webapp update..

**Comment by PhilipNgari** [comment]
Thanks team. @kennsippell . How would the webapp update look like. How long would it take and is 3.7x release the immediate solution. I may lack more details for now but happy to chat more about it.

**Comment by garethbowen** [comment]
@kennsippell I think we'll need one more PR for medic-docs changes to include those new schema params.

**Comment by kennsippell** [comment]
I've batched the documentation changes into the medic-conf 3.1 changes here: https://github.com/medic/medic-docs/pull/164

**Comment by kennsippell** [comment]
Ready for AT on
* medic-projects/muso branch `2home-target`
* medic-conf: `5493-2home`
* cht-core: `5493-2home`

**Comment by kennsippell** [comment]
Assigning @senseibara because he is ATing this on https://sih-muso-mali.dev.medicmobile.org

**Comment by senseibara** [comment]
ATed and looks good to me

**Comment by kennsippell** [comment]
Waiting to merge #6178 until base branch #6041 merges.

**Comment by kennsippell** [comment]
Based on feedback from the documentation review, I'm going to rename `passGroupWithCount` to `passesIfGroupCount: { gte: 2 }`. This change aims to be more clear to partners and be more clearly extensible as other group-scenarios are requested.
