### ISSUE TITLE
Replace all FontAwesome icons with svg icons

### ISSUE THREAD

**Issue by amandacilek-zz** [medic/cht-core#5535]
Our app currently uses a mix of FontAwesome icons and custom png or svg icons. This request is to conduct a clean sweep of the app and replace ALL instances of FontAwesome icons with svg versions, and replace any random png icons with svg. This relates to any system icons that are embedded in the app (navigational page icons, hamburger menu icons, admin app). It does _not_ include an audit of form icons, since those are configurable by the partner.

Switching to the svg format allows us to use new custom icons that better convey the meaning instead of being limited to FontAwesome's generic library. Svg also ensures greater control and predictability when placing/aligning the icons in the app. The benefit of svg over png is that svgs can be re-colored directly in the app code. All of the icons are now a singular color to enable optional re-coloring in the code. Some of the new icons will appear quite similar to the icons we've always been using while others have been updated to improve clarity and/or consistency. 

![Screen Shot 2019-03-25 at 4 48 20 PM](https://user-images.githubusercontent.com/26235957/54962115-e1f52d00-4f20-11e9-978b-8d2430c5c7fc.png)

Icons for the primary page tabs should be displayed at a 30 x 30 px size.
- Messages used to be an envelope but is now conversation bubbles, to more accurately reflect the chat-like nature of the experience
- Tasks used to be a flag but is now a person holding a bag walking to conduct a visit.
- Reports used to be an abstract bulleted list but is now an open book to indicate records.
- People used to be a singular person and is now a group of people.
- Analytics used to be a bar chart and is still a chart but with a trend arrow.

![Screen Shot 2019-03-25 at 5 07 03 PM](https://user-images.githubusercontent.com/26235957/54962048-9b073780-4f20-11e9-9420-59e2d7ba4cc4.png)

All of the icons in the hamburger menu also have new svg replacements, as well as all of the icons that appear on the admin app/configuration pages. Hamburger menu icons should be displayed at a 20 x 20 px size (for now, until nav update). Any other icons that appear anywhere else in the app, such as the admin app, should default to display at 30 x 30 px.

The source svg files can be downloaded at https://drive.google.com/drive/u/1/folders/1PQ3Ydd3CyHToHXYnRx0oMPsTpkT3i3cv.

**Comment by garethbowen** [comment]
@MaxDiz We should consider scheduling this - the icons have been prepared and we can now add them to the app without too much difficulty. This would also improve performance by not downloading the whole FontAwesome font.

**Comment by MaxDiz** [comment]
Looks like a good add for v3.7.0. We'll have to make sure to notify PM's of icon changes in case there is confusion from health workers/supervisors

**Comment by amandacilek** [comment]
Note: This also needs to include form summary pages. The summary page headers currently use FontAwesome icons and these will also need to be updated to direct to the new icon library icons. 

Gareth says: Ideally I think they would be updated manually. We could also provide some CSS styles that would map from common FontAwesome icons to the new ones to make the transition easier.

**Comment by amandacilek** [comment]
Might not be a bad idea to also do #5804 at the same time, which would help minimize confusion during the transition by adding page text labels on small mobile devices for users who see only 3 tabs.

**Comment by elvisdorkenoo** [comment]
### Here is the summary of our latest findings about the Font Awesome upgrade to version 6
**Pros :**
-[ Font Awesome](https://fontawesome.com/docs/web/setup/get-started) version 6 is very rich and have much more icons that ever
- Upgrading from version 4 to version 6, JS + SVG is possible and relatively easy, thanks also to some shims resources that ensure backward compatibility with version 4.
_Installation resources [here](https://fontawesome.com/docs/web/setup/host-yourself/svg-js)_
Upgrade from version 4 guide [here](https://fontawesome.com/docs/web/setup/upgrade/upgrade-from-v4)

**Cons :**
- Font Awesome is no more completely free, there are a free, pro and pro max versions ;  and the free one is pretty limited. Find plans [here](https://fontawesome.com/plans)
- Many of the new icons are not free, only accessible through Font Awesome Pro licence price at $99 per year
- Distribution problem : If we buy the pro version, and a technical partner host their own, they may have to buy their Pro subscription
- Under the pro license you get 1M pageviews a month. Even though we're a single page app it means every time the user changes the URL that's another pageview. We're currently (in 2022) doing ~2M caring actions per month across all projects which is way over that limit.
- FontAwesome no longer work in our Open Source culture(...).

**Conclusion** 
This investigation really helped us learn a lot about the newest version of FA, the complexities of upgrading it, as well as their new licensing model. This helped us realize that, for now, it is not in our best interest to go ahead with a FA upgrade. Due to this and the fact that decoupling the CHT from FA would be a pretty significant undertaking, we have decided to table this issue for now.
Find the last Draft PR [here](https://github.com/medic/cht-core/pull/7640) with all font awesome upgraded to version 6 and most of the icons replaced with svg font awesome 6 free version.

**Comment by jonathanvq** [comment]
@michaelkohn, given what @elvisdorkenoo explained here, what should we do with this ticket? Should it be put "on hold" or something similar? Not sure if a status like that can be used, but something that helps us understand that we won't be looking at this for the time being different to simply still being "open"?
