### ISSUE TITLE
Use IDBNext

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#5552]
We've done a bunch of work around getting IDBNext ready to go, but so far haven't put the final amount of effort into being able to use it.

Specifically, we need to find the time to:
 - Get PouchDB folks to be OK with and release the adapter into the npm ecosystem so we can use it as an alternative (or publish it ourselves under `@medic`)
 - Create a branch that uses it and takes advantage of it to use Mango efficiently, for testing 
 - If this goes well, work out how we want to migrate from the `idb` adapter to the `indexeddb` adapter, and implement it

This ticket is a medic-side ticket we can schedule into releases / time blocks so it doesn't stay under the radar.

**Comment by garethbowen** [comment]
@SCdF I'm wondering if you'd be happy with splitting the Mango part into a separate issue? It seems to me like it could be done before, after, or at the same time as the `indexeddb` adapter switch.

I'm comfortable by publishing it in our own branch if necessary but it's definitely worth pushing PouchDB to release it as well.

I'm scheduling this for 4.0.0 because the migration step may make the upgrade process more difficult than usual for users.

**Comment by SCdF** [comment]
@garethbowen yep that makes sense: Mango === less indexes, which is good even if they are not as fast as they'd be in IDBNext. Would you like me to raise a separate issue here?

**Comment by garethbowen** [comment]
Yes please!

**Comment by SCdF** [comment]
See: #5592

**Comment by garethbowen** [comment]
Closing this as obsolete. The pouchdb side is done, and the CHT side is better covered here: https://github.com/medic/cht-core/issues/9208
