### ISSUE TITLE
Add feature to create a place via SMS

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#5614]
You can create a patient using the `add_patient` trigger on the [registration transition](https://github.com/medic/medic/blob/master/sentinel/src/transitions/registration.js#L349) but there's no way to create a place via SMS so if you want to register a new household you need to do that in the webapp before registering the patients.

Add the ability to register a place via SMS at the right place in the hierarchy. The place may have a unique `place_id` generated allowing contacts to be created as children of the place.

Example workflow:

1. CHP: `RF Smith family` (where RF is a JSON form for registering families).
2. Response: `Smith family registered with place ID 11111`
3. CHP: `R 11111 John`
4. Response: `John added to the Smith family with patient ID 11112`
5. CHP: `R 11111 Jane`
6. etc...

**Comment by abbyad** [comment]
We have heard that scale up of some deployments could be limited by users not all having smart devices. This is a feature that would be key to closing the gap between SMS workflows and app workflows.

**Comment by ranjuts** [comment]
++1 to this feature on behalf of MOH Nepal as well. 

Adding a few relevant suggestions  and considerations: 

>Specific to adding families or generic to any place?
- Should the text form be specific to adding families or could it add any place as it is relevant to the particular user type? e.g. if a CHW sends the form it creates a family and if a CHW supervisor sends the form it creates a CHW area.

- If specific to adding family, should be able to configure permissions for whether or not anyone other than a CHW should be able to create a family and be able to send error/warning messages accordingly.

Example workflow: 

1. CHW supervisor or a non-CHW: `RF Smith Family` 
2. Response: `Cannot register a family in your area. You have to be a CHW to use this form correctly.`

> Would there be a need for CHW supervisors to add family via SMS? 
- If we require this feature to cover a CHW supervisor's ability to add family to a CHW Area (as opposed to her own), there should be a way to specify which CHW area the family belongs to. She could either begin by adding a CHW Area first or use a CHW Area ID if that is available. Either way, she would have created a CHW Area first. 

Example workflow: 
 
1. CHW supervisor: `RCA Anne's Area`
2. Response: `Anne's Area CHW Area registered with Place ID 11111`
3. CHW supervisor: `RF 11111 Smith Family`
4. Response: `Smith Family added to Anne's Area CHW Area with Place ID 11112`
5. CHW supervisor: `R 11112 John`
6. Response: `John added to Smith Family with patient ID 11113` 

*(this would create various complications, one being the fact that the create family form might need to have the CHW Area ID field as non-required as the same form would be used by a CHW to create a family in which case the Area ID is not needed. We can also not have a generic form for creating any place.)*

> Strong recommendation for family ID (or place IDs) to have different formatting compared to patient IDs
- If the generated family ID looks identical to a patient ID, there are huge chances of confusion and error among CHWs. Consider different formatting for a family ID -- e.g. F123. 

- Not as critical as being able to differentiate patient IDs from family IDs but if we allow other places to be created by SMS it would be ideal to have different formatting for each kind of place ID. e.g. CA123 for CHW area. 

> Consider existing form fields in a new person form and flexibility required for project specific designs (this might not be relevant for the feature itself but for design and config later)
- In Nepal, the new person form includes an age field so would need to consider the form design and length as well if we need to add a field for family ID, a second numeric field 

cc @aikajanet @derickl @PhilipNgari

**Comment by leah-ngaari** [comment]
Adding here a related request
User story
As CHW Supervisor (MoH) I would like to know the number of HHs regitered in the system under each CHW. I would also like to know the number of HHs members in each of the HH within my area of coverage.

Request:
 -Add the ability for CHWs to register Households through SMS.  A unique ID is assigned to the registered HH and then the ID is used to register HH members. 

Example of workflow

1. CHW : H Mark Mark
2. Response: Thank you for registering Mark's HH. HH ID is 12345
3. CHW: N HHID(12345) Mercy Kinoti
4. Response: Thank you for registering Mercy. Her ID is 33445

Cc @mouriceb

**Comment by mouriceb** [comment]
There was also this request related to what is described here.
https://github.com/medic/medic-projects/issues/3115

CC: @SMurithi

**Comment by abbyad** [comment]
@leah-ngaari, is your user story a different feature request? If so it should be opened as a new issue.

**Comment by MaxDiz** [comment]
Noting the open workflow items identified by @ranjuts above. Requesting that the assigned eng coordinate with Ranju to clarify workflows and define acceptance testing criteria

**Comment by dianabarsan** [comment]
Had a discussion with @ranjuts and these are the conclusions:

1. The `registration` transition will be used to create places by SMS by adding additional triggers.

2. > Specific to adding families or generic to any place?

This will be generic as now hierarchies can be configured. The `registration` config for the forms that create places will include a parameter called `contact_type` that determines which place type the form creates.

Because we can have multiple place types at the same level, allowing the ommision of this parameter could make a form permanently fail if it would have the possibility of creating 2 place types at one level. 

3. > Strong recommendation for family ID (or place IDs) to have different formatting compared to patient IDs

The reason for this request was to avoid errors where users would use place ids instead of person ids. 
We agreed (as per @garethbowen 's recommendation) that we could add this feature in a future iteration and have place ids follow the same pattern as patient ids for now. 

Other things to consider:

1. Should we check for `can_create_places` permission?
2. Should we check the user's `replication_depth` config and not allow too deep place/contact creation?

**Comment by garethbowen** [comment]
> Should we check for can_create_places permission?

I think so.

> Should we check the user's replication_depth config and not allow too deep place/contact creation?

I don't think that's necessary. Replication depth is usually about hardware limitations rather than permissions. It'd be a little strange because you would create a new place that you can't see. It's an edge case anyway because if they're creating places via SMS they're probably not also replicating.

Currently we hardcode the patient's parent to the contact's parent. I think this will have to be changed so you can, for example, create a family and then create a family member whose parent is the family not the chw area. This will also require some validation to make sure you're creating contacts below parents that are below your place.

**Comment by ranjuts** [comment]
@leah-ngaari @smbuthia could you take some time tomorrow to read above and verify that this fulfills the requirements for MOH Kenya? During my conversation w Diana I shared whatever insights I had from my experience here and a conversation we had with the team there in May. It would be good to verify we aren't missing any new context. Thanks! 

cc @katanu

**Comment by abbyad** [comment]
To clarify, there was a recommendation for family ID (or place IDs) to have different formatting compared to patient IDs. After discussion it was suggested that "we could add this feature in a future iteration and have place ids follow the same pattern as patient ids for now."

The trade-off in introducing different formats for family ID vs person ID at a later time is that a deployment that was previously using the same format for family ID and person ID will have challenges if the format changes. On the **user side**, CHWs will have a mix of formats for old and new families which may be confusing to the user. On the **config side**, you would have to validate a place ID for both formats. There will likely be validation message if a place doesn't exist, but the response would have to be generic, like `make sure to use a valid place ID`, instead of being able to give a more helpful message like `Place IDs are formatted "PXXXXX"`. 

**It is possible that having the same ID is fine for partners and users**, I just want to make sure that these trade offs are well understood so that we can determine if having different formats is a requirement, or an optional nice-to-have that can be made available only to **_new_** deployments at a later date.

Either way, making the person and place IDs have different formats does not block this issue. It can be done as a separate issue, and included with this release if needed.

**Comment by ranjuts** [comment]
Upon further thought and follow up discussion w Marc and some other designers, it seems wise to dig further the question of same vs different ID formats for people vs places. There are user, config and deployment side questions to think through before deciding on whether to format these IDs differently + whether to phase the feature out as suggested above. 

Creating a separate ticket for it. Will move relevant information from here, add further context and link here. Also awaiting further thoughts from the team working w MOH Kenya - due early next week.

**Comment by smbuthia** [comment]
@ranjuts this looks like it fulfills the requirement for MoH Kenya. 
Some of the key considerations we have are:
1. Registering households and using the household IDs to register household members
2. Submitting reports on a household. For example, a household visit form
3. Aggregating household data in analytics; both in-app and Klipfolio 

Assuming the implementation works the same way as App place creation (places are created as contact documents), then all our considerations are covered.

Concerning the ID formats, Leah and I discussed this and think it would be better to have consistent ID formats throughout a deployment. We thought of some options that could facilitate this:
1. Updating existing HH IDs after(or during) an upgrade to the version that has different format place IDs (perhaps by appending a prefixed code)
2. Having the version that supports different format place IDs be backward compatible and also support the old ID style (perhaps by having a transition that triggers this)

**Comment by garethbowen** [comment]
Ready for AT in `5614-place-by-sms`

**Comment by garethbowen** [comment]
@ngaruko Documentation for the new feature is in the medic-docs branch here: https://github.com/medic/medic-docs/pull/157

**Comment by dianabarsan** [comment]
Back in development for a little bit to create a new transition and alias `generate_patient_id_on_people` as per https://github.com/medic/medic-docs/pull/157#discussion_r351787786

**Comment by garethbowen** [comment]
Ready for AT again!

**Comment by ngaruko** [comment]
LGTM. 
This feature depends heavily on configured hierarchy. I am running this to a tech lead o give it a quick test with a couple of different configurations and hierarchies before closing it off!

**Comment by garethbowen** [comment]
Merged.
