### ISSUE TITLE
Sentinel should have a status page

### ISSUE THREAD

**Issue by henokgetachew** [medic/cht-core#5663]
It's hard to monitor sentinel as it stands.  It's usually determined based on if its actions haven't been performed that we know sentinel is down.

In order to be proactive in monitoring it, the best way seems to be to have a status page that just tells you that it's running.

This would make it so that we could monitor it from outside of the instances as well and build alerting on top of it.

**Comment by garethbowen** [comment]
This information should also be exposed via an API for automated programmatic access (read: medic-bot v2).

**Comment by garethbowen** [comment]
There are now a range of sentinel metrics exposed through the [monitoring API](https://docs.communityhealthtoolkit.org/apps/reference/api/#get-apiv1monitoring), including: outbound_push.backlog, messaging.outgoing, sentinel.backlog.

@henokgetachew I'm tempted to close this out, unless you can think of other sentinel metrics to add?

**Comment by henokgetachew** [comment]
How about something like sentinel_status : running or scheduled to run within 5 minutes or last run 5 minutes ago? Could we have an API that we could ping just once and know whether there is a sentinel issue or not?

**Comment by garethbowen** [comment]
> a sentinel related problem?

Those three backlogs I put above are the most useful symptom of a sentinel problem - if the backlogs are growing then something is wrong with sentinel. We don't currently store when the schedule last ran. We could add this and then report on it through the monitoring API but I'm not sure how useful that is, for example, the three states you suggest are all signs of a healthy sentinel. In your experience when we have a sentinel problem is it because the schedule isn't running, or the run is crashing or taking too long, or sentinel is not keeping up with the incoming docs, or the whole service is not running, or something else?

**Comment by michaelkohn** [comment]
@henokgetachew do you have any further responses/updates/context based on Gareth's comment?

**Comment by garethbowen** [comment]
Closing as watchdog covers the main issues here. Please reopen this, or open another issue against watchdog if something in particular is missing.
