### ISSUE TITLE
Allow  Sentinel scheduled time to be configurable

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#5720]
**Is your feature request related to a problem? Please describe.**
As a QA tester waiting 5 minutes to test something that sentinel is running over is extremely painful. 

**Describe the solution you'd like**
Read a value from app_settings to configure the time for which sentinel runs.

**Comment by garethbowen** [comment]
Alternatively we could consider just setting it to 1 minute for everyone. This has the added advantage of making scheduled message sending a little more responsive with the downside of additional load on the server.

**Comment by Hareet** [comment]
> downside of additional load on the server.

There are some heavily multi-homed servers that could crawl with this change.  I'm also a little concerned about configuration for this option -- if someone sets it to 30s, 15s and accidentally stalls other multi-homed projects. Here's a quick SRE test that would make us feel more comfortable.

SRE testing scenario:
- Start view warming or another heavy CPU/Mem process on 2 multi-homed projects (we'll call this Server A)
- Upgrade gamma.dev on server A to handle this feature
- Monitor for 3 days

@henokgetachew - Anything else we could test?

**Comment by garethbowen** [comment]
@Hareet I don't think the load would be significant. Most of sentinel runs when something changes in the database. The scheduled part is just checking for if there are messages due to be sent, and sending them. It's reasonably lightweight, but might mean we have to reindex some views more often.

If we make it configurable we should definitely validate the setting so it never checks more often than every minute.

Many of our projects are smartphone only and never even send SMS which means this schedule is a waste of resources. I think we should also make it so we can disable it completely in configuration, potentially defaulting to false, or add some logic to detect if it's possible for a scheduled SMS to be generated with the current configuration. Then we can move the `due_tasks` view out into the `medic-sms` ddoc so most projects will never need to index the view again.

If we did this in combination with changing the timer to 1 minute then I think the overall load on the multi-homed servers would reduce (disclaimer: this needs to be proven).

**Comment by Hareet** [comment]
Thanks for the clarification @garethbowen 

I'll watch this discussion as it continues.

**Comment by SCdF** [comment]
For testing, if you restart sentinel it runs them straight away, and sentinel is safe to restart as much as you like.

**Comment by dianabarsan** [comment]
With https://github.com/medic/cht-core/commit/4090a4bdc049f4add6715df67f3e8a5ffad6f61c, Sentinel now listens to `SIGUSR1` to toggle off transitions and `SIGUSR2` to run all scheduled tasks.
