### ISSUE TITLE
Show a prompt when we detect the user is logged out

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#5772]
In 3.6.0 we implemented a [feature](https://github.com/medic/medic/issues/3919) to detect if the user's session has expired and redirect them to the login page. This cleans up a bunch of issues where the app started behaving strangely with no notification. As @dianabarsan [noted](https://github.com/medic/medic/issues/3919#issuecomment-503955033)...

> Every type of automatic (background) replication will redirect any type of user to the login page without warning and without being triggered by the user interacting with the app. If it's not too difficult, I think it would be much less intrusive to show a popup that informs the user that they have been logged out - similar to the one we use to prompt users to refresh once the app is updated.

Improve the current handling by showing a popup with an appropriate warning.

1. If the user chooses to login, redirect to the login page.
2. If the user cancels out of the popup, then show it again in some time (roughly 5 minutes?).
3. If the user doesn't interact with the popup at all for one minute then assume they've stepped away from the keyboard and not currently in the middle of a task and redirect them to the login page.

**Comment by SCdF** [comment]
Ready for AT on `5772-prompt-on-session-expiry`
 - Whenever a user's session expires you should get a prompt that you are being logged out¸as opposed to just being silently redirected to the login page
 - This won't be instant with offline users as it requires that they are online and have performed a request (otherwise we can't tell that the session has expired)

(easiest way to expire sessions is to change the secret in CouchDB, as that will invalidate all existing sessions. Using the UI to change your own password will also expire it. Otherwise waiting around is the other way)

**Comment by ngaruko** [comment]
LGTM - Ready to merge @peter-ochieng .
![image](https://user-images.githubusercontent.com/6979995/79302550-cfd99880-7f40-11ea-9a63-6e5671c6537f.png)

**Comment by peter-ochieng** [comment]
Merged into `Master`
