### ISSUE TITLE
Cluster safe credentials

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#5904]
With SIH and AT we use a special section of the couchdb node configuration called `medic-credentials` to store secrets such as passwords and API keys. This works well in that couchdb protects this so only admins can access it, however it's node specific so if we decide to have multiple couchdb nodes it will have to be separately configured in each node. With a greater focus on integrations and potentially plugins this concept will become more widely used so we should find a more future-proof way to store credentials.

The surest way to be cluster safe is to store the data in the database itself so work towards that. The issue then becomes how to secure the data so only admins can access it, for example, make sure it doesn't accidentally get replicated to the client or couch2pged into postgres.

**Comment by SCdF** [comment]
Is the expectation that the credential code is going to last long enough to hit clustering concerns?

I'm not familiar with AT, but for SIH the reason for the credential work is where it is (e.g. in our codebase at all) is because that's where we put the very basic outbound conversion work. As we deploy more external integrations this relatively basic work will either need to be extended upon pretty thoroughly or (and this was the going thought) replaced with something much richer than what is there.

**Comment by garethbowen** [comment]
AT has been developed to be a permanent feature so it'd be good to get the credentials sorted before it becomes an issue. In general I think there is a use case for storing sensitive information particularly in regards to push integrations for which there is growing demand.

**Comment by garethbowen** [comment]
The workaround for this is to set the credentials on every node in the cluster.

**Comment by garethbowen** [comment]
Scheduled for 4.0.0 because this should be done alongside the horizontal scalability work.

**Comment by garethbowen** [comment]
When working on this also make sure that the credentials aren't logged in a production environment particularly by haproxy. We added specific code to mask the password to fix [this issue](https://github.com/medic/medic-infrastructure/issues/147) so as long as the new request matches that regex it'll be masked there too.

**Comment by garethbowen** [comment]
Next steps here...

Once archv3 is merged, rebase, and then it'll be ready for AT.

**Comment by garethbowen** [comment]
Ready for AT in `5904-cluster-safe-credentials`.

AT instructions:

- Set up the outbound-express server to test outbound push: https://github.com/medic/support-scripts/tree/master/outbound-express
- Set up outbound push as per [the docs](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/outbound/)
- Store the credentials as per the [docs PR](https://github.com/medic/cht-docs/pull/668)
- Then make sure the new credentials are being sent to the outbound-express server.

Also test that [this security issue](https://github.com/medic/medic-infrastructure/issues/302) is fixed at the same time.

**Comment by ngaruko** [comment]
Few notes:

1. Reference to expired link in [api keys section](https://github.com/medic/cht-docs/blob/107f31b9df52c00a5277aefb86a99d3d0d0fbed2/content/en/apps/guides/messaging/gateways/africas-talking.md#api-keys). - [CHT credentials API](https://github.com/medic/cht-docs/blob/107f31b9df52c00a5277aefb86a99d3d0d0fbed2/apps/reference/api#put-apiv1credentials)

**Comment by ngaruko** [comment]
Couple of notes:

1. Reference to broken link in [medic-vault ](https://github.com/medic/cht-docs/blob/107f31b9df52c00a5277aefb86a99d3d0d0fbed2/content/en/apps/guides/database/_index.md#medic-vault)section : see [Credentials API](https://github.com/medic/cht-docs/blob/107f31b9df52c00a5277aefb86a99d3d0d0fbed2/apps/reference/api#put-apiv1credentials). And [outbound.js](https://github.com/medic/cht-docs/blob/107f31b9df52c00a5277aefb86a99d3d0d0fbed2/content/en/apps/reference/app-settings/outbound.md#destination). See [API documentation](https://github.com/medic/cht-docs/blob/107f31b9df52c00a5277aefb86a99d3d0d0fbed2/apps/reference/api#put-apiv1credentials).
2. The [OutboundError](https://github.com/medic/cht-core/blob/5904-cluster-safe-credentials/shared-libs/outbound/src/outbound.js#L33) might need to be updated to refer to `medic-vault/{key}` instead of `medic-crententials/{key}` and it is probably no longer a config key??
3. Since the documentation wasn't too clear on new ways to save credentials, I attempted to save them straight into the `medic-vault` db. Following the code, I gave the doc the [id](https://github.com/medic/cht-core/blob/5904-cluster-safe-credentials/shared-libs/settings/src/index.js#L8) of `credential:Outbound` :```{
  _id: 'credential:Outbound',
  password: 'Outbound'
}```
 > Then I triggered the outbound and this error popped up : 
```
2022-07-20 11:27:40 ERROR: Failed to push 937b2d7b-22ec-4080-b411-d975458fac1e to express_config: Error: Invalid IV length
    at Decipheriv.createCipherBase (internal/crypto/cipher.js:103:19)
    at Decipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)
    at new Decipheriv (internal/crypto/cipher.js:264:22)
    at Object.createDecipheriv (crypto.js:132:10)
    at /Users/bede/tests/cht-core/shared-libs/settings/src/index.js:70:31
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  [stack]: 'Error: Invalid IV length\n' +
    '    at Decipheriv.createCipherBase (internal/crypto/cipher.js:103:19)\n' +
    '    at Decipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)\n' +
    '    at new Decipheriv (internal/crypto/cipher.js:264:22)\n' +
    '    at Object.createDecipheriv (crypto.js:132:10)\n' +
    '    at /Users/bede/tests/cht-core/shared-libs/settings/src/index.js:70:31\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
  [message]: 'Invalid IV length'
}
```
>> Any thoughts @garethbowen ?
PS: Tested on local/dev environment -

**Comment by ngaruko** [comment]
Oh. One thing though @garethbowen ...
The [OutboundError](https://github.com/medic/cht-core/blob/5904-cluster-safe-credentials/shared-libs/outbound/src/outbound.js#L33) might need to be updated to refer to `medic-vault/credential:${key}` instead of `medic-crententials/{key}` and it is probably no longer a config key??

**Comment by garethbowen** [comment]
@ngaruko I've improved the error message, thanks!

I have a couple of follow up questions...

1. In your log output it looks like we're logging the `auth` section with username and password in plaintext. Is that right?
2. In the security issue log it looks like you've looked in and API log, but the issue was in the haproxy log which has a slightly different format. Can you check the haproxy log?

**Comment by ngaruko** [comment]
@garethbowen 

1. I think those logs come from [this line](https://github.com/medic/cht-core/blob/899e30df5fc6b7c52c99893609887ae714c87cd0/shared-libs/outbound/src/outbound.js#L176) but are not logged in `happroxy`
2. For the security issue, I also checked in `happroxy`, there are obfuscated  when we save credentials
![image](https://user-images.githubusercontent.com/6979995/180114605-9fbdcde3-c9a9-4d96-ac45-b3ee79b7efaf.png)

**Comment by garethbowen** [comment]
@ngaruko Ok, I think the debug logging is an issue. We should never log a password in plaintext. I've made a change to the PR to mask this line specifically. Would you mind testing that again, when the build completes?

**Comment by ngaruko** [comment]
Looks good atm @garethbowen 
<img width="750" alt="image" src="https://user-images.githubusercontent.com/6979995/180128752-568e3e70-7c14-4a47-97e0-30b7a9b0241f.png">

**Comment by garethbowen** [comment]
Merged!
