### ISSUE TITLE
Login page dynamic elements don't work correctly

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#5954]
**Describe the bug**
Because the login page is cached by the service worker, any code that gets run when that page gets rendered only gets run once, at the point that the device first visits the login page. You can see all this code in [`login.get`](https://github.com/medic/medic/blob/master/api/src/controllers/login.js#L186).

This logic includes:
 - White labeling / branding
 - Translations
 - Redirection (though this appears to be additionally broken by other code as well)

It gets more complicated, because somehow regardless after you wipe the service worker to force it to call `login.get` again fresh, the *next* reload defaults the login page back to a vanilla version, e.g. with no redirect url (despite what you passed it) and English (despite what your language is set to).

**Reproduction steps**

(bonus, boot api with a debugger via `node --inspect server` etc and put a break point in `login.get` for extra details)

1. Successfully and completely log in to the application as any English-language user (I used a online user) into an environment with multiple languages
2. Change your user's language to something else (e.g. French)
3. Log out
   - Here you would **expect** the login page's language to be French, but you **observe** it's still English
   - (also note that `login.get` never ran)
4. Unregister the service worker, by (in Chrome) going to dev tools -> Application -> Service workers and clicking 'Unregister' for your URL
5. Refresh the login page
   - (notice now `login.get` runs)
   - Note that the login page is now in French
5. Refresh the login page **again**
   - (once again `login.get` doesn't get run)
   - Note now that the login page is **back to English**  

**Environment**
- Instance: Localhost running master
- Browser: Chromium 76
- Client platform: Linux
- Version: master

**Comment by eljhkrr** [comment]
Hey folks, I've been looking at this and realized there are several approaches we can take to solve this. Some involve architectural changes and because login is a key component of the CHT app, I'd love to hear your thoughts on the most effective solution:

1. Move login into the webapp and let angular handle translations.

2. Implement cache-busting logic that watches for locale updates.

3. Find/implement a lib that can handle locale updates independently.

I'm for option 1 since unauthenticated requests hit the webapp anyway and we may want to retain caching benefits associated with this flow. It's also possible to delegate authentication to the API and then send users to the webapp if they make it through. Feel free to discuss what's works best.

**Comment by SCdF** [comment]
@eljhkrr thanks for the summary! You have been looking into 1, correct? Where did you get to with that, what issues have you faced etc?

Also, I'd be interested in what you consider the pros and cons of each approach. 

Since we are loading the entire app when you hit the login page it definitely lends weight to 1. The only obvious downside is that we'd have to also parse and execute on the entire app before the login page displays. With Angular 2+ I believe this would be solvable, as login would be its own module (or whatever that terminology is)

**Comment by eljhkrr** [comment]
Hey @SCdF! Not much has been done for opt 1 aside from feasibility studies. With the planned migration to angular 2, we can split login into its own module and avoid bloat. I'll be looking into how this can work and update the comment above with more pros & cons as I think of them.

**Comment by SCdF** [comment]
@garethbowen I put this in 3.9.0 because it blocks #5955, which is already in there

**Comment by garethbowen** [comment]
I'm looking at this as part of #6280 which specifically deals with the translation elements.

There are three parts to this which can all be handled separately...

1. Branding. This should be cached but we need to implement cache busting so if the config is updated the service worker downloads the updated files. At the moment the service worker definition is generated at build time and bundled with the release so it doesn't get busted when config changes. One solution is to generate it at runtime so we can regenerate it when config changes.
2. Translations. We want to be able to translate the page dynamically so if users change their language the login page is the right language. This could be handled by Angular but it's a very heavyweight library to load just for this. I think this can be managed by vanilla JS and I'm having a look at that now. The translations values will be cached so if settings are updated these won't show without some cache busting described above.
3. Redirect URL. This is passed as a parameter to the URL so I think with a little vanilla JS we can easily pluck it out and use that rather than passing it to the template and caching it. I'll have a look at this one as well.

The cache busting is lower priority than the broken redirection and static translations, so I propose we raise a new issue on the backlog for it.

**Comment by garethbowen** [comment]
I'm going to close this issue because it has been split up and documented in other places.

1. As part of #6280 (in progress) the user's locale is not cached and can be switched dynamically.
2. As part of #5955 (in progress) the redirect is not cached and is parsed from the URL dynamically.
3. Finally in #6338 (scheduled) updating the branding and translations will expire the service worker cache so the login page is downloaded again.

Please reopen or comment if anything's been missed!
