### ISSUE TITLE
Missing translation warning is displayed in console but doesn't seem to do anything when provided. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6062]
**Describe the bug**
When viewing the deceased contacts list page a warning is displayed in the console `Translation for contact.deceased doesn't exist`. Adding a key value for `contact.deceased` to your language file doesn't seem to get used but does clear the error. 

**To Reproduce**
1. Add a person who is deceased using the CHT/default config. 
2. Navigate to the deceased list page. 
3. The console displays the warning  `Translation for contact.deceased doesn't exist`. is shown. 
4. Add a key value for `contact.deceased` to your language file and upload.
5. The warning is removed but that isn't displayed. 

**Expected behavior**
I'm not real sure what that value is supposed to be used for. Might be worth just removing. 

**Environment**
- Instance: gamma.dev
- Browser: chrome
- Client platform: linux
- App: webapp
- Version: 3.7

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by garethbowen** [comment]
It's used in the title bar when viewing a deceased person which is only shown on mobile. We have a similar translation key "contact.deceased.title = Deceased" defined in the main translation file which I think we should use here instead of introducing another translation key. Either way we should not ship with translations missing, so let's get this fixed.

**Comment by garethbowen** [comment]
Ready for AT in `6062-reuse-deceased-translation-key`

**Comment by newtewt** [comment]
Looks good.
