### ISSUE TITLE
Confirmation notification displayed while navigating away from tasks list

### ISSUE THREAD

**Issue by ranjuts** [medic/cht-core#6065]
**Describe the bug**
While navigating away from the tasks tab, we are seeing a notification that we are supposed to get while exiting an incomplete form. If we reload, then the notification clears and then only you navigate to the other page chosen. 

**To Reproduce**
1. Go to tasks tab.
2. Click on any task.
3. Complete the task form and submit. You will land back on the task page.
4. Navigate to any other page. You will see the note. 

**Expected behavior**
Should navigate to another page without getting such note. 

**Screenshots**
![Screen Shot 2019-10-22 at 6 14 55 PM](https://user-images.githubusercontent.com/5404004/67565747-e1867400-f745-11e9-9976-c00c3ce44c90.png)

**Environment**
- Instance: 
- Browser: Chrome, normal mode. Did not try incognito mode. 
- Client platform: MacOS
- App: webapp
- Version: 3.7.0
- Configuration: reference app

**Comment by dianabarsan** [comment]
Seeing this in the console after submitting a task:

![image](https://user-images.githubusercontent.com/35681649/67755129-41c82f00-fa40-11e9-921f-fe2e63490b73.png)

I did not get the warning when trying to navigate away, because the _winning_ transition was an empty task detail page. If the other transition had won and I ended up on a task that prefills some field, I would have gotten the warning when navigating away.

**Comment by dianabarsan** [comment]
This is caused by the code not entirely clearing the "selectedTask" in redux, so every time the controller gets reloaded and this code runs: https://github.com/medic/cht-core/blob/master/webapp/src/js/controllers/tasks-content.js#L166 . This ends up loading the form, which can set `enketoStatus.edited = true` - which is the value we check for when showing the popup. 
The same bug also happens in mobile view, if you select a task, click on the header "X" and then try to select another task or try to navigate away. 
See attached video: https://photos.app.goo.gl/eFt4X6sD4BQ3SBL18

**Comment by ngaruko** [comment]
Thanks @dianabarsan for the comments and video clip
LGTM on the branch - no error in the console and no `confirm` modal

**Comment by dianabarsan** [comment]
Merged into `master` and backported to `3.7.x`
