### ISSUE TITLE
Purging for task and target documents

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6181]
**What feature do you want to improve?**
https://github.com/medic/cht-core/issues/5657 changed tasks from being in-memory objects to being database documents. Currently, task documents replicate to the user's device and will remain there forever. After time, some users may have thousands of task documents on the their device which will slow things down. Many of these documents have no functional purpose on the device and can be purged.

**Describe the improvement you'd like**
* A task document is safe to purge when it is [60](https://github.com/medic/cht-core/pull/6041/files#diff-8f90c28d3acf485f33868b2660a3d697R18) days past the task document's end date and the document is in a terminal state.
* A target document is safe to purge whenever the reporting period is over.

These rules for when task and target documents are safe to purge are hard-coded into the "rules engine" and are not partner-specific. Therefore, server-side purging can handle them for all partners instead of requiring partner-specific logic for purging these documents.

**Comment by dianabarsan** [comment]
I think we should revise the rule for "target" documents and keep them in for longer. 
In solving https://github.com/medic/cht-core/issues/4840 , I'm basing some code on actually having access of target documents from the previous reporting period. 

Maybe we should keep target documents for 6 (insert random number greater than 1) reporting periods?

**Comment by kennsippell** [comment]
DHIS2 workflows also require target older target documents. Any random number greater than 1 would work. #5661

**Comment by dianabarsan** [comment]
There have been discussions about adding additional functionality to the "Supervisor target aggregates" to display CHW targets for past reporting periods. 

Since no final decision was made as to where this feature is heading, I think we should either skip purging `target` documents altogether for now or keep them for a larger window, say 12 "reporting periods".

**Comment by MaxDiz** [comment]
Since in-memory document storage can cause significant performance issues, let's set a slightly wider window for targets. A quarters reporting periods should be sufficient until we gain user feedback. For longer term trends, a supervisor can call data from the DB, correct?

**Comment by dianabarsan** [comment]
If we purge a document, it won't be available for the offline user (supervisor) anymore. It will exist in the server's database, but the user's device would have deleted it locally. In order to download it again, the purge rule would have to change serverside AND the target document itself would need to be edited (to get a new rev and be bumped to the end of the changes feed). 

We're looking at 1 document per reporting period per supervised CHW, so 12 documents per year per CHW.

**Comment by MaxDiz** [comment]
ok, let's start with 6 reporting periods for offline users.  

I believe supervisors are online more frequently and would likely use more comprehensive dashboards to understand longer-term trends (open question). We can include in our follow-up questions.

**Comment by garethbowen** [comment]
Ready for AT in `6181-purge-tasks`

**Comment by dianabarsan** [comment]
For AT: 
Task documents should be purged when they are in a terminal state ('Cancelled', 'Completed', 'Failed') 60 days after their end date.
Target documents should be purged when they are older than 6 months.

**Comment by ngaruko** [comment]
LGTM @dianabarsan Ready to merge

**Comment by dianabarsan** [comment]
Merged.
