### ISSUE TITLE
Record telemetry events for tasks and targets v2

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6188]
**What feature do you want to improve?**
Deploying Tasks and Targets v2 https://github.com/medic/cht-core/issues/5657 to production, it would be very useful to inform future iterations by measuring exactly how the system is performing in the wild.

**Describe the improvement you'd like**
Add telemetry events:

1. How long it takes to load tasks tab
1. How long it takes to load targets tab
1. How many contacts are "dirty" when tasks/targets refresh
1. How often the "freshness" thread runs in the background
1. How often the "freshness" thread is canceled and after how long

**Describe alternatives you've considered**
None

**Comment by dianabarsan** [comment]
Ready for AT on `6188-rules-engine-telemetry`.

**Comment by SCdF** [comment]
Assigning myself to AT

**Comment by SCdF** [comment]
@dianabarsan are you able to also create documentation changes here: https://github.com/medic/medic-docs/blob/master/user/telemetry.md This would be a requirement for merge. It would also help me AT: I'm not seeing a specific update for the targets page, but I'm not sure if that's intentional (I think it's being recorded as `tasks:refresh`) but hasn't been reflected in the ticket description

**Comment by dianabarsan** [comment]
The "targets" loading should be recorded under `analytics:targets:load` . I'm using the controller name as the "tag" (the `tasks` controller is called `tasks`, but the `targets` controller is called `analytics-targets`).
I'll add the documentation for all events.

**Comment by dianabarsan** [comment]
Documentation PR. https://github.com/medic/medic-docs/pull/217

**Comment by SCdF** [comment]
Cool, creates telemetry events as documented.

**Comment by dianabarsan** [comment]
Merged.
