### ISSUE TITLE
Adding dynamic language translation in the app.

### ISSUE THREAD

**Issue by KiharaSimon** [medic/cht-core#6232]
**What feature do you want to improve?**
Adding a scroll label that a user can choose a language of his/her choice.

**Describe the improvement you'd like**
Just a lang dynamic lang translator API

**Describe alternatives you've considered**
 Internalization and Localization of an angular app

**Additional context**
The app will improve the user interaction with workflows and the app itself.

**Comment by SCdF** [comment]
Hi @KiharaSimon, thanks for your suggestion.

Can you expand a little more here?

User's can select a language from a list of supported languages in their profile (hamburger menu -> User Settings -> Edit User Profile, then select the language you want in the dropdown).

**Comment by KiharaSimon** [comment]
Client side UI multiple language interactions. Example a CHW in Kenya can
have the workflows in Swahili.
Thanks

**Comment by SCdF** [comment]
@KiharaSimon if I understand your request this should already be possible, as long as the forms used have swahili translations

**Comment by KiharaSimon** [comment]
What about an translation  API

**Comment by SCdF** [comment]
If you're talking about using an external, automated translation api this unfortunately has two very large concerns:
 - As our application gives out medical advice we would have to have a very high confidence that it would never mistranslate medical terms to give incorrect or incoherent advice. I am unsure as to how we could gain this level of confidence without proof-reading the automation to the point where we'd be spending a similar amount of effort to baking them in like we are now
 - It would only work if you were online, and we've found that CHWs use the app offline most of the time, either because they are working in locations without internet access, or because it saves battery life

Just to re-iterate: if a language is supported by a deployment of CHT users can pick that language in their settings. In terms of the core UI, we support a few languages out of the box, but the UI can be translated into any language you'd like, and those language packs uploaded to your instance via medic-conf. Also, when authoring forms you can supply as many translations as you'd like as well

**Comment by n-orlowski** [comment]
As per convo with Stefan, not enough info to get started, will reopen if this becomes relevant in the future
