### ISSUE TITLE
API error for weak password is not prescriptive

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6256]
**Describe the bug**
Creating a new user via API with a simple password yields an error which is not prescriptive.

**To Reproduce**

1. `medic-conf create-users upload-docs` for a new user with a weak password

Expected: Prescriptive error describing the problem clearly
Observed: `The password is too easy to guess. Include a range of types of characters to increase the score.`

What is required? Upper case? Lowercase? What are the _actual_ requirements ... 

**Expected behavior**

**Logs**
```
ERROR StatusCodeError: 400 - {"code":400,"error":{"message":"The password is too easy to guess. Include a range of types of characters to increase the score.","translationKey":"password.weak"}}
```

**Environment**
- Instance: openhie.dev.medicmobile.org
- App: api
- Version: master

**Comment by kennsippell** [comment]
The error through Admin Console is much more clear. Perhaps we can use this `The password is too easy to guess. Include at least 1 uppercase letter, 1 number, and 1 special character.`

However `_`  underscore doesn't work as a special character?? Why.

**Comment by garethbowen** [comment]
The password requirements are clear cut like and we intentionally do not suggest what people should do to improve security because it's bad practice. If you say "include at least one number" then people just append "1" to the existing password and it's still easy to hack.

There are no requirements for special characters, uppercase letters, or numbers, but they all contribute to complexity along with length and character uniqueness.

The message is prescriptive and clear as is.

**Comment by kennsippell** [comment]
Didn't realize... so should we clarify this message in the admin console then? `The password is too easy to guess. Include at least 1 uppercase letter, 1 number, and 1 special character.`
