### ISSUE TITLE
Use http2 to fetch all login resources at the same time

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6276]
**Describe the performance issue**
The login page takes a long time to complete loading on slow networks in part because we load resources incrementally. First we load the `login.html`, then the `script.js`, then the `service-worker.js`, and finally all the app resources listed in the service worker. This means we wait for network lag a total of four times.

**Describe the improvement you'd like**
Provide a `Link` header with the `login.html` to instruct the browser to fetch all the other resources. This reduces the wait from four to two server round trips.

**Describe alternatives you've considered**
It would be better to send all resources with the `login.html` so we only have one round trip, but that would require SSL to terminate in API which is harder for SRE to manage than using the load balancer as we currently do.

We could inline our resources into the html but that breaks caching and makes the html a single very large request.

**To Reproduce**
Steps to record the performance metrics:
1. Go to the login page. The instance must be hosted on AWS to get http2 enabled.
2. Clear your cache completely
3. Open the network tab
4. CTRL+F5 to refresh completely
5. View when the requests are fired and measure the time to completion

**Measurements**
Currently you can see four distinct bands where requests are initiated. To see the result more clearly you can throttle your connection.

![Screenshot from 2020-03-07 15-14-04](https://user-images.githubusercontent.com/2064938/76140829-5370b180-6086-11ea-92ad-6afbb24967ff.png)

**Environment**
- Instance: any AWS hosted instance
- Browser: Any
- Client platform: Any
- App: API & webapp
- Version: 3.8.0

**Additional context**
This only affects the first load but it makes a really bad initial impression.

**Comment by garethbowen** [comment]
My investigation so far shows that this will achieve the desired effect:

```js
res.setHeader('Link', '</login/xyz.js>; rel=preload; as=script');
```

We need to find a nice way to include all service worker defined files. I think the simplest is to duplicate the array in the generated service-worker.js but we'll also need a check/unit test to ensure the two are kept in sync. Alternatively when generating the service-worker.js also generate a JSON file in api/src which can be required at runtime.

**Comment by latin-panda** [comment]
Hi @garethbowen,

This is the branch with the progress so far: [code](https://github.com/medic/cht-core/blob/311db2373df7ee683bd9425714eb743deb146b00/api/src/controllers/login.js#L230) 
Looks like we don't need to enable crossorigin in style.css and script.js resources.

But we do need leave the HTML tags, otherwise the browser will throw a warning saying that those 2 resources weren't used a few seconds from the window's load event. This article provides good information: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content) and also in [Stack Overflow](https://stackoverflow.com/questions/51613520/http-2-preloaded-css-is-not-applied-and-considered-unused)

<img width="1215" alt="Screen Shot 2020-06-22 at 7 11 17 pm" src="https://user-images.githubusercontent.com/66472237/85281179-b0269980-b4c8-11ea-8607-3d74017733ff.png">

I took a look at the service-workers and found out that login's script calls only [one service worker](https://github.com/medic/cht-core/blob/311db2373df7ee683bd9425714eb743deb146b00/api/src/public/login/script.js#L166)

I tried to add it as the previous resources but the browser complains:

<img width="539" alt="Screen Shot 2020-06-22 at 8 20 48 pm" src="https://user-images.githubusercontent.com/66472237/85280796-00512c00-b4c8-11ea-85a8-b772e70b3a7a.png">

<img width="1231" alt="Screen Shot 2020-06-22 at 8 21 51 pm" src="https://user-images.githubusercontent.com/66472237/85280810-0515e000-b4c8-11ea-83af-96be5c968fa6.png">

Then after some research I found out that Chrome has a [API very nice](https://developers.google.com/web/updates/2017/02/navigation-preload), but sadly this is for modern versions of Chrome 62+ and not available for Firefox as per the [MDN site](https://developer.mozilla.org/en-US/docs/Web/API/NavigationPreloadManager).
Summarising, we can enable the preload feature in the _"activate"_ event and then access it in the _"fetch"_ event by using the navigationPreload feature.

We still need to test this in a proper server with http/2 enabled to be able to see the actual speed 🙂 but local doesn't complain.

**Comment by garethbowen** [comment]
I don't think we need to include the service-worker itself but it'd be good to preload all the files listed in the generated service-worker. There are a couple of dozen of those in addition to the style and script you've got.

**Comment by latin-panda** [comment]
Logging findings and experience so far:

I tried to load the service-worker as **worker**:
`</service-worker.js>; rel=preload; as=worker`
But it's not supported yet:
<img width="1215" alt="Screen Shot 2020-06-23 at 6 23 42 pm" src="https://user-images.githubusercontent.com/66472237/85497668-7c10bd00-b61d-11ea-9bda-e36d2a3db3f2.png">

Then I tried to load it as `rel=prefetch` but this violates Content Security Policies of the browser, which I tried to fix by adding meta tag but looks like the **prefetch-src** or **worker-src** aren't fully supported or recognised. If I set the **default-src 'self'**, then the inline styles and scripts won't work and will need to provide the **unsafe-inline** setting.  I'm concerned of dropping the browser security in terms of XSS, I need to research more about the security concerns of prefetching resources, more info [here](https://developers.google.com/web/fundamentals/security/csp).

<img width="1119" alt="Screen Shot 2020-06-23 at 8 36 19 pm" src="https://user-images.githubusercontent.com/66472237/85497793-b24e3c80-b61d-11ea-8caf-3534e8624252.png">

We might need to log a question in Stack Overflow to see if someone in the community has advices on how to preload the service workers like ours. 

Currently our service worker is requesting resources programmatically, I'm able to preload the resources in Chrome, but since the service worker tries to access them after some time then the browser throws these warnings:

<img width="1669" alt="Screen Shot 2020-06-24 at 10 43 22 am" src="https://user-images.githubusercontent.com/66472237/85498609-348b3080-b61f-11ea-9209-07a9067200ca.png">

Finally, I tried to prefetch these resources which Chrome complains again about the violation of Content Security Policies, while Firefox doesn't throw errors or warnings but block them completely:

<img width="1675" alt="Screen Shot 2020-06-24 at 12 11 34 pm" src="https://user-images.githubusercontent.com/66472237/85498834-99df2180-b61f-11ea-894a-80cda823fa97.png">

Next, I'm going to try to [preload by creating HTML tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Scripting_and_preloads), the service-worker's resources.

**Comment by latin-panda** [comment]
Final thoughts:

I was trying to preload the resources which the service worker loads in the worker route, and noticed that even if I try to invalidate the preload intentionally (to debug), the browser isn’t giving any error or warning, perhaps because it's background process ( 🤔 ? )

<img width="573" alt="Screen Shot 2020-06-26 at 8 03 01 am" src="https://user-images.githubusercontent.com/66472237/85802385-007d5000-b784-11ea-9851-877d95038295.png">

Learned that this service worker is autogenerated by using sw-precache, which is obsolete and now it’s called Workbox… The Creator doesn’t motivate the usage of preload if we are already using precache: https://github.com/GoogleChromeLabs/sw-precache/issues/259

Learning about Workbox… it has a feature that already make the preload mechanism if the browser supports it, but they suggest not to use it if the app is App Shell design with cached HTML, since it won’t give much benefit : https://developers.google.com/web/tools/workbox/modules/workbox-navigation-preload

However, it could still have a little benefit in the first load on very slow connections while combining with HTTP/2, this needs to be tested. It was decided to log an issue to upgrade from sw-precache to Workbox and while on it, enable the Workbox's preload feature and test.

This issue's PR will submit the preload of login's CSS and JS only.

**Comment by garethbowen** [comment]
Ready for AT in `6276-login-resources-http2`

As well as testing that the login page still works ensure that the login.js and login.css are preloaded so the page renders quicker. Ensure you clear your browser cache completely between tests.

**Comment by ngaruko** [comment]
@garethbowen - You mentioned in the steps to reproduce that:
>The instance must be hosted on AWS to get http2 enabled.
Do we have a test AWS instance with http2 enabled or we need to contact SRE (@henokgetachew ) to set this up?

**Comment by garethbowen** [comment]
All our AWS instances should have http2 set up by default, so any hosted test instance should do.

**Comment by ngaruko** [comment]
LGTM
Tested on [gamma-cht](https://gamma-cht.dev.medicmobile.org) with the `6276-login-resources-http2` branch. Login page works as expected.  The `login/script.js` and `login/styles.css` files are preloaded ..
![image](https://user-images.githubusercontent.com/6979995/88626123-30f73780-d0fe-11ea-9bd6-9f65fa2d990c.png)

**Comment by garethbowen** [comment]
Merge commit: https://github.com/medic/cht-core/commit/95fac454969a2fd2854fb2f932c2cd05e219e6f3
