### ISSUE TITLE
Allow app builders to specify disabled languages in config

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6281]
**What feature do you want to improve?**
Whether or not a language is disabled is stored in generated docs in the database and can only be set via the app management console. This makes it less likely that app builders will define the list of languages that are actually supported and users are confronted with a long list of broken languages to choose from. Most apps probably support only one or two languages fully so this can be simplified significantly.

**Describe the improvement you'd like**
Instead of defining whether or not the language is enabled in the messages-* doc, it should be in the appsettings doc so it can be hardcoded in the projects configuration. Make sure to update the default configuration to only include fully supported languages to improve the out-of-the box experience. Also include a migration so as not to break existing projects that _have_ configured it correctly.

**Describe alternatives you've considered**
We could leave the enabled flag where it is and provide a medic-conf hook to disable languages but this is technically more complex.

Alternatively we could disable any language not explicitly provided for in the config but that is an unintended consequence of uploading new languages.

**Additional context**
This will make the language selector in #6280 much cleaner.

**Comment by m5r** [comment]
Is it a good time to get rid of the `locales` property in the default config's `app_settings.json`? There is no documentation about it in [our docs](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/), it's [not supported since version 2.7.1](https://github.com/medic/cht-core/pull/2441), but it's still present in every config I've checked so far, including the default config in cht-core and the config for one of [the most recent project](https://github.com/medic/config-moh-mali-chw/blob/master/app_settings/base_settings.json#L13-L22) that went live.


> Also include a migration so as not to break existing projects that *have* configured it correctly.

I'm thinking that the migration should look like this:
- get the translations docs
- save the translations' `code` to a `enabledTranslations` (better name pending) property in app settings
- remove the `enabled` property from each translation doc

Then it's going to be mostly code cleanup to make sure every code branch relying on `locale.doc.enabled` uses something like `settings.enabledTranslations.includes(locale.doc.code)`

**Comment by garethbowen** [comment]
> Is it a good time to get rid of the locales property in the default config's app_settings.json?

Definitely. Good spotting!

> save the translations' code to a enabledTranslations (better name pending) property in app settings

The downside of this approach is if the app developer then uploads the settings again it'll overwrite the `enabledTranslations` property. We might have to implement it in a backwards compatible way where you can either specify it in settings _or_ in the file as it is now, and then deprecate the old way and remove it in the next major.

**Comment by m5r** [comment]
Opened up the follow up issue medic/cht-core#8157

**Comment by garethbowen** [comment]
@m5r Is there a cht-docs update to communication how to do this? Maybe it needs something on this page: https://docs.communityhealthtoolkit.org/apps/reference/app-settings/

**Comment by m5r** [comment]
@garethbowen totally, this fell off my radar so thanks for bringing it up to my attention. I've opened the PR here: medic/cht-docs#1073
