### ISSUE TITLE
Add user telemetry for replication requests

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6354]
**What feature do you want to improve?**
We don't have a good idea of how often phones are trying and failing to sync data.

**Describe the improvement you'd like**
Every time a sync attempt is made we should record some user telemetry so we can monitor and improve. It could also be useful in setting more useful Service Level Objective based on the impact to the project of stale data rather than raw server uptime which doesn't impact offline users much.

Particularly it would be useful to know...
- How long the request took to complete.
- The status, eg: success, server offline, phone offline, other
- How long it's been since the last successful sync so we can work out how stale the data is

**Describe alternatives you've considered**
We could calculate this server side based on logs, but that would miss data points when the server or phone are offline.

**Comment by dianabarsan** [comment]
It's going to be difficult to get any useful information by just recording how long sync took. We can't add telemetry for a specific request (because PouchDB does everything in the background), only for the whole operation, and the duration can vary greatly depending on the number of docs that needed to be synced (either upwards or downwards), how many batches and general payload size. 

Were you thinking to have a finer granulated recording?

**Comment by garethbowen** [comment]
We could add finer grained metrics as well, but the main metric I was after was how long does it take actual users with real connections etc to complete a replication. It would be good to record how many changes were synced both ways to take that into account.

We can already see individual requests from each user by inspecting the logs if we need to dig down deeper. The advantage of the holistic metric is being able to record how long it takes to do a complete sync from the user's perspective.

**Comment by helizabetholsen** [comment]
Thanks for flagging this ticket for me @garethbowen. In follow-up to our conversation with @yembrick today, I wanted to add that I'd be interested in a number of metrics related to sync times - average # of times a CHW syncs per month, amount of time it takes per sync, and the % of CHWs who do not sync at all in a given month. 

More broadly, I wanted to flag a few additional telemetry-derived metrics that we are interested in exploring for inclusion in our impact monitoring across projects:

- # of CHT app logins (total, per CHW)
- # of tasks (total, per CHW), _ideally broken down by completed, cancelled, or still active_
- # of messages (total, per CHW)
- Average “boot time” for the CHT application
- Average time to search contacts across all CHWs per month
- Average time to search reports across all CHWs per month
- Average time to create and save a given report (i.e. home visit form, patient assessment form)

More to come on this soon but I wanted to give a sense of the metrics we are considering to explore what is possible in our product telemetry data.

**Comment by mrjones-plip** [comment]
@helizabetholsen  - As we're warming up the 3.12 release, did you have  any info in the "More to come on this soon" per you comment?  We can't promise we can deliver all the metrics, but we're happy to listen to requests!

**Comment by michaelkohn** [comment]
Please allocate any time spent on this to `Project | 214 Research` in Clicktime.

**Comment by latin-panda** [comment]
Hi @mrjones-plip, were we able to define exactly the metrics we need to add for the scope of this ticket? So, we can start designing the solution and know when work is achieved :) Thanks!

**Comment by helizabetholsen** [comment]
It would be worth asking @kennsippell if he has any specific metrics he'd like to capture here. From my perspective, the metrics linked above would be useful:

- number of times the CHT app is opened (total, per CHW)
- number of tasks (total, per CHW), ideally broken down by completed, cancelled, or still active [see Maria's analysis on tasks]
- number of messages (total, per CHW)
- Average “boot time” for the CHT application
- Average time to search contacts across all CHWs per month
- Average time to search reports across all CHWs per month
- Average time to create and save a given report (i.e. home visit form, patient assessment form)
- number of user feedback docs created, common errors -- @kennsippell 

There are additional metrics that @n-orlowski would like for us to capture for user monitoring and feedback, which include: 
*Session - “From the time the app opens to the time the app closes”
- Number of sessions
- Time between sessions
- Length of the session
- Timing of the session
- Page views for each session
- What the user was doing when the session ended

In addition, there is more context [here](https://docs.google.com/document/d/1c2UHfzaue4sNvQkiwRc93PBEdML9J9DlFNuQ23suk4k/edit#heading=h.q31g948sivit) for the type of metrics we'd like to engage in monitoring via telemetry.

**Comment by mrjones-plip** [comment]
@helizabetholsen  - [like in 6741](https://github.com/medic/cht-core/issues/6741#issuecomment-831587666), we're gonna keep this ticket narrowly scoped to just gathering telemetry around replication times per the top body of this ticket.

A lot items you mentioned overlap with #6300 - but that ticket isn't currently scheduled for 3.12 (and likely won't be added).

**Comment by mrjones-plip** [comment]
Oop! Linked to the wrong ticket in prior comment - fixed.  Sorry @helizabetholsen !

**Comment by dianabarsan** [comment]
I've worked on adding these new telemetry entries, and looking for some feedback. Thanks in advance! 

| key | value | recorded | 
| --- | ------- | -------- | 
| `replication:user-action`  | 1 | when the user clicks "Sync now" | 
| `replication:<database>:<direction>:success` | number representing how long in took to replicate, in ms | when replication is successful | 
| `replication:<database>:<direction>:failure` | number representing how long in took to replicate, in ms | when replication is failed | 
| `replication:<database>:<direction>:failure:reason:offline:client` | 1 | replication fails because of connection error and the app detects the client is offline | 
|  `replication:<database>:<direction>:failure:reason:offline:server` | 1 | replication fails because of connection error and the app detects the client is online | 
| `replication:<database>:<direction>:failure:reason:error` | 1 | replication fails because of other errors |
| `replication:<database>:<direction>:docs` | number of replicated docs | For one-directional, stores number of "read" docs, for sync, stores sum of read docs for every direction. | 
| `replication:medic:<direction>:ms-since-last-replicated-date` |  number in ms representing the difference between now and when the client last replicated successfully | only recorded for medic database, every time replication is attempted | 
| `replication:medic:<direction>:denied` | 1 | when replication is denied | 

Unless otherwise specified, <database> and <direction> placeholders stand for any combination of:
| database | direction | 
| --- | --- | 
| `medic` | `from` or `to`  | 
| `meta` | `sync` |

**Comment by kennsippell** [comment]
Potentially suggest renaming `user-action` to `user-initiated`?
Unsure on meaning of `denied` - does that mean insufficient permission?

I'd be interested to understand how long initial replications are taking specifically. We know they are very heavy and seem to be a vocal point-point for users (users reporting that it takes hours/days). We would expect many failures and retries for these scenarios. I'm not sure how we might capture that dimension -- maybe just one more counter `replication:initial` or alike?

**Comment by dianabarsan** [comment]
> `denied`
This is actually the name of the emitted event in PouchDB. 
When replicating `to`, it generally means users try to create docs that aren't allowed to - most likely because of hierarchy permissions. 
When replicating from (or generally). the `denied` can happen when the doc fails the `validate_doc_update` function - which is a core CouchDB functionality. 
Both of these cases kinda fall under "insufficient permissions" I guess, I have no problem in renaming the metric. 

Initial replication happens outside of angular (theoretically). We start initial replication on bootstrap (pre-angular) when we detect the user's database lacks two essential docs: the `medic-client` ddoc and the `settings` doc (both of which are required for the app to function). If these docs exist, we load the app. 
If the user needs initial replication, starts initial replication, downloads the ddoc and settings doc, then closes their app and starts the app again, bootstrap won't start initial replication and boot the app - replication will continue once the app boots but it still counts as "initial replication", but we don't actually do it in the bootstrap sitting.

**Comment by kennsippell** [comment]
`denied` seems appropriate given the definition

Sounds like initial replication is a tough one. Even if we add it outside Angular, sounds like our numbers will be whacky. Maybe let's skip that detail...

**Comment by dianabarsan** [comment]
This is ready for AT on `6354-telemetry-for-replication`

The new telemetry entries are detailed in the above comment (https://github.com/medic/cht-core/issues/6354#issuecomment-839975519) and also in this documentation PR: https://github.com/medic/cht-docs/pull/502

**Comment by ngaruko** [comment]
LGTM.
Leaving some details here for @helizabetholsen to confirm if that's the data and format requested.
**_Scenario 1_**:  ...> Successful automatic replication, ie not user initiated - 
a) Time taken to replicate, when replication was successful (`replication:<database>:<direction>:success`, both directions):
```
 "replication:medic:to:success": {
      "sum": 2029,
      "min": 2029,
      "max": 2029,
      "count": 1,
      "sumsqr": 4116841
    },
```
```
  "replication:medic:from:success": {
      "sum": 7403,
      "min": 7403,
      "max": 7403,
      "count": 1,
      "sumsqr": 54804409
    },
```
 b) Number of replicated docs (`replication:<database>:<direction>:docs`)  

```
  "replication:medic:from:success": {
      "sum": 7403,
      "min": 7403,
      "max": 7403,
      "count": 1,
      "sumsqr": 54804409
    },
```

and 
c) Time between a replication attempt and the last successful replication (`replication:medic:<direction>:ms-since-last-replicated-date`). 
```
 "replication:medic:from:ms-since-last-replicated-date": {
      "sum": 247451152,
      "min": 247451152,
      "max": 247451152,
      "count": 1,
      "sumsqr": 61232072626127100
    },
```

**Comment by dianabarsan** [comment]
@ngaruko  It depends on the error that comes back as a result of replication. 
Can you tell me what the error looked like? (you should see it as a feedback doc).

**Comment by ngaruko** [comment]
@dianabarsan There is no feedback doc for this particular case. 
![image](https://user-images.githubusercontent.com/6979995/119447414-f85ad580-bd83-11eb-8119-3416ae8277e2.png)

Basically I am referring to the [documentation](https://github.com/medic/cht-docs/pull/502/files#diff-4c4fda2d298052191547f4f0e7d5393d1cdaa13908d917490e358eef77d295e0R64) about the error message when the server is not reachable (either internet connection on the server side or server down).

**Comment by dianabarsan** [comment]
can you check the console log and see what the message looks like then? If there is no feedback doc?

**Comment by ngaruko** [comment]
For reference, when the phone is offline, the `failed to fetch message` then shows 

![image](https://user-images.githubusercontent.com/6979995/119458290-b1271180-bd90-11eb-95ba-8855c285b6c4.png)

**Comment by dianabarsan** [comment]
Thanks for the update, @ngaruko . This was very helpful. 

This message: `Unexpected token T in JSON` isn't necessarily denoting a connection error - this actually looks like ngnix or another load balancer responding with something that isn't JSON. But given our stack, I think this is specific enough so we always consider it a connection error. I'll make the update!

**Comment by ngaruko** [comment]
Oh wait, actually I am getting the `failed to fetch error` if I use the browser? Maybe my tunneling is the culprit here 
![image](https://user-images.githubusercontent.com/6979995/119462280-a8d0d580-bd94-11eb-85b3-54b001221cb8.png)
 and the error I was looking for is saved in the telemetry. 
```
  "replication:medic:to:failure:reason:offline:server": {
      "sum": 1,
      "min": 1,
      "max": 1,
      "count": 1,
      "sumsqr": 1
    },
```
Did you want me to try another way to connect to phone or it is ok to capture that `Unexpected token T in JSON` error as well?

**Comment by ngaruko** [comment]
I also observed that  in cases where the client/mobile time is ahead of server/normal time, the mobile app often prompts for a login/session expiry. Not sure if it has been always like this, but not definitely related to this PR (just noticed as I was playing a lot with times)?

**Comment by dianabarsan** [comment]
I think there's a high chance that our load-balancer (ngnix or AWS whatever) will return a 502 with some html when something goes wrong between it and API. So I think it's a good idea to capture this, along with the "Failed to fetch" in the `offline:server` group.

**Comment by dianabarsan** [comment]
>  the mobile app often prompts for a login/session expiry
yea, that's expected if your "expire" your cookies.

**Comment by ngaruko** [comment]
Looks good atm. The `replication:medic:from:failure:reason:offline:server` is recorded in telemetry when the `Unexpected token T in JSON` error happens.  Feel free to merge @dianabarsan

**Comment by dianabarsan** [comment]
Merged to `master`.
