### ISSUE TITLE
New contact header not translated in desktop view

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#6392]
**Describe the bug**
The header when creating a new contact is not translated in desktop view.

**To Reproduce**
1. Open the app in mobile view
1. Change language to French
1. Go to Contact tab
1. Select any place
1. Add a new person (ie "Nouvelle Personne")
1. See that the header is properly localized in mobile view (ie "Nouvelle Personne")
1. Change window size to desktop view and repeat 3-5
1. See that the title in the desktop view is _not_ localalized (ie "New Person")

**Expected behavior**
The header should be the localized version of the title, and the same in desktop mode as it is in mobile mode.

**Screenshots**
<img src="https://user-images.githubusercontent.com/789512/80892693-29a8c500-8c9a-11ea-92e7-0d199b723005.png" width=50%>

<img src="https://user-images.githubusercontent.com/789512/80892707-3a593b00-8c9a-11ea-99fe-2a14991a8d3a.png" width=80%>

<img src="https://user-images.githubusercontent.com/789512/80893032-d2f0ba80-8c9c-11ea-9508-16b7e85c4e4f.png" width=50%>

<img src="https://user-images.githubusercontent.com/789512/80892808-ed299900-8c9a-11ea-9bfd-5781780b0f8d.png" width=80%>

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Windows
- App: webapp
- Version: `6291-case-id` branch, but reported on 3.8.1 as well.

**Additional context**
This issue was just reported by a technical partner trying to figure out how to translate the Contact Form titles. The fact that it is localized in mobile view seems to indicate that the translation is configured correctly. All **New** and **Edit** contact forms experience the same problem, but the title header for App Forms show properly localized.

If a single non-English language is used for the deployment, a workaround is to put the localized text in the place of the English labels for the following:
- `contact.type.*.new`
- `contact.type.*.edit`

**Comment by garethbowen** [comment]
I think the problem is that the translation is performed in two different ways... 

The mobile version is set when the [page is rendered](https://github.com/medic/cht-core/blob/master/webapp/src/js/controllers/contacts-edit.js#L112) using the $translate service based on the translation key for that contact type.

The desktop title is [replaced after Enketo renders the form](https://github.com/medic/cht-core/blob/master/webapp/src/js/services/enketo.js#L292) using TranslateFrom which ignores the translation keys altogether.

Fix this bug by making both consistent so you only have to configure it in one place and it just works. One option would be to remove the title that Enketo renders and output our own that uses the redux state just like the mobile version does. Make sure whatever solution you pick uses translation keys not the deprecated object syntax to make it easier to configure and reuse translation values.

At the same time make sure the default config works out of the box in both resolutions.

One workaround is to also set the translations in the form doc in the database (ie: ID `form:contact:person:create`) to specify the title in the old style syntax, eg:

```json
 "title": {
  "en": "New Person",
  "fr": "Bonjour Marc"
},
```

Then sync to the client and refresh.

![Screenshot from 2020-05-04 09-53-23](https://user-images.githubusercontent.com/2064938/80926730-1f4b1000-8ded-11ea-8b5d-c4514524badc.png)

**Comment by m5r** [comment]
The code has changed quite a bit since this bug has been ***

Just for reference, here are the two ways a translation is performed in the current code base:
- [mobile version](https://github.com/medic/cht-core/blob/master/webapp/src/ts/modules/contacts/contacts-edit.component.ts#L222)
- [desktop version](https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/enketo.service.ts#L312)

Thanks @garethbowen for pointing out that the object syntax for translations was deprecated. Where can I read more about when and why it has been deprecated in favor of the other syntax?

**Comment by garethbowen** [comment]
> Where can I read more about when and why it has been deprecated in favor of the other syntax?

I don't think it's documented anywhere. The old syntax was to include an object mapping locale to translated string. The new way is to use a translation key which is then looked up in a translation file which contains every value for a language. The new way is preferred because it keeps all translations in one place which makes it easy to configure them, and you can reuse translations in multiple places through the configuration.

> I'm thinking of making the mobile view form use the same translation key as the desktop view to have consistent translations. At this stage, both mobile and desktop views would always show the english title. The only thing left would be to add translations for these titles. The downside of this solution is that we would have to add new translation for each form's title. Is this a realistic approach in your opinion?

We need to make sure we maintain backwards compatibility, so that app developers aren't required to make a configuration change while rolling this out. 99% of our users use a mobile interface, so it's most likely that the mobile view is being translated correctly already. Given that, the best solution would be to somehow modify the desktop view to use the same logic that the mobile view does.

One way I can think of to do this are to add an optional parameter to the Enketo service to take the translation key. Then modify where we set `$title.text(...)` to use the translation given, falling back to the code we have now.

Another way would be to let Enketo render as it does now but then immediately after find and swap out the title for the one set in the controller.

**Comment by meghna-khemka** [comment]
Tested above issue and it seems to be working fine

Changed language to French and Add a new person (ie "Nouvelle Personne") .Header is properly localized in mobile view (ie "Nouvelle Personne")
![image](https://user-images.githubusercontent.com/84743933/126827428-005046e3-43bc-4f67-b427-096b20a64091.png)

Change window size to desktop view .
Expected -The header is localized version of the title, and same in desktop mode as it is in mobile mode.

![image](https://user-images.githubusercontent.com/84743933/126827513-220a9459-fda1-474a-937c-9b273749dfff.png)
