### ISSUE TITLE
Possibility of using config locally without being oblige to use serveo?

### ISSUE THREAD

**Issue by Marina-Kenf** [medic/cht-core#6437]
**Describe the issue**
Trying to work on config on my local machine through docker.
I went through theses steps: https://github.com/medic/cht-core/blob/master/INSTALL.md.
Localhost available but unable to login due to service-worker error "`Loading error, please check your connection`" && "`Error bootstrapping DOMException: Failed to register a ServiceWorker for scope ('https://localhost/') with script ('https://localhost/service-worker.js'): An SSL certificate error occurred when fetching the script.`  
I'm working around it by using serveo
Serveo is unreliable, confusing, hard to setup.

**Describe the improvement you'd like**
Is there a way to do this without serveo? Can we explicitly make it so service worker is not required when origin is localhost?

**Comment by garethbowen** [comment]
You should be able to access http://localhost (NB: without the "s" on the "http") without serveo as long as you're just using it locally. Browsers have an exception to the https requirement for "localhost" access.

You need to use serveo or ngrok if you want to connect your phone to your computer because then you're using an IP not "localhost". We haven't yet come up with a solution to work around that requirement.

**Comment by garethbowen** [comment]
Probably a duplicate of #6168

**Comment by Marina-Kenf** [comment]
Thanks @garethbowen for you reply.
I can instead access https://localhost. 
- In chrome login to the config as admin is successful but generates the error mentioned above for a chw account. Only serveo is able to connect the chw.
- In Mozilla, I had the same issues but when I cleared the cookies, login worked for both admin and Chw profiles.

**Comment by Marina-Kenf** [comment]
Closing ticket and conversation moved to #6168.
