### ISSUE TITLE
Getting contact summary cards displayed that should not on a profile

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6485]
**Describe the bug**
Loading a contact summary for a child happened to load extra contact summary cards. There were 2 instances of the immunization and 1 of the past pregnancies card. This contact only has immune reports. I believe at one point I saw all the reports displaying under this contact but I cannot reproduce and no evidence otherwise. 

**To Reproduce**
1. Log in using a phone. I used nc_sup_offline on gamma.dev
2. Navigate to a profile.  I went to child part 2 profile
3. see the extra contact cards

**Expected behavior**
only contact cards that apply to the current contact should be displayed. 

**Screenshots**
Attached a video

**Environment**
- Instance: gamma.dev
- Browser: mobile app
- Client platform: andrioid
- App: webapp
- Version: 3.9 beta
[device-2020-06-11-115721.zip](https://github.com/medic/cht-core/files/4765921/device-2020-06-11-115721.zip)

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
Sounds like a race condition to me. 
I managed to replicate it as an admin user on `gamma.dev` by throttling the CPU by 6x and loading contacts aggressively (not allowing a contact to fully load before I navigated to the next).  

![image](https://user-images.githubusercontent.com/35681649/84417784-ce65dd00-ac1e-11ea-9bd4-5a26effa1114.png)

**Comment by jkuester** [comment]
This appears to have been "fixed" during the Angular uplift (probably by [these changes](3fb9da938f985f25ba5698930138d4eab26ac319)) as I am able to exactly recreate this issue on the [3.9.x branch](https://github.com/medic/cht-core/tree/3.9.x), but not on `master`.  On `master` this behavior presents a little differently and ultimately I think is "working as expected" (though perhaps not exactly how we would like it to work).  

To demonstrate the difference, I have performed the same basic test scenario, first on `3.9.x` and then on `master`. In my CHT data for both scenarios I had two patients. `Adriana` (who did not have any summary cards) and `Adelia` (who had a summary card for a past pregnancy).  

### 3.9.x

I added a 5s timeout to the [ContactSummary service call](https://github.com/medic/cht-core/blob/e6bcce41988afb8565723156e56b2ce2ce8d17be/webapp/src/js/services/contact-summary.js#L62) to slow it down. 

Then in the browser I did the following:
- Open the contact for `Adriana` and see that no summary cards are displayed
- Open the contact for `Adelia`
- Then quickly, before the summary loads, re-open `Adriana` and see that the past pregnancy summary card is incorrectly displayed

![3 9_broken](https://user-images.githubusercontent.com/8441903/122300615-2768f080-cec5-11eb-8e43-84e6844e7ec2.gif)

### master

I added a 5s timeout to the [ContactSummaryService call](https://github.com/medic/cht-core/blob/a6226376d75c7de942283a75ac8129cdf8c13165/webapp/src/ts/services/contact-summary.service.ts#L77)

Then in the browser I did the following:
- Open the contact for `Adriana` and see that no summary cards are displayed
- Open the contact for `Adelia`
- Then quickly, before the summary loads, re-open `Adriana` and see that the past pregnancy summary card (and the rest of `Adelia`'s summary information is briefly displayed until `Adriana`'s summary reloads. At that point, no summary cards are displayed.

![master_working](https://user-images.githubusercontent.com/8441903/122300920-9e9e8480-cec5-11eb-9e8c-72768b77d543.gif)

---

Based on this I am going to go ahead and push this issue into `Ready for AT`.

**Comment by meghna-khemka** [comment]
I am able to replicate above issue in Master .
Summary- I had 2 patient Andra (who did not have any summary cards) and Andra2 (who had summary card for  past 2 pregnancy).
Steps:Apply throttling. Click on Andra 2 and go back immediately before Summary card loads.
Click on Andra and examine past pregnancy summary cards are getting displayed.
When throttling is off, its working as expected.
I am also able to replicate above issue when throttling is on and when we click on Andra after Andra’s 2 summary card loads.
Supporting doc:Video attached


https://user-images.githubusercontent.com/84743933/122831616-fe6aa600-d29e-11eb-8f59-f93ca7b0033a.mov

**Comment by jkuester** [comment]
To follow up, I was able to re-create the issue with the steps from @meghna-khemka.  It seems that the issue I originally saw with delaying the loading of the contactSummary was resolved as noted above by the Angular uplift. However, the same invalid behavior can also be triggered in `master` (as Megna found) by just slowing down the loading of reports for specific contacts. (If I had to guess, I would say this is probably the issue that could actually be experienced by end users, so great catch Megna!)

Basically, when the ContactsEffects loads the data for a selected contact, it issues an async call to load reports. When that async call finishes, the reports are received into the `store` which then triggers the ContactsComponent to display the reports.  However, between the time that the ContactsEffects issues the async call to load the reports and the time that call actually finishes and returns the reports, the selectedContact can actually change (because the user navigates to a different contact).  ContactsEffects will issue a second call to load reports for the new contact. But, if that second call finishes before the first one, then whenever the first call actually finishes, it will overwrite the reports from the second call (the reports for the actual selected contact).  

As Megna pointed out, this behavior is exacerbated by a slow network connection.  If you select a place with multiple children (such as a Household) and then quickly select one of the people within the household, if your network connection is slow it is pretty easy for the reports to return for the selected person first, before the reports for the household (since the household tries to load all of the reports for its child contacts).  When that happens, all of the reports for everyone in the household will be displayed for the person.

**Comment by jkuester** [comment]
Okay, this should be ready for AT (for real this time) with the changes in the `6485-wrong-summary-cards` branch.

**Comment by meghna-khemka** [comment]
Tested above issue and now issue seems to be working fine.
Scenario 1: 'Andra 2' card doesn't get loaded

https://user-images.githubusercontent.com/84743933/123699637-5c097000-d814-11eb-9954-b022c41be661.mov

Scenario 2: 'Andra 2' card get loaded

https://user-images.githubusercontent.com/84743933/123699968-b86c8f80-d814-11eb-8e97-5ae81c3ca19b.mov
