### ISSUE TITLE
Schedules depending on `later` library might not run when expected

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6634]
**Describe the bug**
We use the [later](https://github.com/bunkat/later) library for scheduling purging. It has a "documented" glitch where it won't create a timer for the immediately next occurrence of a cron schedule, when this occurrence is less than one second away from the present, instead it will schedule the next occurrence. 

https://github.com/bunkat/later/blob/master/src/core/settimeout.js#L36
```
// minimum time to fire is one second, use next occurrence instead
if(diff < 1000) {
  diff = next[1] ? next[1].getTime() - now : 1000;
}
```

**To Reproduce**
This is very hard to reproduce, as it requires having sentinel schedule purging within a second of the schedule being created. 
However it has happened in production. 
What you would observe, if the bug is triggered, is that purge will just be skipped. Just like it would not be scheduled at all. 

**Expected behavior**
Purge should run on schedule.

**Logs**
Logs from the production instance where this happened:
```
Sep 04 04:00:00 medic-sentinel-logs | [2020-09-04 00:59:59] 2020-09-04 00:59:59 WARN: Reminder configuration invalid
Sep 04 04:00:00 medic-sentinel-logs | [2020-09-04 00:59:59] 2020-09-04 01:00:00 INFO: checking schedule again in 5 minutes 
```

The purge scheduler had run in between these two items. 
Purge should have been scheduled to run at `2020-09-04 01:00:00`, so within a second from the present. 

**Environment**
- Instance: production instance
- App: Sentinel
- Version: discovered on 3.9.1, but it's been an issue since forever

**Additional context**
I think the simplest solution is to change from using `later.setTimeout` to using the builtin `setTimeout`.

**Comment by mrjones-plip** [comment]
Unassigned for now given all the work I'm doing for CMoHM.  I'll pick up time permitting.

**Comment by garethbowen** [comment]
Delayed to 3.12.0 to speed up 3.11.0 release.

**Comment by mrsarm** [comment]
@dianabarsan looks like the "late" library is unmaintained and deprecated, and the author suggest in the Npm page to switch to its "drop-in" replacement:

> Please upgrade to the maintained and new drop-in replacement @breejs/later at https://github.com/breejs/later 🚀 Thanks and happy hacking! 🚀 @niftylettuce

Although taking a look to the source code, a similar code appears at [src/index.js#L1205](https://github.com/breejs/later/blob/e8d16f333abf52811c3c28bdc416722c86f24185/src/index.js#L1205):

```js
    let diff = next[0].getTime() - now;
            if (diff &lt; 1e3) {
              diff = next[1] ? next[1].getTime() - now : 1e3;
            <span class="pl-kos"></span>
```

I was thinking of replace the lib and create a regression test and see what happens, but because we need to fake the clock it may work no so well.

So, we can:
1. Replace `later` by `@breejs/later`
2. Use the built-in `setTimeout`, and find a library to parse the `cron` strings into a millisecond equivalent.

In both case I can try the creation of the regression test.

What do think?

**Comment by dianabarsan** [comment]
Can we still use `later` for parsing cron strings and extract the "timeout" delay value and just use it with `setTimeout` ?

**Comment by mrsarm** [comment]
I would prefer to upgrade because the library is deprecated and at some point its dependencies may trigger upgrade issues like security issues, so now that we need to do something about it, is the best time to change. The library pointed is a fork actually, so it should be backward compatible, and taking any of the approaches won't prevent us to have to test carefully that scheduling continue to works as before + the issue fixed.

**Comment by mrsarm** [comment]
About what you mention of using any of the libraries the old one or the new one to only parse the cron seems a good approach tough, if I take that approach, I can encapsulate it in a common module withing the project.

**Comment by mrsarm** [comment]
Ready for AT, branch `6634-sentinel-schedules-gaps-fix` , PR https://github.com/medic/cht-core/pull/7143 .

In the PR description is described a possible way to test the fix, but it is almost impossible, but at least we should test that the purging scheduling continue to work.

**Comment by niftylettuce** [comment]
You could also use Bree for scheduling purging, https://jobscheduler.net

**Comment by meghna-khemka** [comment]
Tested above issue by configuring Purging to run every 5 sec
Supporting doc:Video attached

https://user-images.githubusercontent.com/84743933/123172390-f3944a80-d431-11eb-8878-3db4ae5ad097.mov

<img width="976" alt="latest screenshot Purging" src="https://user-images.githubusercontent.com/84743933/123172452-06a71a80-d432-11eb-9e97-d7543e6be3b3.png">
