### ISSUE TITLE
Obscure username in telemetry data

### ISSUE THREAD

**Issue by ecsalomon** [medic/cht-core#6643]
**What feature do you want to improve?**
In telemetry data, the user name is given in plain text. This is often some version of the user's real name and therefor sensitive data.

**Describe the improvement you'd like**
Include a hashed or otherwise obscured version of the username (with some sort of lookup for admins and analysts who need access to the real user name). This would make telemetry data overall much more shareable and usable by the community without the need to remove PII.

**Describe alternatives you've considered**

**Additional context**

**Comment by garethbowen** [comment]
We treat telemetry data just the same as patient data so it's acceptable to contain PII. If we want to share it then it should be aggregated or have the PII removed before it gets shared just like we do with patient data. Additionally the name of the DB the data is stored in contains the username, so that would also need to be hashed. And then, in order to sync the data from the phone the phone would need access to the lookup table which would defeat the purpose.

I'd like this to be solved the same way we solve it for patient data, and I'm wondering if that should be somewhere between CouchDB and Postgres. What do you think?

**Comment by ecsalomon** [comment]
Thanks, Gareth. That makes sense.

I had imagined something for PII in postgres using roles to control access. We have legitimate business use cases for PII (e.g., entity deduplication, ), though we are pursuing few of them now. But what I had pictured in my mind was something like roles to access:

- Raw data / all PII
- Names
- Phone numbers
- Geolocation

This would mean a user would have to assume the `raw_data_access` role to read from any relations that have not separated PII from the rest of the fields or to read from _all_ PII tables. The `name_access` role would give access to relations with name data, etc. And then ERD something like:

![image](https://user-images.githubusercontent.com/7809989/93387325-a514a880-f82e-11ea-8c7e-149f4ea279a6.png)

But this is _not_ my area of expertise, so totally open to hearing this is a silly idea. :)

**Comment by garethbowen** [comment]
Sounds good to me. Would this be done in the data workflow management system?

I'm envisioning the telemetry data being synced to a new `raw.telemetry_json` (or something) table and get cleaned up for sharing in the same way assessments are in your diagram. Is that what you were thinking?

**Comment by ecsalomon** [comment]
Yes, am aiming for the broadest scope of workflow management I can push for, so I would include this in its scope.

Would very much like that solution for telemetry!

**Comment by ecsalomon** [comment]
@garethbowen should we close or rescope/rename the issue since the original request will not happen?

**Comment by garethbowen** [comment]
I'm in favour of closing this one out and dealing with it at the same time we deal with PII in patient data, if that works for you?

**Comment by ecsalomon** [comment]
Sounds good.
