### ISSUE TITLE
Improve how Muting is handled on device before syncs

### ISSUE THREAD

**Issue by senseibara** [medic/cht-core#6737]
**What feature do you want to improve?**
The [muting feature](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/transitions/#muting) as it works right now requires Sentinel Transitions to update the relevant contact docs following a muting form submitted by the CHW. Because of very slow/unstable connectivity in the field, we notice some weird situations that arise from it. The most frequent one is that the muting form don't get synced for days/weeks, in the mean time the household or place and its descendants remain active and users sometimes continue to submit forms. 
A part from the form submissions, from a UX perspective it is not ideal if the contact is not muted immediately, the users sometimes submit extra muting forms as they don't understand what's happening. Some of our UX features like UHC are affected as well. 

**Describe the improvement you'd like**
We would want ideally a muting feature that can work fully offline and that would be immediately effective after it was triggered. 
Another solution that would only prevent the form submissions after the muting, could be a improvement in configuration that would make it possible to check if the last form submitted for any of the parents of a contact or the contact itself is a muting form. we could add that check to the form properties to prevent it from being submitted in those cases ( this might be already possible and i'm just not aware of that ).

**Additional context**
We have noticed this issue for our partner MUSO, where CHWs continue to submit forms for a place/contact supposed to be muted, this make it confusing and difficult specially from a data analysis perspective, the reasons why those submissions are being done is unclear, is it a mistake ? Was the family not supposed to be muted in the first place ? Would the CHW had unmuted the family first before submitting the visit if the family was muted in time ? Are the chws submitting visits forms without actually visiting the family to not be penalized by the UHC scoring ? 

initial ticket : https://github.com/medic/config-muso/issues/44

**Comment by abbyad** [comment]
Replacing https://github.com/medic/cht-core/issues/6683 in [3.13](https://github.com/orgs/medic/projects/60#card-53279322) with this issue.

**Comment by dianabarsan** [comment]
Can someone indicate who to discuss the solution / workaround with (since Bara is no longer available)? 
Thanks!

**Comment by Marina-Kenf** [comment]
@dianabarsan I can help with this.

**Comment by michaelkohn** [comment]
And @eljhkrr

**Comment by dianabarsan** [comment]
Unsure of what is going on here? is this no longer ready for dev?

**Comment by michaelkohn** [comment]
Looks like @Fatoufall unassigned, i assume that was an accident?

**Comment by Fatoufall** [comment]
hey my bad...I wanted to add @maremegaye as PO of Muso

**Comment by dianabarsan** [comment]
This is ready for AT on `6737-validation-shared-lib`. (looking back, I picked a terrible name for this branch :) )

For a more technical explanation, please see: https://github.com/medic/cht-core/pull/7087#issue-631375395
Updated documentation here: https://github.com/medic/cht-docs/pull/504

There are no configuration changes that need to be made in order for client-side muting to work - having muting configured correctly in general is enough. You can opt out from running muting on the client by adding an "client: false" param to the config - check documentation for full details.
I tried to cover most situations that could come up and make up for late syncs, avoid generating conflicts. In the end, we still have two processes that execute an action at different times and in different circumstances, so the results of these actions might not always be the same. The documentation has a notes section that ennumerates some situations where we know that muting on the server will have different results than muting on the client:
- updated muting settings between client and server processing of the same report / contact
- editing the muting/unmuting reports before they are synced, but after the transition ran locally, that either change the target contact or change the validity of the report
- deleting muting/unmuting reports before they are synced
- validation rules that depend on database data (for example using the "exists" rule, which will run over different data sets, a report could be valid for the client but invalid for the server and the other way around).
- conflicts that overwrite `muting_history` for contacts
- delayed sync for some docs (either contacts or reports) could exacerbate the above because of the "replay" behavior (because replaying means that we run muting over some reports multiple times - if reports are edited significantly between replays, we could get different results).
- multiple clients muting/unmuting the same contacts at the same time will have no guaranteed results - conflicts are going to appear and choosing the winning rev is not deterministic.

Except for some edge cases, you should be able to:
- mute/unmute a contact on the client while having an internet connection (and Sentinel up and running) and not get conflicts on any of the docs (contact or reports) and get the same results as if muting would just run on the server. Same for unmuting.
- mute/unmute a contact on the client while not having an internet connection. Muting on the client only updates contacts (adding or removing the `muted` property) and does not silence/un-silence registrations. The silence part still only happens on the server. Also, in order to "cancel"/"re-enable" tasks, you configuration needs to handle muted contacts itself (just like before).
- perform multiple mute/unmute actions on the client, while not having an internet connection, and then reconnecting. After sentinel processes all the mutes/unmutes, your contacts should be in the same state as before syncing.
- forms that create and mute/unmute contacts at the same time should work (I have a couple of forms that I used for testing that I'm sharing here: https://gist.github.com/dianabarsan/1921504576f32cd9d369bba89572f573 - these forms are far from perfect or complete - and assume you configured these muting forms: https://github.com/medic/cht-core/tree/master/demo-forms/muting-forms).
- forms that create both mute and unmute reports are treated differently, and only _unmuting_ reports is processed when such a form is submitted (there's an example form in the gist).

Please be aware that
- muting on the client only works for offline users.
- it will only change contacts that are available on the client, with the "full" muting/unmuting running on the server.
- it adds some additional metadata to the contact docs (muting_history) which should be treated as read-only, it adds some additional metadata to the report docs (client_transitions) which should also be treated as read-only.
- the transition only runs on new docs - before they are saved in the database. So if you mute a contact, unmute a contact and then edit the first muting report, your contact should not become muted again.  (note: some of the forms in my gists above, when edited, will create new docs every time).

**Comment by abbyad** [comment]
This is an awesome improvement! We've been fixing other aspects where the structure/words used in config are difficult for an app developer, and wondering how the config language resonates with app developers. Does `client: false` resonate in an unambiguous way? To me it wasn't clear, where something more specific like `client-side: false` would seem clearer. There are possibly other reasons why the more general `client` make sense, but just thought I'd mention it before it gets cemented in :)

**Comment by ngaruko** [comment]
LGTM . Thanks @dianabarsan for sharing those forms.
* able to mute and unmute a contact on the client while offline  
* muting and unmuting client while connected does not cause conflicts
Pinging @Fatoufall and @Marina-Kenf in case they would like to give it test before release.
But ready to merge @dianabarsan .

**Comment by dianabarsan** [comment]
@abbyad I don't mind either "client" or "client-side". I used "client" throughout, in muting history structures, so that's why the config uses "client". 
It's an easy change to update the config to use "client-side", if you find that much clearer.

**Comment by abbyad** [comment]
Thanks @dianabarsan, for config perspective I think `client-side` would be clearer. Does that resonate with @kennsippell and @derickl too?

**Comment by craig-landry** [comment]
Hey @ngaruko, thanks for getting this tested. There are some really complicated scenarios for this one. Are there documented test cases somewhere that outline what conditions were tested? If not, would you please write up some basic bullet points here on the ticket for the cases that were covered?

**Comment by ngaruko** [comment]
**1.  Muting a contact with internet connection:** 
=> sentil logs the transition 
```
2021-06-03 03:07:03 DEBUG: calling transition.onMatch for doc 5a92d71a-b3ff-4d1e-abee-47efe8b463fe and transition muting seq 360-g1AAAAIjeJyV0DsOgkAQBuCNmGhjY2WnlZ2RwWWBSm5hqewrhOBuob3eRG-iN9Gb4D6oSEygmUn-zP8VUyOEpmXA0UxppbnIlS715VqbeFQgumyapiqDYns2wYRDwjMuusd_6nRlJt23wsYJkUipDHFfIbfCsRUWTkhASI6zvsLJCrdWmHuBccA07SmosZnobpZBHlaJncIEYZkMBylPr7yssnYKJjvCiBykvL3ysUroFBoxAYQOUr5ecX85OKWIAYBAt1P9AGzcqbM 
2021-06-03 03:07:03 DEBUG: finished transition muting doc 5a92d71a-b3ff-4d1e-abee-47efe8b463fe is changed seq 360-g1AAAAIjeJyV0DsOgkAQBuCNmGhjY2WnlZ2RwWWBSm5hqewrhOBuob3eRG-iN9Gb4D6oSEygmUn-zP8VUyOEpmXA0UxppbnIlS715VqbeFQgumyapiqDYns2wYRDwjMuusd_6nRlJt23wsYJkUipDHFfIbfCsRUWTkhASI6zvsLJCrdWmHuBccA07SmosZnobpZBHlaJncIEYZkMBylPr7yssnYKJjvCiBykvL3ysUroFBoxAYQOUr5ecX85OKWIAYBAt1P9AGzcqbM 
```
==> warning when attempting to submit a report 
![image](https://user-images.githubusercontent.com/6979995/120583017-8ec48080-c481-11eb-91ab-a7fc9e2294a7.png)
 ==> and in couchdb
```
"client_transitions": {
    "muting": true
  },
```
==> warning also displayed when the `client' is disconnected from the internet and the user attempts to submit a report
![image](https://user-images.githubusercontent.com/6979995/120583547-8c165b00-c482-11eb-8a57-25cf7ca5334b.png)

**2. Muting contact with no internet connection (created also while the client is offline)**
==> Muting works, submit report displays the prompt. However, contrary to the wording of the prompt, tasks are being created upon submission eve with a muted person - is this a something configurable @dianabarsan ?
==> Enable internet connection to sync docs created above:
* contact summary shows `muted' 
![image](https://user-images.githubusercontent.com/6979995/120585006-1790eb80-c485-11eb-8fd1-795e05a91128.png)
* `muting_history` is saved in the database
![image](https://user-images.githubusercontent.com/6979995/120585346-aaca2100-c485-11eb-9167-680099b928ab.png)

* 
**3. Unmuting contact** 
   * after they have been synced or muted while online: a) client online/offline => `muted` label removed, able to submit report without prompt and `muting_history` updated in the database:
![image](https://user-images.githubusercontent.com/6979995/120585928-b8cc7180-c486-11eb-8a9d-de2295c746bd.png)

**4. Internet off, create contact, mute...do stuff... then unmute and sync**
 ==> contact unmuted as expected and the `muting_history` saved to db 
```
 "muting_history": {
    "server": {
      "muted": false,
      "date": 1622693757072
    },
    "client": [
      {
        "muted": true,
        "date": "2021-06-03T04:14:54.548Z",
        "report_id": "aebc1000-c68c-44d9-bae2-859bcf917011"
      },
      {
        "muted": false,
        "date": "2021-06-03T04:15:12.372Z",
        "report_id": "38171441-02b8-4caa-8f8a-7f30f1a3d25d"
      }
    ],
```
5. **using forms that create and mute/unmute contacts at the same time** 
==> tried a few combination using @dianabarsan forms above. Works as described by forms
![image](https://user-images.githubusercontent.com/6979995/120587846-3cd42880-c48a-11eb-9df8-cdc571be49a2.png)
==> Gotcha: Please remember to add said forms to the `muting` field in `app_settings`
```
 "muting": {
    "muting": true,
    "mute_forms": [
      "mute_person",
      "mute_clinic",
      "mute_new_clinic" ,
      "mute_new_person" ,
      "mute_clinic_new_person",
      "mute_health_center_new_clinic",
      "mute_new_clinic_moew_persons",

    ],
    "unmute_forms": [
      "unmute_person",
      "unmute_clinic",
      "new_person_unmute_new_clinic" ,
      "new_person_unmute_new_peron" ,

      "unmute_clinic_new_person",
      "unmute_health_center_new_clinic",
      "unmute_new_clinic_moew_persons",
      "new_persons_unmute_person"

    ],
```

**Comment by dianabarsan** [comment]
>  Muting works, submit report displays the prompt. However, contrary to the wording of the prompt, tasks are being created upon submission eve with a muted person - is this a something configurable @dianabarsan ?

https://github.com/medic/cht-core/issues/6737#issuecomment-844976084

> Also, in order to "cancel"/"re-enable" tasks, you configuration needs to handle muted contacts itself (just like before).

**Comment by dianabarsan** [comment]
>  Please remember to add said forms to the muting field in app_settings

They shouldn't need to be added as muting/unmuting forms.

**Comment by craig-landry** [comment]
Sorry about the close/reopen. I clicked by accident! **This is still open**.

**Comment by ngaruko** [comment]
This can be merged @dianabarsan . I have pinged @Marina-Kenf to keep an eye on this after release to make sure we have covered most of use cases and scenarios.

**Comment by dianabarsan** [comment]
Thanks @ngaruko . @abbyad requested that I change everything that says "client" to "client_side" (just nomenclature), so that is still pending.

**Comment by abbyad** [comment]
Sorry for having delayed this... I had wanted to check that the naming made sense on the config side, but I don't think we got many more opinions on that.

**Comment by dianabarsan** [comment]
I already pushed the change to edit the name yesterday, globally, as per @abbyad 's request. 
It would be awesome if @ngaruko did a quick smoke test to see I haven't broken something.

**Comment by ngaruko** [comment]
All good @dianabarsan . Please go ahead and merge away.

**Comment by dianabarsan** [comment]
Merged to `master`.
