### ISSUE TITLE
Angular 10/11 support

### ISSUE THREAD

**Issue by ubresponsive** [medic/cht-core#6852]
Hi, keen to explore this further for our NGO, can I ask is there a plan to upgrade the AngularJS to Angular 10 or 11?

Secondly is there a plan to swap out grunt for webpack?

Thank you

**Comment by MaxDiz** [comment]
Hi @ubresponsive Angular upgrade is in progress now - see the [v3.11 release](https://github.com/orgs/medic/projects/35) for details.

@garethbowen may be able to provide info on grunt / webpack.

**Comment by mrsarm** [comment]
Here are more technical details about the Angular 10 migration, and the progress if you want to take a look: https://github.com/medic/angular10-migration

**Comment by garethbowen** [comment]
Hi @ubresponsive ! As mentioned we're nearing completion of the Angular 10 migration and will be releasing it soon. We expect this to be fully backwards compatible so feel free to explore the current release (3.10.x) for now. Upgrading to 3.11.0 should just work.

Swapping out grunt and sorting out the build pipeline has been delayed until we get Angular 10 done. If you have the time we'd love a PR, but otherwise, watch this space.

**Comment by garethbowen** [comment]
Closing this as I think the questions have been answered. If you have any more questions, feel free to post on the https://forum.communityhealthtoolkit.org/.
