### ISSUE TITLE
Ability to access "user permissions" from tasks, targets, and contact-summary

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6914]
**What feature do you want to improve?**
Contact-summaries

**Describe the improvement you'd like**
Task and target code written in cht-app configurations has access to the current logged in user object. This user object is not available in contact-summary scripts. This results in weird hacks like [this](https://github.com/medic/config-muso/blob/master/contact-summary-extras.js#L7) in which is_uhc_enabled is maintained on both the user document and the user's contact document. This means that to enable uhc for a user, we have to turn it on in two places which is a pain.

Knowing the properties of the user that is viewing the contact summary would be useful for situations like "is the current user a supervisor" or "does the current user have a role for which UHC is enabled?"

**Comment by dianabarsan** [comment]
> Task and target code written in cht-app configurations has access to the current logged in user object.
Is it not the user's contact object?

**Comment by dianabarsan** [comment]
https://github.com/medic/cht-core/blob/master/shared-libs/rules-engine/src/rules-emitter.js#L50

```
    flow = nools.compile(settings.rules, {
        name: 'medic',
        scope: {
          Utils: nootilsInstance,
          user: settings.contact,
        },
      });
```

So we call it `user`, but it's actually the contact doc.

**Comment by kennsippell** [comment]
Thanks @dianabarsan .... You're totally right. So `user` is tasks/targets is the same as `lineage[0]` in the contact-summary. 

Okay I guess we can close this? Or change it to be that both contact-summary and tasks/targets should benefit from having access to the `user` doc or at least the user's `role` information.   My goal is to toggle UHC 'on' for a set of users + enable a slightly different experience in the contact summary for those users. I want to maintain the user state in one place instead of multiple.

**Comment by dianabarsan** [comment]
I'm OK with passing the user object to configuration code (task, targets, contact-summary). 

What would you call the property we pass to nools and contains the user object here: 
```
flow = nools.compile(settings.rules, {
        name: 'medic',
        scope: {
          Utils: nootilsInstance,
          user: settings.contact,
        },
      });
```

**Comment by kennsippell** [comment]
:shrug:   Interfaces are hard. Especially when the current interface is overly generic, slightly misleading, and can't be changed...

maybe we "deprecate" `user` (keep as is but mark as deprecated for 4.0 removal) and create two new objects which are specific, disambiguated, and consistent across other language? `userContactDoc` `userDoc`

and just brainstorming:
maybe we augment the data that gets passed in already `user.doc`
maybe we come up with second name that is more specific `userDoc`, (`actualUser`, `userUser`, `user2` lol)
maybe we expose very specific data from the user doc (role, language, facility, contact are all that are in there) so eg `userRoles`? 

No great options.

**Comment by dianabarsan** [comment]
> maybe we come up with second name that is more specific

I'm thinking we could add two new properties: `userDoc`, which will contain the user-settings document, and `contactDoc` which will contain the contact doc, deprecate `user` and transition from using it gradually in favor of the two new properties. 
How's that?

**Comment by dianabarsan** [comment]
>  but it seems this info isn't available in the contact summary unless the user's facility's primary contact is also the user's contact - then it is lineage[0].contact (this is common, but not guaranteed)

contact-summary receives the contact via `contact`: 
https://github.com/medic/cht-core/blob/master/webapp/src/js/services/contact-summary.js#L66

**Comment by kennsippell** [comment]
>  add two new properties ..., deprecate user

:+1:

**Comment by latin-panda** [comment]
Putting this back for a bit, I'll resume work after other higher priority work is done.

**Comment by latin-panda** [comment]
Hi @kennsippell 
Are these new variables (userSettingsDoc, userContactDoc) more useful as "globals" in targets, tasks and contact-summary as they are available everywhere in the scripts?  <--- 2 lines change but then the app devs will need to mock these when doing unit test, etc.

The other way is to pass these in each function as parameter in targets & tasks, like resolvedIf, appliedIf <--- _the scope is more limited as these vars_ are only available inside functions, a lot more lines change (tasksEmiter, targetEmiter) but easier to test and to see where the variable is coming from. 

I thought on double checking because I remember our chat about globals. 
What aligns better to the need and use?

**Comment by kennsippell** [comment]
@latin-panda Probably globals.  More globals kinda suck, but I think injecting these into each function would clutter interfaces badly. Eventually we probably need a breaking change, but until then we maybe keep the message passing somewhat consistent.

**Comment by latin-panda** [comment]
This is ready for AT:
CHT-Core: https://github.com/medic/cht-core/pull/7126
CHT-Conf: https://github.com/medic/medic-conf/pull/409
CHT-Docs: https://github.com/medic/cht-docs/pull/518

A bit of context for QA:
Muso partner decided that all users are going to be UHC and the `is_uhc_enabled` [is going to disappear](https://github.com/medic/config-muso/issues/310). 
However in order to give flexibility when configuring CHT-Core, we have provided an API in the `cht` namespace with a couple of functions to check if the current user has the specified permissions, for example it can check for a custom permission or/and a system permission (`can_edit`) that is configured in app_settings.json. The API is available in targets, tasks and contact summary, for example a task can display if the user has specific permissions:
```js
{
  id: 'special-task',
  ...
  ...
  appliesIf: () => {
    ...
    ...
    return cht.v1.hasPermissions(['can_view_special_task', 'can_edit']);
  },
}
```


Please check the CHT-Docs PR for more details.

Also to provide this feature and avoid code duplication we had to refactor the authentication service in webapp and admin apps, specifically the `has(permissions)` and the `any(permissions)` functions, you might want to check that permissions related things are still okay (ie, show/hide tabs etc)

**Comment by meghna-khemka** [comment]
@latin-panda 
Tested above issue for Contact Summary.Issue seems to be working fine for 'haspermission' but there seems to be some issue with hasAnyPermission: eventhough user has role("can_edit") but result is displayed as False on UI.

Could you please look into this issue.

Case1: hasPermission
![image](https://user-images.githubusercontent.com/84743933/123556019-ecc14c80-d73d-11eb-9671-abcb9ed48df1.png)
Output
![image](https://user-images.githubusercontent.com/84743933/123556063-14181980-d73e-11eb-9a99-cd51c6df3287.png)

Case2:hasPermission
![image](https://user-images.githubusercontent.com/84743933/123556193-a91b1280-d73e-11eb-8168-5195b3fbc7bc.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123556221-ccde5880-d73e-11eb-8369-56b2a76afe71.png)

Case 3:hasAnyPermission- permission exist on user

![image](https://user-images.githubusercontent.com/84743933/123557514-08305580-d746-11eb-881c-a26dae6b630f.png)

Output:
![image](https://user-images.githubusercontent.com/84743933/123557531-3150e600-d746-11eb-8d03-70d3286704ae.png)

**Comment by latin-panda** [comment]
Thanks @meghna-khemka! Posting here a bit of the conversation in case someone needs it :) 

`hasAnyPermission` verify if the user has a group of Permissions from a list (Array with Arrays):

`hasAnyPermission( [ [ 'can_edit' , 'can_do_something_else' ], [ 'can_view_things' ] ] )`

In this example, the user should have `can_edit` and `can_do_something_else` or should have  'can_view_things’ in order to return true, ie it checks for the whole group and the user needs to have at least 1 complete permission group. 

The `cht` api is available when emitting the tasks and targets functions: applyIf, passIf, resolveIf. Same as the pre-existing `user` and `Utils` globals. However, contact summary is a bit different, webapp wraps the file content in a function and passes the globals, so globals are available anywhere in contact-summary file.

**Comment by meghna-khemka** [comment]
Case 3:Contact Summary - 
hasAnyPermission- permission do exist on user 
![image](https://user-images.githubusercontent.com/84743933/123664268-09b45900-d7ec-11eb-9bb5-fa14e44a4b61.png)
Output
![image](https://user-images.githubusercontent.com/84743933/123664189-fa351000-d7eb-11eb-90bb-9c580ac208be.png)

Case 4:Contact Summary - 
hasAnyPermission- permission not do exist on user 
![image](https://user-images.githubusercontent.com/84743933/123664356-20f34680-d7ec-11eb-8d9f-6fe0f7f2c30b.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123664518-41bb9c00-d7ec-11eb-975b-a27af3dad88d.png)

Case 5:Contact Summary - 
hasAnyPermission- mixed permission
Highlighted one is true
![image](https://user-images.githubusercontent.com/84743933/123664658-63b51e80-d7ec-11eb-99a6-e47eb51ea5f1.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123664810-8b0beb80-d7ec-11eb-8557-166552df4979.png)

Case 6:task-hasPermission
![image](https://user-images.githubusercontent.com/84743933/123666234-e12d5e80-d7ed-11eb-9df2-36fb1feff457.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123666391-0326e100-d7ee-11eb-9f10-1636900e531a.png)

Case 7:task-hasPermission- no permission
![image](https://user-images.githubusercontent.com/84743933/123665060-c9090f80-d7ec-11eb-9de2-d17357f5b7e9.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123665990-a6c3c180-d7ed-11eb-85b2-6491b771477b.png)

Case 8:hasAnyPermission- permission do exist on user 
![image](https://user-images.githubusercontent.com/84743933/123668226-c52abc80-d7ef-11eb-8bc0-43d240c2a675.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123668162-b512dd00-d7ef-11eb-9511-55b6ddb1c52e.png)


Case 9:hasAnyPermission- permission not do exist on user 
![image](https://user-images.githubusercontent.com/84743933/123667640-3027c380-d7ef-11eb-808a-d4ff6e8d1e34.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123667804-5b121780-d7ef-11eb-8143-77b70ae4be8c.png)


Case 10:hasAnyPermission- mixed permission-Highlighted is true
![image](https://user-images.githubusercontent.com/84743933/123667425-ff478e80-d7ee-11eb-8401-d5b8a6aa95d3.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123667329-e7700a80-d7ee-11eb-8247-0a9ac814c56d.png)

Case 11:target-hasPermission
![image](https://user-images.githubusercontent.com/84743933/123673948-e8f10100-d7f5-11eb-8fa9-8441789e15de.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123673895-d4146d80-d7f5-11eb-8c1e-e59e8f9a8233.png)

Case 12:target-hasPermission- No permission exist
![image](https://user-images.githubusercontent.com/84743933/123674062-0920c000-d7f6-11eb-88e4-70a3b41f21e0.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123674228-379e9b00-d7f6-11eb-881a-84bb8774d92a.png)


Case 13:hasAnyPermission- permission do exist on user 
![image](https://user-images.githubusercontent.com/84743933/123672154-dfff3000-d7f3-11eb-92f8-fd0548f01adf.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123672286-fc9b6800-d7f3-11eb-909a-a369721217d8.png)

Case 14:hasAnyPermission- permission not do exist on user 
![image](https://user-images.githubusercontent.com/84743933/123673329-2ef99500-d7f5-11eb-8548-6d6a449758ab.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123673259-1f7a4c00-d7f5-11eb-8af3-89b544bfd98c.png)


Case 15:hasAnyPermission- mixed permission(each array contain a role which don't exist)
![image](https://user-images.githubusercontent.com/84743933/123673057-e04bfb00-d7f4-11eb-8a1e-24e2e23c5d2d.png)

Output
![image](https://user-images.githubusercontent.com/84743933/123673098-ee018080-d7f4-11eb-80e5-70bbd33e45b6.png)

**Comment by kennsippell** [comment]
Should this api also be available to the `purge.js` partner code? Then it would be uniformly available across all JavaScript code. I think the same functionality can be implemented there, but a nice clean uniform interface across all code seems nice. This could be added as an improvement later if this feedback seems too late.

**Comment by latin-panda** [comment]
That's a good one Ken! I've done a quick assessment and made a [ticket](https://github.com/medic/cht-core/issues/7163) for this as we're closing 3.12.0. I've assigned it to myself.

**Comment by latin-panda** [comment]
PRs have been merged into main branch.
