### ISSUE TITLE
Select question with appearence "minimal" not picking all the languages set on the form

### ISSUE THREAD

**Issue by Marina-Kenf** [medic/cht-core#6964]
**Describe the bug**
When you create a select question with the appearance `minimal`, you have a pull-down menu that is picking only one language from the ones configure and never changes no matter the language of the user. 

**Expected behavior**
See the pull-down menu in the language set for the user.

**Screenshots**
This screenshot is how the question looks for a user in French, English, and Bambara. The list is picking Bambara and does not change.
![image](https://user-images.githubusercontent.com/63068738/108823218-0a2bb180-75b8-11eb-9124-cbe84ba4cd2d.png)

**Environment**
- Instance: upgrade-muso-mali.app.medicmobile.org/
- Browser: Chrome
- Client platform: Ubuntu 

**Additional context**
The workaround has been to have a normal select question with no appearance to have a check-list instead of a pull-down menu

**Comment by ngaruko** [comment]
Issue seems to still be there.
Tested on local with the custom [`repeat` form on the branch](https://github.com/medic/cht-core/blob/312d022939337fc6f82e79fa778185da8e0cb40b/demo-forms/repeat-translation.xml): 

1. Loaded form to app
2. Open the form and click on multiple radio buttons: 
![image](https://user-images.githubusercontent.com/6979995/132185693-e32985af-ec3a-4b8d-aa78-703e1b7e9b88.png)

3. Changed user language
4. Repeated 2
**on main branch** - blank page
![image](https://user-images.githubusercontent.com/6979995/132186215-679a38ec-2fb9-4663-8ce6-6c4a0602e439.png)


**on PR branch** - same 
![image](https://user-images.githubusercontent.com/6979995/132188179-c9adfa30-50b5-4f04-ba11-23db2fbf885d.png)

Am I missing something @m5r ?. Feel free to merge @m5r .

**Comment by m5r** [comment]
This is a normal behavior because the form only has English and Swahili translations. This is not something that happens in production, it only contains a minimal testing case to prevent potential regressions.

The fix focuses mainly on making any `select` with the attribute `appearance="minimal"` correctly use the user's language.  
For example, I changed the select appearance from `horizontal-compact` to `minimal` in `config/default/forms/contact/clinic-create.xml:1070` and here is how it looks like:

#### In English
![minimal select en](https://user-images.githubusercontent.com/13026820/135461569-2e92a9a1-404d-447d-a432-47cfb89676ca.png)

#### In French
![minimal select fr](https://user-images.githubusercontent.com/13026820/135461627-09af4800-fab5-4e2c-a4a6-300d41ffeb19.png)
