### ISSUE TITLE
Prototype integration with CloudWorks' Rapid Diagnostic Toolkit app

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#6981]
As part of our work with CloudWorks we need to build a prototype integration to the [Rapid Diagnostic Toolkit](https://github.com/dimagi/rd-toolkit) Android application.  

The workflow for the prototype will be an assessment form that provisions a test, and then a follow up task which would have a button to check for the status of the test. If the test is still pending, the user could wait in the form to press the button again until the return status is that the test is complete. 

<p></p>

This [integration](https://github.com/dimagi/rd-toolkit/blob/master/docs/usage.md) requires an Enketo widget to provision a test in the RDToolkit app, and another Enketo widget to collect the test result:

> Since tests take a significant amount of time to resolve, the default execution mode is a two phase interaction. The first phase is an activity callout to provision a diagnostic test, and the second phase is request to capture the result of the test.

The result widget would store the return value as a JSON blob for now, with the status being queryable from within the form itself. That way the field could be required, and preventing advancing in the form until a completed/success status is returned.

**Comment by abbyad** [comment]
Link to feature: https://community.productboard.com/feature-board/planning/features/7066130

**Comment by latin-panda** [comment]
**1st prototype links**

[1st prototype - implementation document](https://docs.google.com/document/d/1efEQnqHMZvC_I44_26GlVsQ3fnjdwcKhaTVw2wj6G6o/edit?usp=sharing)
[Test instance](https://testing.dev.medicmobile.org/)
[CHT Core branch](https://github.com/medic/cht-core/tree/6981-cloudworks-rdt)
[medic-android branch](https://github.com/medic/medic-android/tree/6981-cloudworks-2)

**Comment by latin-panda** [comment]
**Demo videos**

[Demo video # 1](https://drive.google.com/file/d/1lw19gMp3jx3V1RBHj2PvaoFmtwkGtN5L/view?usp=sharing): TLDR video with first version of implementation. Not commentary, just chill music.
[Demo video # 2](https://drive.google.com/file/d/1ntktnAChpFk7dAQkKSt5Vq4W3Ifv1ynf/view?usp=sharing): Longer video showing more scenarios with improved code. It has commentary

**Comment by latin-panda** [comment]
Status: 
    We are freezing development until the partner provides feedback about the demo.

**Comment by latin-panda** [comment]
Update: 
✅ Connect with Cloudworks API and reflect results in their dashboards 
✅ Support xls form
✅ Make it configurable from “outside” medic-android
🔄 Support image storage and display 
       -> Android 10+ doesn’t allow to access other apps’ images, shared resources needs to be stored in "share storage". The partner will fix the issue in their app and notify when their new release is done then we can continue the work in this feature.

**Comment by latin-panda** [comment]
Update:
The partner informed today that they are currently working on the fix for the Android 10+ issue. 
I've found another issue between RDToolkit and their Dashboard API where images are stored twice in the dashboard, maybe something to do with the app going to sleep and non blocking queue of requests. I've provided the steps, screenshots and other details.

**Comment by garethbowen** [comment]
I've moved this out of 3.11.0 and added it to the team workstream so it doesn't block the release.

**Comment by latin-panda** [comment]
**Update:**
The partner is working on fixing the issue related with the store of images for Android 10+. They're almost done, when it's ready, then we can do the integration work.
They resolved the issue with duplicate images in their dashboard, I verified it was working.

**Constrain:** 
Because RD Toolkit app uses libraries that supports sdk 21+ and our medic-android supports 19+, we can't build an apk XWalk. This is the error:

```
 uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.github.dimagi:rd-toolkit:0.9.0] as the library might be using APIs not available in 19
        Suggestion: use a compatible library with a minSdk of at most 19,
                or increase this project's minSdk version to at least 21,
```

**Comment by newtewt** [comment]
Will this integration retire our need for the existing MRDT app?

**Comment by abbyad** [comment]
This is being considered, but not a given. In the next two months we might be involved in exploring Rapid Diagnostic Test workflows, which will help answer that question more definitively.

**Comment by latin-panda** [comment]
**Update:** 
The issue related to retrieving images in Android 10+ is fixed and I've added the support in medic-android and CHT-Core.
We still have the constrain were xwalk build is failing because RD Toolkit app uses libraries that supports sdk 21+ and our medic-android supports 19+ but we can make a webview apk for Android5+ (sdk 21+) to not block the feature.

The documentation docs are updated and accessible [here](https://drive.google.com/drive/folders/1lqmn1QXlLTYfN_Tt1zF93_R6hDocdfvg?usp=sharing).

I've tested the feature in Android 11 and opened PRs for review :)

**Comment by latin-panda** [comment]
**Update:**

Forms & documentation are updated and accessible [in this shared folder](https://drive.google.com/drive/folders/1lqmn1QXlLTYfN_Tt1zF93_R6hDocdfvg?usp=sharing).

PR for cht-doc: https://github.com/medic/cht-docs/pull/510 (on review)
PR for cht-android: https://github.com/medic/medic-android/pull/175 (approved)
PR for cht-core: https://github.com/medic/cht-core/pull/7093 (approved)

**Comment by latin-panda** [comment]
Forms & documentation are updated and accessible in [this shared folder](https://drive.google.com/drive/folders/1lqmn1QXlLTYfN_Tt1zF93_R6hDocdfvg).

Custom implementation for RDToolkit is available in the following PRs, however we're going to try making a generic feature to launch any external app using XForms.
[cht-doc](https://github.com/medic/cht-docs/pull/510)
[cht-android](https://github.com/medic/cht-android/pull/175)
[cht-core](https://github.com/medic/cht-core/pull/7093)

Research about using ODK Collect for launching external apps is in [this document](https://docs.google.com/document/d/1XNLS4PUbT2hjDWxRXEMDK8h_LZAtl1n61rh8IlBk7GQ/edit?usp=sharing).

**Comment by latin-panda** [comment]
Initial scope of Medic's generic feature for launching external apps using XForms:

- [ ] (CHT-Android) Make a generic feature to launch external apps and pass simple data (text, numbers, booleans) to the app.
- [ ] (CHT-Android) Receive and process responses from the external apps that contains simple data (text, numbers, booleans) .
- [ ] (CHT-Android) Receive and process responses from the external apps  that contains complex data (Multi-level objects and images)
- [ ] (CHT-Core) Design and process XForm to trigger an event to get inputs and output fields with simple data (text, numbers, booleans) for the external app communication. 
Initially there's going to be 1 trigger method. 
- [ ] (CHT-Core) Receive responses from CHT-Android that contains simple data (text, numbers, booleans) from the external app and process it in a way that can be assigned to the XForm output fields.
- [ ] (CHT-Core) Handle CHT-Android responses with complex data (Multi-level objects and images) that needs to be assigned to XForm output fields.
- [ ] (CHT-Core) Handle multiple definitions of external app feature in the same XForm.
- [ ] Send solution of initial scope for revision and discussion. 
- [ ] Prepare comprehensive documentation.

**Comment by latin-panda** [comment]
The first half of this work, the launching android apps, is ready for AT, in the following PRs:
[CHT-Core](https://github.com/medic/cht-core/pull/7248)
[CHT-Android](https://github.com/medic/cht-android/pull/199)
[CHT-Docs](https://github.com/medic/cht-docs/pull/540)
@newtewt @meghna-khemka  we'd like to AT this part during this week because of the grant deadline. Can you please have a look and let me know if we need a walkthrough session? I've tested in Android 11 and 9, but it'd be nice to verify other versions as well. Thanks!

The second half, the covid19 configuration is in development and will be a separate branch and a separate PR, not affecting the feature to be AT this week.

**Comment by latin-panda** [comment]
Covid19 configuration:
- [ ] Create a directory in `cht-core/config`, it'll contain minimal configuration for making the covid-19 form work.
- [ ] App settings, icon resources files... 
- [ ] Add health facility, person forms (patient or CHW) and english translation file.
- [ ] Add covid-19 rdt form with lists of options
- [ ] Add Geolocation to covid-19 rdt form
- [ ] Add task (?) to fill out the capture of rdt result.
- [ ] Harness test coverage

**Comment by meghna-khemka** [comment]
@latin-panda :Picked for testing

**Comment by meghna-khemka** [comment]
Tested below scenarios:-
On Android 10
Scenario 1: Simple journey with 'provision report ->Task-> Capture report and task disappear'

https://user-images.githubusercontent.com/84743933/129777777-6e6318bb-1932-47ad-92fd-98a0fee9367f.mp4

Scenario 2:Expired test

https://user-images.githubusercontent.com/84743933/129781035-d17e01bd-a82a-4821-a9a7-968ec761e13d.mp4

Scenario 3 :
Question asked :
I am pondering over one edge-case: after we start the RDT test (via CHT task) and delete the CHT app, it seems the CHT task just sits there without allowing further any action on it. Is this expected or can we do something to clear/delete that lingering task in CHT?- Jenni is looking into this.

Scenario 4 :Launch button is not getting displayed on web.
![image](https://user-images.githubusercontent.com/84743933/129781737-29c65ed9-9323-4e88-8e89-6e9de90ee1ce.png)

**Comment by latin-panda** [comment]
Hi @meghna-khemka 
I think tasks that never get completed is a current situation in CHT, an option is to play with the rules in `applyIf` and `resolveIf` functions in the task to “disappear” a task after a while, maybe it’s more like a decision from the implementer of the instance because maybe they’d like to see how many are incomplete. 

I was wondering if you can test launching another app, maybe by using other intent properties from the widget configuration :)

**Comment by latin-panda** [comment]
A bit more of information about what happens if an Android app that the form tries to open doesn't exists: 

Depending of the intent's action, example action to send SMS, the Android will display a pop up requesting the user to choose another app that to complete the action. If no app is chosen or no app is available to take over, then we only get a RESULT_CANCELED code.

The thing is, we also get this when the app: 
1. explicitly returned this result,
2. didn't return any result 
3. crashed during the operation

So it's hard to know what is the real reason an act accordingly, however we do log an "Error occurred" kind of message.

I think assuring the right app is installed for those that uses the form should be part of the setup steps when enrolling users. Same as when having SMS app for SMS forms or [Simprints app](https://docs.communityhealthtoolkit.org/apps/reference/forms/app/#cht-xform-widgets) for registering patients with biometrics.

**Comment by meghna-khemka** [comment]
Thanks @latin-panda .
I have couple of more questions

Scenario 4: What should be preview_status of provision report once Capture task is triggered? It still displays as RUNNING, shouldn't it be updated to Completed?

Scenario 6: Image is not getting displayed .
![image](https://user-images.githubusercontent.com/84743933/129785599-085f45b1-ae55-4976-a06d-f117635e652f.png)

**Comment by latin-panda** [comment]
@meghna-khemka just to ensure we're in the same page, [we're still working ](https://github.com/medic/cht-core/issues/6981#issuecomment-899234529) on the configuration of the covid-19 (that uses RDToolkit app), so I'd recommend not to test RDToolkit functionality, those forms are just test and different from the what the FIND requested.

Better to cover the [feature of launching android app](https://github.com/medic/cht-docs/pull/540/files#diff-42e397b31a83def589115cb8e24a0f466e97079c0f2218f3c0914eb075db5e35R118) which is a independent generic feature and made available separately from the integration.

But to answer the questions the RDToolkit app doesn't have a "completed" state, the final state is "queued", but an app developer can change the display name when designing the form so it's more friendly for the end user.
About the image, I don't remember if RDToolkit app returns an image when the result is invalid, I haven't reach to that point in the configuration yet.

If the app returns an images (file path or bitmaps) then we convert it to Base64. 
To display Base64 images, you will need to use a new widget: [`display-base64-image`](https://github.com/medic/cht-docs/pull/540/files#diff-42e397b31a83def589115cb8e24a0f466e97079c0f2218f3c0914eb075db5e35R87)

**Comment by meghna-khemka** [comment]
Tested Integrating a different android application i.e. `Camera` app. After capturing the image from inside the camera app, the image is being returned to CHT report in form of BitMap. 


https://user-images.githubusercontent.com/84743933/129814792-8c2f183a-69dc-4398-be3d-1667de2bd0da.mp4

**Comment by latin-panda** [comment]
Thanks a lot @meghna-khemka!

**Comment by latin-panda** [comment]
Android app launcher PRs (cht-core, cht-android and cht-docs) and the config PR were approved, tested and merged. 
Closing ticket for release.

**Comment by ngaruko** [comment]
Android 1.0 

https://user-images.githubusercontent.com/6979995/168958367-9b66cb66-b37d-475e-a902-74b7a744468a.mov
