### ISSUE TITLE
Trying to open another report after selecting a verification state will not load the next report.

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6989]
**Describe the bug**
A user can mark a report as correct or has errors. After selecting one of those options and then trying to move to another report the app won't load that report. You have to select a different report and then return. 

**To Reproduce**
1. As an online user that has `can_verify_reports` role and at least 2 reports. 
1. Navigate to the reports tab. 
1. Select any report
1. Click the Review button and select either option.
1. Attempt to click a different report on the left hand side.
1. The url changes to have the new report id but the app doesn't load it. 

**Expected behavior**
The next report should display to the user.  Instead to work around you have to select a third report and then select the one you had in step 5

**Logs**
If applicable, include the server or browser logs.

**Screenshots**

**Environment**
- Instance: localhost
- Browser: chrome
- Client platform: windows
- App: webapp
- Version: master

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
I'm unable to replicate this. 
Is it possible you're not waiting until the "review" is complete before navigating to the new report?

**Comment by dianabarsan** [comment]
I was able to replicate this by: 
1. Throttling my connection and 
2. Clicking on the other report before the "review" action is complete.

**Comment by jkuester** [comment]
This issue seems to be caused by the [RxJs exhaustMap](https://rxjs.dev/api/operators/exhaustMap) function basically acting as expected, but in an unanticipated sequence of events.  

When the report is verified, it triggers the [verifyReport effect](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/effects/reports.effects.ts#L264) which eventually updates the selected report (to mark it as verified or not).  When the selectedReport is updated, that [triggers the change subscription](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/modules/reports/reports-content.component.ts#L88) in the reports content component to re-select that report.  This, in turn, triggers the [selectReport effect](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/effects/reports.effects.ts#L54). 

On the other hand, when navigating between different reports via the sidebar, clicking the buttons triggers the routerLink to open the new report which triggers the [route subscription](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/modules/reports/reports-content.component.ts#L96) in the reports content component which selects the newly routed report.

This issue occurred when a report is verified and then very quickly the user navigates to a different report. What happens is that before the first call to the selectReport effect (triggered by the verifyReport effect) finishes a second call to the selectReport effect is triggered by routing to the new report.  However, because of the [exhaustMap in the selectReport effect](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/effects/reports.effects.ts#L58), it seems that the second call to the selectReport effect is basically ignored (exhausted?) because the first has not finished yet. 

Unfortunately, I have been unable to recreate this behavior in a unit test so far (for unknown reasons, the `exhaustMap` functionality seems different when running the unit tests...?). However here is the evidence that I have been able to find so far that supports my above conclusion:
* If I add `delay(5000),` as an additional function in [this pipe](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/effects/reports.effects.ts#L63) and run the webapp, I can reliably recreate the issue in the browser without throttling any performance. (But I still don't see the second call being excluded in my unit tests for some reason...)
* Using the debugger/console.log I have confirmed that [filter](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/effects/reports.effects.ts#L57) gets called twice (once for each report), while the contents of the [exhaustMap function](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/effects/reports.effects.ts#L58) are only executed once (for the first report).

@dianabarsan does this sound plausible to you and do you think we need to look at using something besides `exhaustMap` here?  Or is there some other part of this flow that should be refactored?

**Comment by dianabarsan** [comment]
I think we just have the same case of what happened with contacts, report verification (being async) finishing and overwriting the state with the report it knows.
The reason the app is not reacting is because the actual route (the URL) matches the "newly" clicked report - at least that is what I'm seeing when I recreate this bug with throttling my connection and _whithout_ any code changes. 

If you really want to exclude `exhaustMap` as a probably cause, you can just replace it with a `tap` (mind that you'll need to change to the callback of tap so it doesn't rely on returning another observable, because it won't be subscribed to).

**Comment by jkuester** [comment]
Okay, after a bunch more investigation/debugging I think there are 2 interconnected race conditions here that are affecting things.  The first is just the "simple" condition alluded to above, where the report verification process updates pushes an update for the report to the database and that eventually triggers the [change subscription](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/modules/reports/reports-content.component.ts#L88) to re-select the verified report.  If, while the report is still being verified, the user navigates to a different report, it will trigger the [route subscription](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/modules/reports/reports-content.component.ts#L96) to select the new report. The race is whether the report verification will finish and re-select the verified report before the route subscription is triggered for the newly selected report.  

You would think that whichever one of those subscriptions is triggered _second_ would "win" and would ultimately be the selected report.  However **that is not necessarily the case**, and that is where the second race condition comes in.  

The second race condition happens when multiple [`selectReport` actions](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/effects/reports.effects.ts#L55) are emitted.  If the second selectReport action is emitted before the first one completes, it is [exhausted](https://github.com/medic/cht-core/blob/fd417e571c728b571a29381b6a4fd38a52b5921d/webapp/src/ts/effects/reports.effects.ts#L58) (and ignored).  This means that if there is enough time between the route subscription and change subscription being triggered, then the one triggered _second_ will "win" (and will be the selectedReport).  However, if the subscriptions are triggered close enough to each other that the first selectReport action does not have time to finish, then the second selectReport action will be ignored an the _first_ subscription called will "win" (and will be the selectedReport). 

This behavior is actually not isolated to the current case of selecting a different report while the original is still verifying. It is enough for the user to simply quickly between two report and trigger two calls to the route subscription.  This will cause the first selected report to be displayed, while the route URL parameter will actually be pointing to the second report.

To recreate:

- Throttle CPU/network
- Start with Report A selected
- Navigate to Report B
- Before Report B finishes loading, navigate back to Report A
- Report B will finish loading and be displayed, but the report ID in the URL parameter will be for Report A (and the user will be unable to navigate back to Report A)

https://user-images.githubusercontent.com/8441903/124318484-57a7c480-db3e-11eb-96dc-e90e947fad4c.mp4

**Comment by jkuester** [comment]
This is ready for AT on https://github.com/medic/cht-core/tree/6989-report-verify-race-cond

**Comment by meghna-khemka** [comment]
Hi @jkuester 
I tried testing this defect and issue still persist.
Please find supporting attachment


https://user-images.githubusercontent.com/84743933/128946126-65dca6c9-7608-40f6-95e9-08fb85e6c045.mov
