### ISSUE TITLE
Patients with `type: 'person', contact_type: 'other'` don't have tasks appear when viewed on the contacts tab

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6993]
**Describe the bug**
Contact documents with `type: 'person', contact_type: 'other'` don't have tasks appear when viewed on the contacts tab

**To Reproduce**

1. Deploy the production supervisor-moh-mali configuration https://github.com/medic/config-moh-mali/tree/master/supervisor-moh-mali using cht-core v3.10.2
2. Create a patient
3. Navigate to the patient in the contacts tab

OR

1. Deploy cht-core default configuration
2. Create a patient-level contact and edit the doc to have `type: 'person', contact_type: 'chw'`
4. View the contact in contacts tab

Expected -  You should see tasks for this contact. There should be no errors
Observed - No tasks. Error in console `Failed to load tasks for contact TypeError: Cannot read property 'person' of undefined`

**Logs**
`Failed to load tasks for contact TypeError: Cannot read property 'person' of undefined`
Crashing at https://github.com/medic/cht-core/blob/3.10.x/webapp/src/js/services/tasks-for-contact.js#L19

**Environment**
- Instance: https://supervisor-moh-mali.app.medicmobile.org/
- Browser: Chrome
- App: webapp
- Version: v3.10.2

**Additional context**
Works if you add the contact_type in app_settings.json, but has unknown consequences.

**Comment by dianabarsan** [comment]
Additionally: 

### 1. These contacts won't appear listed as children in their parent's contact detail page: 
(no console errors, the contact will just not be there).
![image](https://user-images.githubusercontent.com/35681649/110731642-5f5bfa00-822b-11eb-96a5-d672ff258fcb.png)


### 2. These contacts can't be edited. 
```
angular.js:15570 Error loading contact form. TypeError: Cannot read property '_id' of undefined
    at transformXml (enketo.js:100)
    at enketo.js:370
    at processQueue (angular.js:17948)
    at angular.js:17996
    at Scope.$digest (angular.js:19115)
    at Scope.$apply (angular.js:19503)
    at angular.js:21604
    at TaskTracker.completeTask (angular.js:21234)
    at angular.js:6814
```
### 3. When the contact opened, their icon doesn't appear: 
![image](https://user-images.githubusercontent.com/35681649/110731704-80bce600-822b-11eb-8dd3-150c41782dda.png)

### 4. These contacts don't show the correct contact-summary cards / fields.
 
The fields that should apply to their type don't appear (in this case, the Medic ID field, since this is using default config), this is something to be fixed in medic-conf. 

### 5. These contacts won't receive correct actions in the actions drop-up: 
![image](https://user-images.githubusercontent.com/35681649/110733978-96340f00-822f-11eb-9e8c-627fd5be9b57.png)

or 
![image](https://user-images.githubusercontent.com/35681649/110734272-240ffa00-8230-11eb-89d8-f4aeb6ea8e2f.png)
vs
![image](https://user-images.githubusercontent.com/35681649/110734309-3a1dba80-8230-11eb-9477-88c29e078e74.png)


### 6. Simply focusing the Select2 contact search triggers a cryptic error: 

![image](https://user-images.githubusercontent.com/35681649/110732903-b6fb6500-822d-11eb-8af6-1bdbe66ac543.png)

The actual error is: 
![image](https://user-images.githubusercontent.com/35681649/110733340-6a645980-822e-11eb-950c-45dc482e0899.png)

### 7. If UHC is enabled, visits won't be displayed for clinics that have a `contact_type`:
![image](https://user-images.githubusercontent.com/35681649/110733823-4f461980-822f-11eb-9306-4602ca3a9a14.png)

**Comment by dianabarsan** [comment]
Ready for AT on `310-consistent-contact-types`

**Comment by newtewt** [comment]
I've been working through this today. 

The issues reported in the moh-mali config are fixed. No errors in console and the people show correctly with the tasks also displayed on the parent. 

Downgraded to 3.4 and tested using the default config as well. Setting a contact_type manually on the person docs. Then upgrading to 3.10.2. Seeing the error and then applying the branch. The errors are resolved.  


Created custom contact_types with custom places and persons. 
Tasks - Is working for appliesTo on custom contact types. 
Targets - Is working for appliesTo on custom contact types. 
Contact summary. - Is working for appliesTo on custom contact types.

**Comment by dianabarsan** [comment]
Thanks for the update @newtewt . 

The issues from the my comment above (https://github.com/medic/cht-core/issues/6993#issuecomment-796432139) were just my observations once I started poking around and seeing what effects the code would have, but I'm not entirely certain I haven't missed anything.

**Comment by newtewt** [comment]
@dianabarsan  I think this one is ready to merge.

**Comment by dianabarsan** [comment]
Thanks @newtewt . I'll merge the 3.10 changes. The 3.11 changes are in code-review at the moment.

**Comment by dianabarsan** [comment]
Ready for AT for 3.11 on `6993-consistent-contact-types`

**Comment by newtewt** [comment]
I'm not seeing errors when the original contacts that have a random contact_type are added.  I can edit, search, view tasks, targets without issues. 

Along with the default contact types I went through the list of custom contact_types again as well. 
Created custom contact_types with custom places and persons.
Tasks - Is working for appliesTo on custom contact types.
Targets - Is working for appliesTo on custom contact types.
Contact summary. - Is working for appliesTo on custom contact types.

Feel free to merge the 3.11 portion @dianabarsan

**Comment by dianabarsan** [comment]
Merged to `master`
