### ISSUE TITLE
Update "Travis" cleanup script 

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7000]
**Describe the issue**
Our testing builds database cleanup script depends on Travis's build numbers being incremental per repo (????): 
https://github.com/medic/cht-core/blob/master/scripts/travis/cleanup.js#L6

However, once we switched to GitHub Actions, and use the `GITHUB_RUN_ID` in lieu of `TRAVIS_BUILD_NUMBER`. 
These ids are incremental, but certainly not per repo, and we can see huge leaps between one build number and another: 
![image](https://user-images.githubusercontent.com/35681649/110916424-741ab980-8321-11eb-890e-279e94a7e491.png)

This results in our testing builds database continuously growing, without being cleaned up. Currently we host **1093** testing builds instead of the desired number of 50. 

**Describe the improvement you'd like**
Adapt the cleanup algorithm to work with GitHub actions.

**Describe alternatives you've considered**
None.

**Comment by garethbowen** [comment]
I think the problem is that the script isn't being called at all. I ran it locally and got 50 builds returned, so the script kind of works, the problem is it will delete all builds up to 50 before this build, which could potentially remove all except this one. So it definitely needs to be updated, and then it needs to be called.

**Comment by garethbowen** [comment]
Done.
