### ISSUE TITLE
Error thrown when trying to send message to unknown sender

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7046]
**Describe the bug**
An error is thrown when trying to send a message to an unknown contact.
However the error is not visible to the user (all the user sees is that he presses "Send" and nothing happens). 

**To Reproduce**

0. Enable `update_clinics` transition. 
1. Create a new contact with a phone number. 
2. Send a message from this contact to the app (from admin app). 
3. Delete the contact.
4. In webapp, go to messages, click on the conversation from the deleted contact (the list should show a uuid). 
![image](https://user-images.githubusercontent.com/35681649/112994079-8d6d9380-9172-11eb-839a-2c69a57edca5.png)
5. Try to send a new message: 
![image](https://user-images.githubusercontent.com/35681649/112994177-a7a77180-9172-11eb-89ad-c56d6312fcd6.png)
6. Notice that clicking on "Send" does nothing, no message is added, no error is shown and the text in the checkbox is unchanged.
If you open the console, you'll see this error: 
![image](https://user-images.githubusercontent.com/35681649/112994348-d291c580-9172-11eb-8884-aa679540ee6e.png)

**Expected behavior**
We should either: 
1. Disable the "new message" area when we know we have nobody to send messages to. 
2. Display an error message in the UI, so the user knows something has gone wrong. 

**Environment**
- App: webapp
- Version: 3.11

**Comment by m5r** [comment]
Instead of disabling the "new message" area, we agreed it would be a better experience if we could allow the conversation to go on even if the contact doesn't exist anymore.

Currently, we're able to make this work but the experience doesn't feel "right":  
It allows having duplicate conversations (one with the contact and another one with the phone number). Also, sending a new message to the deleted contact adds it to the conversation with the phone number.

On a side note, I've noticed that having a conversation with a phone number and then creating a contact with this phone number doesn't link the conversation to the contact. Which makes it possible to have duplicate conversations as well. We could probably do something here as well but I haven't dug much.

Before spending too much time trying to make this scenario work better, I would like to get some design input.

Right now, the UI behaves like @dianabarsan explained in the bug report above and looks like this:  
![current state](https://user-images.githubusercontent.com/13026820/125912249-701cbf87-406c-4378-a8f0-b6e539b765f7.png)

If we would like to proceed with just hiding the "new message" area, here are some mockups of what we could achieve in a short amount of time:

#### Simply hide the new message area
![new message hidden](https://user-images.githubusercontent.com/13026820/125912334-0dddf5c9-010d-4d6a-95a6-f3d3fc9f0e7b.png)

#### Hide the new message area and explain why it's hidden
![new message hidden with explanation](https://user-images.githubusercontent.com/13026820/125912391-db121409-2bbd-4770-b4ac-dd9df786a382.png)

#### Display the new message area but disable it and explain why it's disabled
![new message area with explanation](https://user-images.githubusercontent.com/13026820/125912427-7b5d8285-0ccc-4fb2-83d2-a4034d1a448e.png)

Would any of these options be good enough for our use case or is this feature so important that we want it to work in this specific case?

cc @n-orlowski

**Comment by n-orlowski** [comment]
Hi @m5r! Not sure if this is the offline/online case where the contact exists but the user can't see it (@dianabarsan ?) but from the above mocks the second works best as it doesn't allow the user to try to take an action they can't (ex. send a message) and also tells them why 👍

**Comment by dianabarsan** [comment]
Offline users shouldn't be able to see messages from contacts they don't have access to. 
Buggy situations could exist where: the contact is purged but the messages aren't, but I don't think these are frequent enough to take into account separately. 

Thanks for asking @n-orlowski !

**Comment by ngaruko** [comment]
Tested on local  - LGTM
**_Before_** 
![image](https://user-images.githubusercontent.com/6979995/128965277-334b31fa-83c9-4ebc-aec6-edddf1bfac73.png)

_**after >> Message editor disabled + No error in the console**_ 
![image](https://user-images.githubusercontent.com/6979995/128965707-1de55e79-7875-4b9d-ab94-0ee06f9a4255.png)

**Comment by latin-panda** [comment]
@m5r just wondering if this is ready to merge as it's part of 3.13?

**Comment by m5r** [comment]
Hi @latin-panda, yes this has been AT'd a while ago and is definitely ready to merge  
I've just resolved a tiny conflict where an object property key had quotes when it shouldn't.  
I'm merging it as soon as the CI allows it
