### ISSUE TITLE
Remove the ability to set the user's language via the API

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7068]
**Describe the bug**
Continuing on from #6972 where we removed the ability to set the user's language in the admin app, we should also remove it from the API and accompanying [documentation](https://docs.communityhealthtoolkit.org/apps/reference/api/#supported-properties-2).

To maintain backwards compatibility make sure the endpoint continues to work when given a language.

**To Reproduce**
1. POST to `/api/v1/users` to set the user's language

**Expected behavior**
The database isn't updated. No errors are thrown. The language property is ignored, either silently or with a warning only.

**Logs**
None.

**Environment**
N/A

**Comment by jkuester** [comment]
@garethbowen to clarify, is the goal of this issue to remove the ability to set the language via the [users service](https://github.com/medic/cht-core/blob/master/api/src/services/users.js) completely (as hinted in your comments on https://github.com/medic/cht-core/pull/7049) or to just remove the ability to configure the user's language via the `/api/v1/users` endpoint (but still retain the functionality in the users service for setting the language since it is used to set the language based on the locale selected when logging in: https://github.com/medic/cht-core/blob/87aa90660ea7fcb41f46f7dcdef4bd1f21de6022/api/src/controllers/login.js#L165)?

**Comment by garethbowen** [comment]
@jkuester Great spotting. I think we can remove that call altogether. It sets the language in the database but that's never used anywhere!

**Comment by dianabarsan** [comment]
I'm echoing [this message](https://github.com/medic/cht-core/pull/7081#issuecomment-831878650) here, for clarity. 

If we remove the language update from user-settings, then we should add some other way of determining which languages the users are currently using. One option would be telemetry, but that would mean that data is relatively stale. 
Knowing which language the users are using is important for debugging and probably for data analysis as well.

**Comment by dianabarsan** [comment]
Added issue for storing users language in Telemetry and Feedback documents: https://github.com/medic/cht-core/issues/7089
These two issues should be scheduled together.

**Comment by dianabarsan** [comment]
This is ready for AT on `jkuester:master`.

**Comment by ngaruko** [comment]
Testing with local dev environment, using `jkuester:master`. Seems like I am able to set a user's language with `curl`. Am I missing something @jkuester ? 
![image](https://user-images.githubusercontent.com/6979995/123358772-2704df80-d5c0-11eb-9de0-ea8048c9032b.png)

**Comment by ngaruko** [comment]
Edit: After running the migration manually, then the user language was gone:
![image](https://user-images.githubusercontent.com/6979995/123363984-bd88cf00-d5c7-11eb-9b04-1a846cff0078.png)

**Comment by jkuester** [comment]
Well this is embarrassing. At the end of the code review, I rebased my branch on `medic/master`. It was a pretty straightforward rebase with a couple merge conflicts that I thought I handled correctly. Diana noticed, though, that some changes were missing from the Users service code and so I added that back in and then we figured everything was correct (especially since all the tests still passed).

After doing some more digging on this today, trying to figure out why you could still POST the language value, I remembered that I still had a pre-rebase copy of my branch on my personal computer.  That let me do a side-by-side comparison of the commits before/after the rebase and I found that somehow I had managed to loose a whole commit (which just happened to be the one with the user service changes and test).  I have pulled that commit back into the branch and verified that now I cannot POST the language to a user.  (I have also resolved to prefer merges over rebaseing in the future, especially since we do a squash-merge back into master anyway...)

**Comment by ngaruko** [comment]
Thanks @jkuester . Looks good atm, ie no language in `users` object. 
![image](https://user-images.githubusercontent.com/6979995/123733110-08b82000-d8ef-11eb-940c-55ad3aa58b7a.png)
I guess we are leaving this for backwards compatibility, but when one updates the user with `language`, there is no indication that it didn't update, both on the terminal and in api logs, it looks like it has succeeded, with a `200` response. Is that intentional @jkuester ?
```
2021-06-29 03:20:24 INFO: REQ 46e745da-75ef-4b52-a12e-93e675a63ade - Updated user 'zola'. Setting field(s) 'language'. Requested by 'admin'. 
RES 46e745da-75ef-4b52-a12e-93e675a63ade ::1 admin POST /api/v1/users/zola HTTP/1.1 200 172 686.286 ms
```

**Comment by jkuester** [comment]
That is correct @ngaruko, we still respond with a 200 if all they pass is `language` to retain backwards compatibility.

https://github.com/medic/cht-core/pull/7081#discussion_r625657425

**Comment by ngaruko** [comment]
Thanks @jkuester . Good to merge
