### ISSUE TITLE
Update logo in reference app "Medic Mobile" -> "Medic"

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7128]
**Describe the issue**
On our reference app we ship with [`medic-os`](https://hub.docker.com/r/medicmobile/medic-os) and in [`cht-core`](https://github.com/medic/cht-core/tree/master/config/default) has our old "Medic Mobile" logo in the header and login screen:

![old logo](https://user-images.githubusercontent.com/8253488/120849431-f4b91280-c52a-11eb-8ca3-343961f45aff.png)

![login](https://user-images.githubusercontent.com/8253488/120861724-9b59df00-c53c-11eb-929c-e2b5b6e7034e.png)

**Describe the improvement you'd like**
We should update the branding to use our new logo in both locations. In case it's handy, here's an SVG converted from [the EPS](https://drive.google.com/drive/folders/1WDPZI3h03oS8b2yyAQLbGXtHfG9zHRiQ) from google drive: [medic.logo.Jun.2021.zip](https://github.com/medic/cht-core/files/6601291/medic.logo.Jun.2021.zip)

**Describe alternatives you've considered**
Be happy with our out of date logo.

**Comment by mrjones-plip** [comment]
I believe this can be done via [the branding config](https://docs.communityhealthtoolkit.org/apps/reference/resources/)

**Comment by garethbowen** [comment]
I think the default icons are stored in [this folder in api](https://github.com/medic/cht-core/tree/master/api/src/resources)...

**Comment by nomulex** [comment]
Should it be medic or CHT?

**Comment by garethbowen** [comment]
Ideally it would be CHT branded but let's hold off until we have the updated brand. In the meantime it's reasonably quick to update the Medic branding for consistency.

**Comment by latin-panda** [comment]
This is ready for AT:

The work focuses mainly if user facing areas. 

Related changes in the [PR for CHT-Core](https://github.com/medic/cht-core/pull/7204):
- Updates the logo and its spacing in the login page.
- Updates the favicon.
- Updates page title to be `Medic`.
- Updates emails in REDME file: `dev@medicmobile.org` and `hello@medicmobile.org` to use `@medic.org`.
- Update `Medic Mobile` to `Medic` in translations and documentation.

Related changes in the [PR CHT-Android](https://github.com/medic/cht-android/pull/195):
(Please note that this one was merged, but still good to consider)
- Updates the app icon.
- Updating the app_name from `Medic Mobile` to `Medic`.

Things that remain the same:
- Colours won't be updated as they require an UX study 
- Legal related: copyrights and licences remains as `Medic Mobile, Inc`. Because this is still our legal name. 
- Android's package, application ID and flavors names remains the same to avoid problems in Playstore.
- Instances name inside the application code remains the same as instances haven't been updated in the server ([related ticket](https://github.com/medic/cht-android/issues/164#:~:text=to%20wait%20until-,this%20issue,-is%20done%20before))

(cc: @n-orlowski )

**Comment by ngaruko** [comment]
Testing on branch `
1 - did we miss the [copyright](https://github.com/medic/cht-core/blob/8ec32819471894971de63fdf3d916a04342c9a44/README.md#copyright) bit or?
2 - [same with api/license](https://github.com/medic/cht-core/pull/7204/files#diff-34a1166a4de57a80eabe143451b4ff52acac0762ec1c16fdb15d6e23956e34b5R1)

**Comment by latin-panda** [comment]
Hi @ngaruko the [legal related things](https://github.com/medic/cht-core/issues/7128#issuecomment-885370707): copyrights and licences remains as `Medic Mobile, Inc`. Because this is still our legal name.  :)

**Comment by ngaruko** [comment]
Thanks @latin-panda 
LGTM for the rest.

_**1. login page**_
![image](https://user-images.githubusercontent.com/6979995/128782697-0ee59314-a73b-41fe-b639-28b97c542bda.png)

**_2. logo_**

![image](https://user-images.githubusercontent.com/6979995/128782652-8cd65f65-3320-4f26-a7f9-b2a05514232a.png)

**_3. Flavicon and page title_** 
![image](https://user-images.githubusercontent.com/6979995/128782774-ac83835f-f919-4689-bcc2-e6c41f1b13de.png)

**Comment by ngaruko** [comment]
Unless @n-orlowski want to have a look for UX look and feel, ready to merge!

**Comment by n-orlowski** [comment]
LGTM, thanks!

**Comment by latin-panda** [comment]
Merged into main branch.
