### ISSUE TITLE
Feedback docs: "502: batch processing terminated with error"

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-core#7147]
**Describe the bug**
The feedback documents from `brac-ug.app` (3.9.2) collected for the month of April 2021 had this error reported 87 times from 75 different users:
```
Possibly unhandled rejection: {"message":"batch processing terminated with error","type":"basic","status":"502"...
```
**Logs**
<details><summary>The full error stack (with UUID and sequence removed) looks like this:</summary>

```json
Possibly unhandled rejection: {
    "message": "batch processing terminated with error",
    "type": "basic",
    "url": "https://brac-ug.app.medicmobile.org/medic/_<**uuid**>_/content?rev=<**rev-id**>",
    "status": 502,
    "ok": false,
    "statusText": "",
    "headers": {},
    "body": {},
    "bodyUsed": false,
    "result": {
        "ok": false,
        "start_time": "2021-04-28T08:57:25.109Z",
        "docs_read": 382,
        "docs_written": 382,
        "doc_write_failures": 0,
        "errors": [],
        "last_seq": "<**seq**>",
        "status": "aborting",
        "end_time": "2021-04-28T09:20:31.326Z"
    }
}
```
</details>

**Environment**
- Instance: brac-ug.app.medicmobile.org
- Version: 3.9.2

**Additional context**
This error is also being seen in feedback docs collected from Muso but we don't have the full data for Muso yet.

For BRAC, this error has been recorded every month since September 2020. Last May, the error was seen only one time, but this month (June), it has been recorded at least 7 times already.

**Comment by dianabarsan** [comment]
I've been curious about these errors for a while. We've had lots of them historically, having just 1 or 7 per month for such a large deployment is not bad. 

The 502 would implicate that our load-balancer (I believe this is the AWS Elastic Load Balancer) doesn't get a response from API. 
We could crosscheck the load-balancer access log (we don't expose that to logtrail, I think only SRE has access to it) with API access log and find out what happened for every 502. 
I'm suggesting the crosscheck because feedback docs are timestamped with client datetime, so unreliable.

**Comment by dianabarsan** [comment]
I was just running some tests on a prod clone and noticed that I got 502 when the request duration exceeded 2 minutes: 

![image](https://user-images.githubusercontent.com/35681649/124297586-e2e78100-db63-11eb-8a23-e8f068c01476.png)
![image](https://user-images.githubusercontent.com/35681649/124297597-e7139e80-db63-11eb-8a65-2fc4cb389295.png)

So this could be an infrastructure issue. We have had this problem in the past and it the load-balancer timeout was raised by a lot (to 2 hours or something, right @Hareet ?) .

**Comment by dianabarsan** [comment]
@binokaryg Following up on this

Is there a project that has the 502 patch (3.10.5 or 3.11.2 or 3.12+) that we can check for these feedback docs? We'd only be interested in feedback docs that have been generated after the upgrade to the patch that contains the fix.

**Comment by binokaryg** [comment]
These are the projects matching the versions above. I am trying to get the dates when these instances were upgraded from unpatched versions.
URL|Current version|Date of patch upgrade
-|-|-
https://brac-ug.app.medicmobile.org|3.10.5|
https://hth-togo.app.medicmobile.org|3.13.0|
https://muso-mali.app.medicmobile.org|3.14.2|
https://pih-malawi.app.medicmobile.org|3.14.2|
https://supervisor-moh-mali.app.medicmobile.org|3.15.0|
https://zazic-scale-up.app.medicmobile.org|3.16.0|

**Comment by dianabarsan** [comment]
Given the recent investigation into failed deployments due to 502, we've found that it's very likely that a bug in NodeJs 8 is causing terminating requests - and producing 502s - while the API service is healthy. 

Additional context: https://github.com/medic/config-muso/issues/1016

Our research showed that this is very likely resolved with 4.x. 

@binokaryg do you think further investigation is required here?

**Comment by dianabarsan** [comment]
Closing as stale. We haven't had reports of similar behavior happening in 4.x.
