### ISSUE TITLE
Feedback docs: "403: You are not allowed to access this db."

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-core#7151]
**Describe the bug**
In April and May 2021, feedback docs collected from 4 users in `brac-ug.app` have this error which occurred 5 times.

`Possibly unhandled rejection: {"error":"forbidden","reason":"You are not allowed to access this db.","status":403,"name":"forbidden","message":"You are not allowed to access this db.","docId":"...", ...`

**Logs**
Looking at the URLs reported, 2 are from specific contacts, and 3 are from the generic tasks page.

In the error stack, two different top-level arguments were reported:

1. `MaxListenersExceededWarning, Possible EventEmitter memory leak detected., destroyed, listeners added. Use emitter.setMaxListeners() to increase limit.` (_4 times_)
2. `Error updating _local/rulesStateStore: {"status":409,"name":"conflict","message":"Document update conflict"}` (_1 time_)

**Environment**
- Instance: brac-ug.app.medicmobile.org
- Version: 3.9.2

**Additional context**

This error generally appeared 1-3 times each month starting from Sep 2020, except it was not seen on Dec 2020 and Feb 2021.

**Comment by dianabarsan** [comment]
@binokaryg Can you please provide the whole contents of the error. untruncated? Thanks!

**Comment by binokaryg** [comment]
Sure @dianabarsan, here they are:
```
Possibly unhandled rejection: {"error":"forbidden","reason":"You are not allowed to access this db.","status":403,"name":"forbidden","message":"You are not allowed to access this db.","docId":"_local/8TrA6M0q6aZrn.VxTlraKg%3D%3D","result":{"ok":false,"start_time":"2021-04-28T07:22:06.715Z","docs_read":0,"docs_written":0,"doc_write_failures":0,"errors":[],"status":"aborting","end_time":"2021-04-28T07:22:07.939Z","last_seq":0}}
Possibly unhandled rejection: {"error":"forbidden","reason":"You are not allowed to access this db.","status":403,"name":"forbidden","message":"You are not allowed to access this db.","docId":"_local/50pad7gPyUXAxOqxSgMUzQ%3D%3D","result":{"ok":false,"start_time":"2021-04-28T12:13:43.500Z","docs_read":0,"docs_written":0,"doc_write_failures":0,"errors":[],"status":"aborting","end_time":"2021-04-28T12:13:44.047Z","last_seq":0}}
Possibly unhandled rejection: {"error":"forbidden","reason":"You are not allowed to access this db.","status":403,"name":"forbidden","message":"You are not allowed to access this db.","docId":"_local/Rz4zqHsSHcH.MqSUbHTjhA%3D%3D","result":{"ok":false,"start_time":"2021-04-16T03:56:01.825Z","docs_read":0,"docs_written":0,"doc_write_failures":0,"errors":[],"status":"aborting","end_time":"2021-04-16T03:56:02.822Z","last_seq":0}}
Possibly unhandled rejection: {"error":"forbidden","reason":"You are not allowed to access this db.","status":403,"name":"forbidden","message":"You are not allowed to access this db.","docId":"_local/h0Z7mEoMCafmtXqNNScv7g%3D%3D","result":{"ok":false,"start_time":"2021-05-20T08:44:32.380Z","docs_read":0,"docs_written":0,"doc_write_failures":0,"errors":[],"status":"aborting","end_time":"2021-05-20T08:44:34.260Z","last_seq":0}}
Possibly unhandled rejection: {"error":"forbidden","reason":"You are not allowed to access this db.","status":403,"name":"forbidden","message":"You are not allowed to access this db.","result":{"ok":false,"start_time":"2021-05-20T08:43:30.318Z","docs_read":0,"docs_written":0,"doc_write_failures":0,"errors":[],"status":"aborting","end_time":"2021-05-20T08:43:30.707Z","last_seq":0}}

```

**Comment by dianabarsan** [comment]
Interesting. Same user? 
These look like failures to sync meta databases.

**Comment by binokaryg** [comment]
These are from 4 users. 3 users from April, 1 from June. All restricted users.

**Comment by dianabarsan** [comment]
Can you please share the user names with me in a private DM? So I can check the security for their meta databases?

**Comment by dianabarsan** [comment]
Ok, I cross-checked the users @binokaryg sent me. All of their meta databases had correct security and also had docs - so these users managed to sync their databases on the next retry. 

I believe this is a race condition where API is very slow to process setting the permissions when the databases are created -because: 
- the meta database creation is triggered when the user 1st attempts a sync: 
https://github.com/medic/cht-core/blob/3.9.x/webapp/src/js/services/db.js#L59
- the initial call to "setup" the database also sets the security for the new database: 
https://github.com/medic/cht-core/blob/3.9.x/api/src/routing.js#L560
https://github.com/medic/cht-core/blob/3.9.x/api/src/services/user-db.js#L93

Webapp doesn't wait for the remote db request to finish, and it immediately starts a sync: 
https://github.com/medic/cht-core/blob/3.9.x/webapp/src/js/services/db-sync.js#L166

If API or CouchDB is slow to set the security of the new database, the client ends up trying to sync to a database they don't have access to. 
This only happens once on 1st login, so it's not a major concern.

**Comment by dianabarsan** [comment]
I just stumbled across this locally and I remembered this issue existed.
The way I had this locally was by: having security set on the `medic` database and having a user with a role that did not match the security object. This was due to a misconfiguration of the user for me locally - so probably not relevant for the case above. 

@binokaryg do you think we should revisit this in 4.x?

**Comment by dianabarsan** [comment]
Closing this as stale. If we see something similar in 4.x, please open a new issue.
