### ISSUE TITLE
Login page redirect loop when password is changed

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7187]
**Describe the bug**
Our app handles getting 401s correctly while the app is open, but if you launch the app into a 401, you'll see a loading screen and a modal with no text. If you ignore the modal and just type the link to login, your login page will be in a redirect loop. 

**To Reproduce**
1. Login as an online user in a fresh browser. This user can even be an admin. 
2. Close all CHT-Core tabs in this browser. 
3. In another browser, as an admin, change the user's password. You can even use the same password the user had before. CouchDb encription involves a random salt, so the session will be invalidated either way. 
4. Back in the browser from step1, open the previously opened tab - basically open an app link like: /messages or something.  
5. See blank screen with modal that has not text. 
6. If you do nothing, the page will refresh after 1 minute and get you to login. 
7. If you manually go to `/medic/login`, the login page will go in a loop. 

**Expected behavior**
We should definitely never get into a redirect loop ever. Anything is better than a redirect loop. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/125154274-e67d9800-e161-11eb-8ec6-1415d069068c.png)

**Video**
https://user-images.githubusercontent.com/35681649/125154128-242df100-e161-11eb-86c0-e365063365f1.mp4

**Environment**
- Browser: any
- App: webapp
- Version: 3.12 but I think this was happening for a while

**Additional context**
For the empty modal, I think the best way is to use the "bootstrap" translations for it, which are cached in the service worker. That way, it will have text even when the user can't access the server to get the translations docs. 
For the login loop, The solution I recommended in https://github.com/medic/cht-core/issues/7186, which is to actually check _session in the login script, should fix this.

**Comment by latin-panda** [comment]
Ready for AT in this [PR](https://github.com/medic/cht-core/pull/7433)

**Comment by lorerod** [comment]
**Reproducible on Master:**
- Blank Screen:
<img width="1301" alt="Captura de Pantalla 2021-12-21 a la(s) 11 03 49" src="https://user-images.githubusercontent.com/21312057/146944443-8bc7aaf3-dcc6-4041-873f-7c17338a62b3.png">

- Login page going on loop:
https://user-images.githubusercontent.com/21312057/146946948-fb5ad7a5-b98a-48ea-9fe9-bfae940541b0.mov

**Fixed on branch:**
- Instead of blank screen I get the expected error modal:
<img width="1398" alt="Captura de Pantalla 2021-12-21 a la(s) 11 25 15" src="https://user-images.githubusercontent.com/21312057/146947263-f1ae55b6-b6e3-487c-8ffc-3bdb03517f56.png">

- No more login loop when manually going to /medic/login:
https://user-images.githubusercontent.com/21312057/146948182-c5889ed7-45ab-43a8-90a1-bda60dad6286.mov

**Comment by latin-panda** [comment]
Thanks Lorena!
Fix is merged into main branch.
