### ISSUE TITLE
Make it possible to display previous task due date formatting via configuration

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7235]
**What feature do you want to improve?**
In 3.9.0 we changed the way we display task due dates in the task list: https://github.com/medic/cht-core/issues/5776 . 
This change made is to all tasks that have a due date in the past will apear as due today, with no option to display a past due date differently. 

**Describe the improvement you'd like**
Implement a configuration option that will allow projects to opt out of the new task due date formatting, and use the old display method, which showed how many days in the past the task was due. 

**Describe alternatives you've considered**
We could also make the "new" task due date format an opt-in, instead of the default. 

**Additional context**
The new UX can be considered confusing for CHWs across some projects. This has been brough forward during squad calls. 
cc @Fatoufall @hiellavis

**Comment by Fatoufall** [comment]
All our partners in W. Africa are confused with the newly proposed display (IH, Muso, MoH Mali), and they all request to get back to the previous display that fits more their expectations. Moreover, we stated internally that the previous display was confused for the cHWs which all our partners do not agree and they confirm that the new one is more confusing.
We should let the 2 configurations available to let the partner decide which one, which is also aligned with our "open-source/flexibility" we claim instead of enforced all the partners to adopt one way regarding the complexity and diversity of health systems we support

**Comment by craig-landry** [comment]
I've added this to the 3.13 release. We have some other work going on that will bring an earlier release date, where some tasks will go to 3.14. This should be included in the 3.13 release (**not** bumped to 3.14).

**Comment by dianabarsan** [comment]
This is ready for AT on `7235-task-due-date-display-config`. Documentation PR: https://github.com/medic/cht-docs/pull/551

There's a new config `task_days_overdue` which switches which translation key is used to display overdue task dates. The new translation (`task.overdue.days`) key receives a `DAYS` param to allow for pluralized translation.

**Comment by ngaruko** [comment]
LGTM.
**Before** 
![image](https://user-images.githubusercontent.com/6979995/133947131-2d3570f2-fc5e-400a-87f7-c244309d35a9.png)

**after**
![image](https://user-images.githubusercontent.com/6979995/133947179-9a84e89c-3c1d-473a-8f05-340a5258631a.png)
 Good to merge.

**Comment by dianabarsan** [comment]
Merged to `master`.
