### ISSUE TITLE
Server Side Purge does not complete to the end

### ISSUE THREAD

**Issue by nomulex** [medic/cht-core#7280]
**Important**: This is a public repository. Anyone in the world can see what's posted here. If you are posting screenshots or log files, please **carefully examine them for** the presence of any kind of **protected health information** (PHI). Images or logs containing PHI _must_ be posted in fully-redacted form, with no visible PHI.

**Describe the bug**
In version 3.10.3, whereas the logs indicate that purging started, the sentinel server side purge  process does not complete to the end.

**Expected behavior**
Purging should complete to the end and display the message `Server Side Purge completed successfully in x minutes`. As shown [here](https://github.com/medic/cht-core/blob/3.10.3/sentinel/src/lib/purging.js#L535).  The process shows that it started by showing [this](https://github.com/medic/cht-core/blob/3.10.3/sentinel/src/lib/purging.js#L513) output but it never completes. 

**Logs**
If applicable, include the server or browser logs.

```
[2021-08-27 08:30:00] 2021-08-27 08:30:00 INFO: Running server side purge 
[2021-08-27 09:30:00] 2021-08-27 09:30:00 INFO: Running server side purge 
[2021-08-27 14:00:00] 2021-08-27 14:00:00 INFO: Running server side purge 
```

**Environment**
- Instance: (eg: clone-pXX.dev.medicmobile.org, etc)
- Version: 3.10.3

**Comment by nomulex** [comment]
I see the below error in the log and [this](https://github.com/apache/couchdb/issues/1600#issuecomment-658838147) thread says that that happens as `a result of the client dropping its connection to CouchDB.`   
```
[error] 2021-08-31T11:46:22.087939Z couchdb@127.0.0.1 <0.9320.78> 70632138a5 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2021-08-31T11:46:30.156350Z couchdb@127.0.0.1 <0.12114.78> 24fd4ad4ef req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2021-08-31T11:49:57.819202Z couchdb@127.0.0.1 <0.2434.76> 514ab31066 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2021-08-31T11:50:03.233327Z couchdb@127.0.0.1 <0.9920.76> d3f667a389 req_err(1125717067) unknown_error : normal
    [<<"chttpd:catch_error/3 L356">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[error] 2021-08-31T11:50:36.904227Z couchdb@127.0.0.1 <0.12006.78> 4e9fd921fd req_err(1125717067) unknown_error : normal
```

**Comment by njogz** [comment]
```Error while running Server Side Purge: FetchError: request to https://clone-pih-malawi.dev.medicmobile.org/medic-purged-role-f504eddcf3620476ae085e09909a4c82/_bulk_docs failed, reason: getaddrinfo ENOTFOUND clone-pih-malawi.dev.medicmobile.org```

```at ClientRequest.<anonymous> (/Users/njuguna/Documents/work/cht-core/sentinel/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'request to https://clone-pih-malawi.dev.medicmobile.org/medic-purged-role-f504eddcf3620476ae085e09909a4c82/_bulk_docs failed, reason: getaddrinfo ENOTFOUND clone-pih-malawi.dev.medicmobile.org',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  [stack]: 'FetchError: request to https://clone-pih-malawi.dev.medicmobile.org/medic-purged-role-f504eddcf3620476ae085e09909a4c82/_bulk_docs failed, reason: getaddrinfo ENOTFOUND clone-pih-malawi.dev.medicmobile.org\n' +
    '    at ClientRequest.<anonymous> (/Users/njuguna/Documents/work/cht-core/sentinel/node_modules/node-fetch/lib/index.js:1455:11)\n' +
    '    at ClientRequest.emit (events.js:314:20)\n' +
    '    at TLSSocket.socketErrorListener (_http_client.js:427:9)\n' +
    '    at TLSSocket.emit (events.js:314:20)\n' +
    '    at emitErrorNT (internal/streams/destroy.js:92:8)\n' +
    '    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:84:21)',
  name: 'FetchError'
}```

**Comment by njogz** [comment]
```
2021-08-31 15:05:06 ERROR: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n" StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"
    at new StatusCodeError (/Users/njuguna/Documents/work/cht-core/sentinel/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/njuguna/Documents/work/cht-core/sentinel/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/njuguna/Documents/work/cht-core/sentinel/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/njuguna/Documents/work/cht-core/sentinel/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/Users/njuguna/Documents/work/cht-core/sentinel/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/Users/njuguna/Documents/work/cht-core/sentinel/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)```

**Comment by njogz** [comment]
Got the errors above when running purging locally but pointed to a clone DB. Also getting quite a few transitions errors like the one below.

```2021-08-31 15:11:00 ERROR: transitions: processChange failed for 307a8566-5dbc-4c3b-89ef-d9076656d94d : FetchError: invalid json response body at https://clone-pih-malawi.dev.medicmobile.org/medic/_design/medic-client/_view/docs_by_id_lineage?include_docs=true&startkey=%5B%22307a8566-5dbc-4c3b-89ef-d9076656d94d%22%5D&endkey=%5B%22307a8566-5dbc-4c3b-89ef-d9076656d94d%22%2C%7B%7D%5D reason: Unexpected token < in JSON at position 0
    at /Users/njuguna/Documents/work/cht-core/sentinel/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  message: 'invalid json response body at https://clone-pih-malawi.dev.medicmobile.org/medic/_design/medic-client/_view/docs_by_id_lineage?include_docs=true&startkey=%5B%22307a8566-5dbc-4c3b-89ef-d9076656d94d%22%5D&endkey=%5B%22307a8566-5dbc-4c3b-89ef-d9076656d94d%22%2C%7B%7D%5D reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json',
  [stack]: 'FetchError: invalid json response body at https://clone-pih-malawi.dev.medicmobile.org/medic/_design/medic-client/_view/docs_by_id_lineage?include_docs=true&startkey=%5B%22307a8566-5dbc-4c3b-89ef-d9076656d94d%22%5D&endkey=%5B%22307a8566-5dbc-4c3b-89ef-d9076656d94d%22%2C%7B%7D%5D reason: Unexpected token < in JSON at position 0 
```

**Comment by njogz** [comment]
> `Error while running Server Side Purge: FetchError: request to https://clone-pih-malawi.dev.medicmobile.org/medic-purged-role-f504eddcf3620476ae085e09909a4c82/_bulk_docs failed, reason: getaddrinfo ENOTFOUND clone-pih-malawi.dev.medicmobile.org`
> 
> ```
>     at ClientRequest.emit (events.js:314:20)
>     at TLSSocket.socketErrorListener (_http_client.js:427:9)
>     at TLSSocket.emit (events.js:314:20)
>     at emitErrorNT (internal/streams/destroy.js:92:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   message: 'request to https://clone-pih-malawi.dev.medicmobile.org/medic-purged-role-f504eddcf3620476ae085e09909a4c82/_bulk_docs failed, reason: getaddrinfo ENOTFOUND clone-pih-malawi.dev.medicmobile.org',
>   type: 'system',
>   errno: 'ENOTFOUND',
>   code: 'ENOTFOUND',
>   [stack]: 'FetchError: request to https://clone-pih-malawi.dev.medicmobile.org/medic-purged-role-f504eddcf3620476ae085e09909a4c82/_bulk_docs failed, reason: getaddrinfo ENOTFOUND clone-pih-malawi.dev.medicmobile.org\n' +
>     '    at ClientRequest.<anonymous> (/Users/njuguna/Documents/work/cht-core/sentinel/node_modules/node-fetch/lib/index.js:1455:11)\n' +
>     '    at ClientRequest.emit (events.js:314:20)\n' +
>     '    at TLSSocket.socketErrorListener (_http_client.js:427:9)\n' +
>     '    at TLSSocket.emit (events.js:314:20)\n' +
>     '    at emitErrorNT (internal/streams/destroy.js:92:8)\n' +
>     '    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n' +
>     '    at processTicksAndRejections (internal/process/task_queues.js:84:21)',
>   name: 'FetchError'
> }```
> ```

Gotten this error twice and it seems to be the one that crashes the purging script. It fails when fetching the same purge db `https://clone-pih-malawi.dev.medicmobile.org/medic-purged-role-f504eddcf3620476ae085e09909a4c82/_bulk_docs`

**Comment by garethbowen** [comment]
I think there's a problem with your clone. ENOTFOUND means it can't resolve the _domain_ let alone the server or specific couch database. When I try and access it directly I get a "502 bad gateway".

**Comment by dianabarsan** [comment]
It looks like purging has completed successfully on the clone, after lowering the contact batch size. 

Looking at the data present on the instance, it seems that there is some incorrect configuration or some unwanted interaction, that ends up linking (in `docs_by_replication_key`) CHWs to a large number of reports. 
In [`docs_by_replication_key`](https://github.com/medic/cht-core/blob/master/ddocs/medic/views/docs_by_replication_key/map.js#L26) view, we emit for the submitter when there is a `registration_not_found` or a `invalid_patient_id` error present on the current report. Purging uses this view to get all related reports and messages for a contact. 
If, by a misconfiguration, a large number of frequently added reports end up having `registration_not_found` errors, all of these reports will become linked to the submitting CHW's contact, instead of the patient contact. 
Looking at actual data, I found many CHWs that have thousands of reports associated to them: 

| Contact UUID | Number of reports | Direct link to query |
| ------ | ------- | ------ | 
| e4570905-5c1c-58eb-b9cc-aa051c6a5315 | 5214 | [link](https://clone-pih-malawi.dev.medicmobile.org/medic/_design/medic/_view/docs_by_replication_key?key="e4570905-5c1c-58eb-b9cc-aa051c6a5315") | 
| 388d04f9-8166-5c72-b06c-929d3c7827f7 | 4283 | [link](https://clone-pih-malawi.dev.medicmobile.org/medic/_design/medic/_view/docs_by_replication_key?key="388d04f9-8166-5c72-b06c-929d3c7827f7") | 
| 5f12ddc9-7e50-5607-af1d-7ab24c6d3437 | 3689 | [link](https://clone-pih-malawi.dev.medicmobile.org/medic/_design/medic/_view/docs_by_replication_key?key="5f12ddc9-7e50-5607-af1d-7ab24c6d3437") | 
| 12a1fab6-f17b-51e8-a9f3-79b292018293 | 3630 | [link](https://clone-pih-malawi.dev.medicmobile.org/medic/_design/medic/_view/docs_by_replication_key?key="12a1fab6-f17b-51e8-a9f3-79b292018293") | 
| e6b7a090-d481-5a5b-a58c-0009a223f730 | 3566 | [link](https://clone-pih-malawi.dev.medicmobile.org/medic/_design/medic/_view/docs_by_replication_key?key="e6b7a090-d481-5a5b-a58c-0009a223f730") | 
| e2a5828e-45e5-5bb7-85e2-6106f97df547 | 3527 | [link](https://clone-pih-malawi.dev.medicmobile.org/medic/_design/medic/_view/docs_by_replication_key?key="e2a5828e-45e5-5bb7-85e2-6106f97df547") | 
| ce74812a-d679-53c8-91ba-d50feaff26907 | 3499 | [link](https://clone-pih-malawi.dev.medicmobile.org/medic/_design/medic/_view/docs_by_replication_key?key="ce74812a-d679-53c8-91ba-d50feaff26907") | 

The list goes on, with hundreds CHWs having over 2000 reports associated to them. 

Looking at one of the listed reports, the contents look like: 
```
{
  "_id": "013b0546-1b02-494e-8f0f-af524f776b0a",
  "_rev": "3-b26d2d6bdfd0581c33655e917d977acc",
  "fields": {
    "tb_symptoms": "none",
    "last_tb_test_results": "",
    "c_refer_for_sputum": "no",
    "c_accompany_to_hf": "no",
    "is_referral_case": "no",
    "patient_id": "ee92ab6f-9eae-47ca-a91d-095731d666ea",
    "patient_age_in_years": "7",
    "source": "contact",
    "source_id": "",
    "patient_uuid": "ee92ab6f-9eae-47ca-a91d-095731d666ea",
    "patient_name": "<redacted>"
  },
  "child_doc": "013b0546-1b02-494e-8f0f-af524f776b0a",
  "created_by_doc": "f2272020-2d11-4826-88df-1d9e30c72afe",
  "content_type": "xml",
  "type": "data_record",
  "form": "tb_screening",
  "contact": {
    "_id": "35cc1d83-5af5-575f-8e38-b997b94e15bc",
    "parent": {
      "_id": "3e0a65ef-b951-500a-ac94-ba8c76521ff0",
      "parent": {
        "_id": "1614ccba-f6c1-5331-aede-9c136c5b4826",
        "parent": {
          "_id": "65719615-bd69-5322-a1a1-b4598afa0218"
        }
      }
    }
  },
  "reported_date": 1575809987807,
  "imported_date": "2020-03-21T16:34:51.074Z",
  "tasks": [
    {
      "messages": [
        {
          "uuid": "5e054324-5346-43ca-a75f-285dc0062201",
          "to": "<redacted>",
          "error": "messages.errors.message.empty"
        }
      ],
      "state_history": [
        {
          "state": "duplicate",
          "timestamp": "2020-03-21T16:35:24.297Z"
        }
      ],
      "state": "duplicate"
    }
  ],
  "errors": [
    {
      "message": "messages.generic.registration_not_found",
      "code": "registration_not_found"
    }
  ]
}
```

The `patient_uuid` is set as `ee92ab6f-9eae-47ca-a91d-095731d666ea`. This document doesn't exist any more, it has been deleted. 

Because of this unfortunate linking between CHWs are reports, with the contacts purging batch size set to 1000, the first batch would load **718424 reports** in memory, and try to process them at the same time. 

I think setting a configuration option to set the purging batch size is a good change. Some project could inherently require to lower the batch size, because of lower instance size and other considerations, that exclude misconfigurations. 

Additionally the project team should investigate the nature of those reports. Why they are logged against deleted contacts? Did the patient contacts exist when the reports were created were created? Did the transitions run over the reports long after the reports were created and contacts were deleted?

**Comment by garethbowen** [comment]
> I think setting a configuration option to set the purging batch size is a good change. Some project could inherently require to lower the batch size, because of lower instance size and other considerations, that exclude misconfigurations.

I'm not a big fan of configuration as a solution to this. It's difficult to detect when it's failing so maintainers won't know they have to change the setting. And then if it's a historical misconfiguration they would have to remember to change it back again for performance when the backlog is cleared.

If possible it'd be great if this was more automatic so when a request times out the batch size was reduced and the request was retried. This is more complicated to code but helps keep sentinel self maintaining.

**Comment by dianabarsan** [comment]
>  this was more automatic so when a request times out the batch size was reduced

That would be awesome, and I thought about it as well, though I'm not certain the request was actually timing out. I think it was either OOM-ing sentinel by its sheer size, either when the response was parsed or when the data was processed. 

I thought about doing a "poll" before making this big request. Say we would add another "limit" of say 10000 reports (determine which number of reports we are comfortable with processing in one batch!), and we would request with the same keys, but with a limit and without include_docs. If we would get results equal to our limit, we would reduce (halve?) the batch size. 
This would, in most cases, just make the whole process slower because of the additional expensive request though. :(

**Comment by garethbowen** [comment]
> ...though I'm not certain the request was actually timing out.

Ahh ok. Thanks for clarifying!

I think we have to put some limit on it. Assuming this is a rare occurrence and 99% of the time the request will return a manageable number of docs, what if we made the request with a limit of 10k _and_ still included the docs. Then 99% of the time the request will complete as fast as it does now, but the 1% of the time we can detect a full page is returned, throw away the results, and try a smaller batch.

It seems inefficient but currently we're crashing with an OOM so replacing that with a wasted query is a definite improvement.

**Comment by dianabarsan** [comment]
Works for me!

**Comment by dianabarsan** [comment]
Ready for AT on `7280-dynamic-purge-batches`. Documentation PR: https://github.com/medic/cht-docs/pull/566

What's changed: 
- view update, expect to have to some indexing time if reusing a large database when testing
- more logging during purging, when not in a development environment
- should work on databases where contacts have thousands of records associated to them
- if a contact has more than 20.000 records, it will be skipped (this means that none of its records will be purged). A log should appear when a contact is skipped and the id of this contact should be saved in a new `skipped_contacts` property in your purgelog
- if a contact batch has more than 20.000 records, contact batch size will be halved. If a contact batch has less than 5000 records, contact batch size is doubled, up to the maximum of 1000. Every time purging runs, the batch size should reset to the default of 1000 and start decreasing and increasing with processing. 
- if purging fails due to an error, the error should be logged to the console and a `purgelog:error:<timestamp>` document should be created. Details about this document can be found in documentation.

**Comment by dianabarsan** [comment]
@ngaruko please let me know if I can assist with anything concerning AT.

**Comment by ngaruko** [comment]
1. Successful purge:
```
2021-12-01 01:32:10 DEBUG: Starting unallocated purge batch with id  
2021-12-01 01:32:10 DEBUG: Starting tasks purge batch with id  
2021-12-01 01:32:10 DEBUG: Starting targets purge batch with id target~ 
2021-12-01 01:32:10 INFO: Server Side Purge completed successfully in 0.4087002202490966 minutes 
```
2. Batched purge under 20k docs
```
2021-12-01 02:52:09 INFO: Found 10004 records 
2021-12-01 02:52:40 INFO: Purging: Starting contacts batch: key "person", doc id "fc721419-87de-5878-a34e-e07e003d0f42", batch size 1000 
2021-12-01 02:52:40 INFO: Purging: Starting "unallocated reports" purge batch with id "" 
2021-12-01 02:52:40 INFO: Purging: Starting "tasks" purge batch with id "" 
2021-12-01 02:52:40 INFO: Purging: Starting "targets" purge batch with id "target~" 
2021-12-01 02:52:40 INFO: Purging completed in 0.5646954360504944 minutes 
```
3. Skipped for over 20k docs: 

Also noticed error reported in #7419 (will work on it next)
![image](https://user-images.githubusercontent.com/6979995/144172470-4f0be6e2-cbc7-4342-b53f-6ca524e7ab74.png)

**Comment by dianabarsan** [comment]
Merged to `master`.

**Comment by ngaruko** [comment]
Retesting for [3.13.1](https://github.com/medic/cht-core/milestone/97). Leaving notes here for future @medic/quality-assurance reference. Purging [docs here](https://docs.communityhealthtoolkit.org/apps/guides/performance/purging/).
Testing this will local dev set up (not docker or horti, just to have more control and easier access to `api` and `sentinel` logs.

1. [Deploy](https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#deploying-cht-core) `cht-core` with branch checked out .
2. Enable server side purging by adding `purge` to `app-settings.json`: 
```
"purge": {
        "fn": "function(userCtx, contact, reports, messages) { const old = Date.now() - (1000 * 60 * 60 * 24 * 365); return reports.filter(r => r.reported_date < old).map(r => r._id);}",
        "text_expression": "at 12 am on Sunday"
    }
```
3. Upload settings.

**Comment by ngaruko** [comment]
1 . Purge does complete on first deployment 
```Purging: Starting "tasks" purge batch with id "" 
2022-01-24 02:27:53 INFO: Purging: Starting "targets" purge batch with id "target~" 
2022-01-24 02:27:53 INFO: Purging completed in 0.09680749961535136 minutes ```
