### ISSUE TITLE
Login page is not cached correctly

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7307]
**Describe the bug**
If a user logs off while being disconnected from the internet, they won't be able to access the login page. 

**To Reproduce**
1. Login as an offline user.
2. Disconnect from the internet.
3. Logout. 
4. You're seeing your browser's "No internet" page instead of the cached login page. 

**Expected behavior**
Login page should be cached: https://github.com/medic/cht-core/pull/5557

**Environment**
- Instance: (eg: alpha.dev.medicmobile.org, etc)
- Browser: (eg: Firefox, Chrome, incognito mode, etc, which worked, which didn't)
- Client platform: (eg: Windows, MacOS, Linux)
- App: (eg: webapp, admin, sentinel, api, couch2pg, medic-conf, etc)
- Version: (eg: 2.15.0, 3.0.0, etc)

**Additional context**
This [commit](https://github.com/medic/cht-core/commit/69c59f3a02e3887bda7a5d78391e82e7244a6083) adds the new "username" parameter to the login GET request, without adding it to the ignored URL parameters in the service worker (https://github.com/medic/cht-core/blob/master/grunt/service-worker.js#L42)

**Comment by dianabarsan** [comment]
This is ready for AT on `6338-live-service-worker`

**Comment by ngaruko** [comment]
**_on master_** 
![image](https://user-images.githubusercontent.com/6979995/135770946-e8debd32-d4ad-4ab8-b138-b9eb5f25f56a.png)
**_On the branch_**
![image](https://user-images.githubusercontent.com/6979995/135778606-cdb0de84-1d8c-47e1-b631-e89b0d871146.png)

One observation though @dianabarsan, the login page that appears directly upon logout gets pre-populated with the admin credentials, not the actual offline user (as seen in the s/shot) while the redirect url contains the user: `http://localhost:5988/medic/login?redirect=http%3A%2F%2Flocalhost%3A5988%2F%23%2Freports&username=andra`. is this the expected behaviour?

**Comment by dianabarsan** [comment]
This is something different, it's about browser autocomplete. 
The username from the query parameters isn't supposed to be pre-filled in the field. I think what you're seeing is your default browser behavior. 
Can you please try with another browser (where you don't have autocomplete) or set autocomplete off?

**Comment by dianabarsan** [comment]
Merged to `master`.
