### ISSUE TITLE
Prepare for future user management UI with API to create many users

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7490]
**Describe the issue**
Currently it is a laborious process to create many users via the API/cht-conf. In some cases we require UUIDs to match up and in others it can [be a convoluted process](https://forum.communityhealthtoolkit.org/t/cht-conf-create-users-error-wrong-type-object-is-not-a-place/1647) (or both!)

**Describe the improvement you'd like**
An API that can be used directly to create many uses that is easy to use, well documented, and returns helpful errors when creation fails. Ideally it should create the contact, the contact's place and a user with correct role, place, contact and password.  Extra ideal would be if it could be tied into [magic link](https://docs.communityhealthtoolkit.org/apps/concepts/access/#magic-links-for-logging-in) delivery to easy login.

**Describe alternatives you've considered**
Existing methods [as documented](https://docs.communityhealthtoolkit.org/apps/guides/data/csv-to-docs/#creating-new-users-with-new-contacts).

**Comment by mrjones-plip** [comment]
@m5r and @dianabarsan - I'm back filling a feature ticket for core PR #medic/cht-core/pull/7454  and docs PR  medic/cht-docs/pull/614.  I wasn't sure quite what to put in the body, so took my best guess - please keep me honest!

**Comment by dianabarsan** [comment]
The current API to create users already connects to magic-link delivery. 
At this moment, the new API is identical to the old API, except it can create multiple users at once. Aforementioned convolutions are still included :) (one still needs to provide some uuids for place creation for every user, at least!).

**Comment by mrjones-plip** [comment]
Great thanks @dianabarsan! Feel free to keep the title of this ticket apt for a...3.15 release? I guess we'll see!

**Comment by m5r** [comment]
This is ready for AT on branch `api/create-many-users`  
[Code PR link](https://github.com/medic/cht-core/pull/7454)  
[Docs PR link](https://github.com/medic/cht-docs/pull/614)

**Comment by mrjones-plip** [comment]
Super awesome news this is in AT - congrats @m5r!

@medic/quality-assurance - While completing AT, it may be handy to both view the new docs in [rendered markdown form,](https://github.com/medic/cht-docs/blob/1dd3f827021c001e4c647de092d5fd1f67168fb8/content/en/apps/reference/api.md#post-apiv1users) as well as compare them to the [same doc currently in master](https://github.com/medic/cht-docs/blob/main/content/en/apps/reference/api.md#post-apiv1users) to know what's changed.

**Comment by lorerod** [comment]
**Scenarios tested (the successful are ticked ✓):**
- [X] Create one user successfully.
- [X] Create multiple users successfully.
- [X] Create users with a list of one element.
- [X] Create an empty list of users.
- [X] Try to create a user without the required fields. 
- [X] Try to create a user without an invalid phone number. 
- [X] Try to create a user that already exists.
- [X] Try to create multiple users with one user missing the required field.
- [X] Try to create multiple users with one user with an incorrect password. 
- [X] Try to create multiple users with one user with an invalid phone. 
- [X] Try to create multiple users with one user that already exists.
- [X] Try to create one user using a user without permission.

Suggestion about the documentation. But not a blocker for this issue:
1. Make clear in the documentation the association between the `type` and `roles` properties. Or maybe use `roles` in examples instead of `type`. @m5r mentioned [this](https://github.com/medic/cht-core/blob/master/api/src/services/types-and-roles.js) and the fact that the property `type` is deprecated.

**Comment by mrjones-plip** [comment]
@m5r and @dianabarsan - thank you!
