### ISSUE TITLE
Improve initial replication 

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7528]
**What feature do you want to improve?**
The user can experience slow initial load of the app. Quoting from [here](https://github.com/medic/cht-core/issues/7492#issuecomment-1038607050):

> I have particular concerns about the initial replication stage which I suspect could be causing significant issues in production when the connection is dropped before the first batch of docs is returned. If that happens I think the initial replication will start again from 0 because the replication API for Pouch and Couch doesn't store checkpointers for partial batches - you need to fill up the entire batch of 100 docs before Pouch will record progress. Particularly with new users to servers with a lot of historical changes this may take some time.

**Describe the improvement you'd like**
Find a way to not start replication from zero if it already has replicated some. 

**Additional context**
[See discussion in this other ticket. ](https://github.com/medic/cht-core/issues/7492)

**Comment by latin-panda** [comment]
@mrjones-plip is this allies or care team? 🤔

**Comment by dianabarsan** [comment]
I don't think this can be changed without completely rewriting how PouchDb does replication. 

Currently, everything is batched, including writes to the local database. Every batch of docs is 100 docs. I don't think it's costly enough to consider rewriting the whole thing, potentially abandoning batching and doing a one-by-one get and write to insure checkpointers will be written mid batch. 

Also, writing checkpointers after replicating every doc (especially if the checkpointer is saved server-side as well) adds a server request  for every replicated doc.

**Comment by dianabarsan** [comment]
One thing we could consider is to reduce the batch size if we detect that the connection is unstable, and not touch the replication mechanism at all.

**Comment by garethbowen** [comment]
> I don't think this can be changed without completely rewriting how PouchDb does replication.

I think you're right that it would need some PouchDB change. I think it could be done surgically by patching out a specific module rather than a complete rewrite but that would need some investigation. I keep wondering if there's a sneaky way to update the checkpointer while PouchDB isn't looking but it feels risky.

It's worth doing some investigation to determine whether this actually happens, how often we'd expect it to happen, and what the impact would be. This information may even be available in our telemetry docs. If it's sufficiently painful we can use that to prioritise a fix.

Ultimately it may end up requiring a change to PouchDB and/or CouchDB but that shouldn't be a blocker.

**Comment by mrjones-plip** [comment]
> @mrjones-plip is this allies or care team? thinking

let's call it care team!  cc @michaelkohn

**Comment by dianabarsan** [comment]
@latin-panda Initial replication has been rewritten. Do you think this issue has to be revisited?

**Comment by latin-panda** [comment]
Initial replication is faster by the work done in this issue: #8134 and available in [v4.2.0](https://docs.communityhealthtoolkit.org/core/releases/4.2.0/). See detailed performance [here](https://github.com/medic/cht-core/pull/8141#issuecomment-1485675042).
