### ISSUE TITLE
Add "update known issues" step to patch ticket template 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7562]
**Describe the issue**
Right now we don't have a documented process for patches that updates the prior release.  For example in 3.14.0, there's no updates about 3.14.1 or 3.14.2 ([but there will be soon](https://github.com/medic/cht-docs/pull/651)).

**Describe the improvement you'd like**
We should add a step in [the patch release ticket template](https://github.com/medic/cht-core/blob/master/.github/ISSUE_TEMPLATE/z_release_patch.md) that is "Update known issues on prior release"

**Describe alternatives you've considered**
None

**Comment by mrjones-plip** [comment]
Per [this comment](https://github.com/medic/cht-core/pull/7563#pullrequestreview-911011884), we're going to look at taking another approach for this.

**Comment by garethbowen** [comment]
I've been thinking about the ideal solution here. My requirements are...

1. Dynamic list of known issues. If someone has to remember to go back and update the release notes every time an issue is found it'll get forgotten.
2. I think the release notes should list regressions only rather than all bugs in that release. In part this is because there are simply too many bugs in the repo, but also if someone is looking to upgrade what they most want to know is if anything is going to break (breaking changes + regressions). I think we should rename the section from "known issues" to "known regressions" or similar to make this clear to all.
3. Regressions should be listed in all release notes between when it was introduced and when it was fixed.

Given that I think the release notes should have a link to a GH issues search. There are two options on this... 

1. Search for all issues with the existing "Regression" label created after the release date. This will get slowly out of date because as far as I can tell there's no way to tell when a regression was introduced to the codebase.
2. Add new labels for which releases are impacted by the regression, eg: "Affects: 3.14.1". Multiple of these labels could be added to represent each release that has this regression. The label would only be created if the release has a regression.

I'm leaning towards option 2 which has a slight overhead when creating the issue but means the "known issues" link is very accurate. It's also useful information to have captured on the issue!

@mrjones-plip How does this sound to you?

**Comment by mrjones-plip** [comment]
Thanks for thinking on this Gareth! Some good stuff here.  

Will the end result be that each versions "Known Regressions" will have a link to a GH issue search, and not enumerate the issues inline?  This seems like a (ahem) regression in our release notes then. It will send users on a click chase to find out known regressions as I'm assuming to make it a "zero actions in docs" behavior, you'd have to pre-emptively add the search to every release, no matter if there were regressions or not.

Could we update the [release note changelog script](https://github.com/medic/cht-core/blob/master/scripts/release-notes/index.js) to generate this new section programmatically such that it'd be a copy and paste job?  This violates your "If someone has to remember to go back and update the release notes every time an issue is found it'll get forgotten." policy though :(

Ideally this would be entirely captured in a GH Action for every patch release....that's likely too hard though. 

Oh...maybe not?! That'd be something like:
* We always tag issues, just as you've described
* When we do any release (major, minor, patch) we do a release page, like we do today
* We [add the ability](https://gohugo.io/templates/data-templates/#get-remote-data) to effectively run the current [changelog script](https://github.com/medic/cht-core/blob/master/scripts/release-notes/index.js) and a modified "known regressions only" version inline. These would be `change_log` and `known_regressions' and accept an inline `version` input. It would leverage your new  "Affects: 3.14.0" style of tags.
* Hugo will build the page with:
   ```
   # 3.14.0 release notes
   
   {{< known_regressions version="3.14.0 " >}}
   
   Lots of great info about the release here, customized by release engineer
   
   {{< change_log version="3.14.0 " >}}
   ```
* EVERY time a CHT version is released (major, minor, patch), we have the cht-core GH Actions trigger a build on cht-docs, thus replenishing all applicable prior `change_log` and `known_regressions` for every release...automatically! 

This feels like a lot of work upfront, but a lot less work on the day to day release cycle.

**Comment by garethbowen** [comment]
>  This seems like a (ahem) regression in our release notes then.

Previously this section existed but was never updated (ie: always said "none"), so I'd say it's an improvement.

> EVERY time a CHT version is released (major, minor, patch), we have the cht-core GH Actions trigger a build on cht-docs, thus replenishing all applicable prior change_log and known_regressions for every release...automatically!

I think this is happening too late - you want the release notes to be updated when a regression is _found_, not when it's _fixed_. If we're to do a trigger it should be done when the issue label is applied.

> This feels like a lot of work upfront, but a lot less work on the day to day release cycle.

I agree this level of automation feels overkill. Regressions aren't frequent enough to warrant the extra work up front in my opinion.

I propose we go with labeling option 2, and use the GH issues search link in the release notes. At a later date we can add the automation using the same labels and remove the search link. Sound like a reasonable compromise?

**Comment by mrjones-plip** [comment]
> Previously this section existed but was never updated (ie: always said "none"), so I'd say it's an improvement.

Hah! Excellent point - thanks for the reality check!  This totally _is_ an improvement - ship it (and extra instructions on how to label) and we'll iterate from there as needed.  I closed this ticket already - feel free to re-open as needed!

**Comment by mrjones-plip** [comment]
Oh - oops - agreed ship option 2!
