### ISSUE TITLE
Update to latest enketo-core

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#7599]
**Describe the issue**
Not to be confused with #6345 which is upgrading to enketo-core to `^5.18.1`, this issue is for upgrading to the next latest version of Enekto (since it already contains several fixes that we know we would like).

**Describe the improvement you'd like**
Once we have upgraded to the latest enketo-core, these are no longer necessary (since they are included in the new Eneketo code) and can be removed:
- [Logic for pausing multimedia when switching pages](https://github.com/medic/cht-core/commit/772a4feac360e8265af15b1fe7292b47ba2f0649)
- [Patch for Enketo repeat name collision issue](https://github.com/medic/cht-core/commit/3cb901c26a2754769577f6f5dce869ce63cb2de1)

**Comment by jkuester** [comment]
Note that we will need to pay attention to https://github.com/enketo/enketo-core/issues/849 since those changes will almost certainly require some changes to how we are handling saving the `inputs` data.

**Comment by jkuester** [comment]
The current CHT/Enketo has a weird behavior (described in [this forum thread](https://forum.communityhealthtoolkit.org/t/unexpected-duplicate-multi-select-drop-down-component-rendered/2668/6)) where some kind of weird conflict occurs when a calculating a `repeat_count` based on a field that has a `choice_filter`.  This issue appears to be fixed in the latest version of Enketo (I cannot recreate the behavior on https://getodk.org/xlsform/), but we should ensure this is fixed in the CHT when upgrading to the latest version of Enketo.  

To recreate the issue, make a form with the following:

survey:

type | name | label::en | appearance | calculation | choice_filter | repeat_count
-- | -- | -- | -- | -- | -- | --
begin group | begin |   | field-list |   |   |  
select_one yes_no | yes_or_no | Yes or No |   |   |   |  
select_multiple yes_no_translations | selected_translations | Translations |   |   | category=${yes_or_no} |  
begin repeat | my_translations | "No" translations |   |   |   | if(${yes_or_no}='yes',0,count-selected(${selected_translations}))
calculate | my_calc |   |   | selected-at(${selected_translations}, position(..)-1) |   |  
note | my_note | Selected: ${my_calc} |   |   |   |  
end repeat | my_translations |   |   |   |   |  
end group | begin |   |   |   |   |  

choices:

list_name | name | label::en | category
-- | -- | -- | --
  |   |   |  
yes_no | yes | Yes |  
yes_no | no | No |  
  |   |   |  
yes_no_translations | yes | Yes | yes
yes_no_translations | ja | Ja | yes
yes_no_translations | oui | Oui | yes
yes_no_translations | no | No | no
yes_no_translations | nein | Nein | no

Then upload the form to a CHT instance and follow these steps:
- Open the form
- Select `Yes` for the "Yes or No" question
- For "Translations", select _more than one_ option (does not matter which ones)
- Go back to the "Yes or No" question and change the answer to `No`
- For "Translations", select _more than one_ option (does not matter which ones)
- See that the ""No" translations" repeat does not work correctly. 
  - The notes are not properly formatted
  - There is to `1` entry, but instead it starts from `2`.

![image](https://user-images.githubusercontent.com/8441903/234375637-6b6d822c-16f1-4279-9ed2-6eedf5ab570a.png)

This broken behavior does not happen when just choosing `No` as the original answer to the "Yes or No" question...

**Comment by garethbowen** [comment]
Bumping to 4.4.0 as we're almost ready to release 4.3.0 and this has more work needed yet.

**Comment by m5r** [comment]
Quick recap of what happened so far:

- Both patches are now removed
  - ~~[Logic for pausing multimedia when switching pages](https://github.com/medic/cht-core/commit/772a4feac360e8265af15b1fe7292b47ba2f0649)~~ removed in the [uplift PR](https://github.com/medic/cht-core/pull/8528)
  - ~~[Patch for Enketo repeat name collision issue](https://github.com/medic/cht-core/commit/3cb901c26a2754769577f6f5dce869ce63cb2de1)~~ removed in a [previous PR](https://github.com/medic/cht-core/pull/8307)
- Upgraded Enketo to the latest version released to date and ported the existing patch to keep inputs always relevant
- Removed any anything related to the enketo widget `analog-scalepicker`
- Added the required config for forms to keep working - I left [a comment in the PR](https://github.com/medic/cht-core/pull/8528/files#r1323397157) about this because I couldn't find this info anywhere in Enketo's docs and found out about this config by trial and error

Now all tests are passing, even the ones included in https://github.com/medic/cht-core/pull/8480 - I merged them in a temporary branch just to make sure that they would [pass in CI](https://github.com/medic/cht-core/actions/runs/6173671787)

------

Here is what the next steps look like:

- Some manual testing:
  - around [how inputs are saved](https://github.com/medic/cht-core/issues/7599#issuecomment-1108582297) - I haven't noticed anything particularly out of touch but my tests were superficial so far
  - confirm the upgrade fixes the bugs mentioned in [this comment](https://github.com/medic/cht-core/issues/7599#issuecomment-1522273957), in [cht-core#8102](https://github.com/medic/cht-core/issues/8102), in [cht-core#8301](https://github.com/medic/cht-core/issues/8301)
  - measure performance improvements for [forms that were slow to load](https://github.com/enketo/enketo-core/issues/982) -- and potentially look into enabling the [`computeAsync` enketo config](https://github.com/enketo/enketo-core/pull/881)
- Consider if we should remove the polyfills included in https://github.com/medic/cht-core/blob/master/webapp/src/ts/polyfills.ts#L69-L76 or if it's more related to https://github.com/medic/cht-core/issues/8159

Calling in @jkuester @tatilepizs for anything I might have missed

**Comment by garethbowen** [comment]
Make sure the release notes include graphs of the performance improvements this brings. This is probably just based on these graphs: https://forum.communityhealthtoolkit.org/t/feature-testing-enketo-7-uplift-for-cht-core/3196/2

**Comment by garethbowen** [comment]
Changed to a "performance" improvement as this has been measured to provide noticeable gains.
