### ISSUE TITLE
Allow Feature Releases to be versioned in CHT Admin UI

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7629]
**Describe the issue**
In #7609 we added a process for releasing versions of Feature Releases as beta releases.  However, they do not show up under beta releases when giving them a `-beta.N` tag (EG `3.15.0-FR-bulk-user-upload-beta.3`, see [here](https://github.com/medic/cht-core/releases/tag/3.15.0-FR-bulk-user-upload-beta.3)): 

![image](https://user-images.githubusercontent.com/8253488/170333762-8cdeac84-584b-485e-9852-d439505443c5.png)

Further, in the top of the admin you can't tell which date/version you're on.  This one is running `beta.3`:

![image](https://user-images.githubusercontent.com/8253488/170360974-f34d5218-8e29-4c7e-a9c4-df888b1bea5a.png)

**Describe the improvement you'd like**
I would like the CD process to show these under a new "Feature Release Beta" section and show the version (eg `-beta.1`, `-beta.2` etc). As well, after installing it should show which version you have installed instead of just the un-versioned branch name.

I suspect this will have to do with how the [Medic Builds repo works](https://github.com/medic/medic-builds-repo/blob/master/ddocs/builds/views/lib/version.js#L32)?

**Describe alternatives you've considered**
Have users of the FRs check the dates of the releases listed in the "Branches" section.  However, they'll get weird warnings like this:

> You are about to upgrade from 3.15.0-FR-bulk-user-upload to 3.15.0-FR-bulk-user-upload.

**Comment by garethbowen** [comment]
I'm not sure about smooshing them into the beta section because it might make them too visible for projects that don't care about the FR.

What might work well is a UI change for when we detect the project is already on an FR, so it's a little awkward to find and install the first time, but after that there's a button right at the top for updating to the latest.

There should definitely be some UI affect which shows if a new FR is available, and the date is probably the best option. I think this is available in the published ddoc so may just need to be exposed in the view.

**Comment by mrjones-plip** [comment]
Gareth - excellent point about not mixing it with the existing Betas. We can call them "Feature Release Betas" to be clear.  I've updated the ticket body to reflect this.

**Comment by m5r** [comment]
Merged to `master` with bulk user upload in #7678
