### ISSUE TITLE
Search bar redesign

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7746]
**Description**
Taken from the [forum post](https://forum.communityhealthtoolkit.org/t/updates-to-the-search-feature/2107): 

As a follow up to our work on [filters](https://forum.communityhealthtoolkit.org/t/feature-testing-filters/1917) ([ticket](https://github.com/medic/cht-core/issues/7653)), the Search feature is next on our [UI evolution](https://forum.communityhealthtoolkit.org/t/updates-to-the-cht-ui-ux/1998).

We are moving to an expandable search to free up real estate in the top bar, collapsing the current search bar into an icon that opens when tapped. Current functionality will remain the same, with users being able to both search and filter results simultaneously.

<details>
<summary> The old version can be seen here </summary>

<img width="700" src=https://user-images.githubusercontent.com/66472237/186577484-500b9909-6801-4bdb-a25a-64d10a83b459.png></img>
<br>
<img width="300" src=https://user-images.githubusercontent.com/66472237/186577524-d46c02bd-99ed-44f8-a0e1-1d95d36a453e.png></img>

</details>

![Screen Shot 2022-08-25 at 11 48 05 am](https://user-images.githubusercontent.com/66472237/186577270-987cbccc-7c7c-41ab-9cee-f067097446be.png)
![Screen Shot 2022-08-25 at 11 48 50 am](https://user-images.githubusercontent.com/66472237/186577385-d9bbde9f-c516-4aaa-941a-4d1e62267065.png)

**Implementation**
The Old and New version of the search and filters interface will be available for a period of time. By default, users will see the new version. You can have users continue to see the old version by giving them the `can_view_old_filter_and_search` [permission](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/user-permissions/) but... the old version will be removed in a future release so it is important to have a plan to get users onto the new version ASAP.

**Comment by latin-panda** [comment]
This is ready for AT in [this PR](https://github.com/medic/cht-core/pull/7758) 
Please have a look at the PR description for details.

**Comment by tatilepizs** [comment]
### Test

**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome
**cht-core version:** `7746-search-bar-redesign`
**Platform - mobiles:** Mobile App. Downloaded from play store **version 1.0.1**

### Mobiles

**Phone:** Samsung Galaxy A01
**Android System WebView Version:** 103.0.5060.129
**Android Version:** 10

**Phone:** Alcatel Onetouch 50560
**Android System WebView Version:** 95.0.4638.74
**Android Version:** 5.1.1

---

<details>
<summary>Search bar redesign - Desktop</summary>

![image](https://user-images.githubusercontent.com/94494491/188940833-8b537ee2-06a4-4202-a412-6f9479e609a9.png)
![image](https://user-images.githubusercontent.com/94494491/188940892-72d12259-7024-4f00-b526-d79d41adc6d0.png)

</details>

<details>
<summary>Search bar redesign  - Mobile - Android 10</summary>

<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188942657-1231630f-92c2-421d-a06b-8b87a9230613.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188942690-359a384c-58f5-4b77-8719-cea1004477a1.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188942717-a15cc331-201e-4a1e-b8c7-ca70095d05d9.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188942755-4c4857d7-534c-4bfa-8891-ad6ba7989ccc.png">

</details>

<details>
<summary>Search bar redesign  - Mobile - Android 5</summary>

<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188943257-908c8db2-dbaf-40dd-b762-b4e3cea2a272.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188943291-6ce6f145-93b2-42fb-8c0a-e674cb744610.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188943321-88cd993f-bf7a-4c8f-ba01-af98aa6bdc78.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188943356-89a0c387-e1b7-4cf9-9edb-589ba834287a.png">

</details>

<details>
<summary>Old search bar enabled - Desktop</summary>

![image](https://user-images.githubusercontent.com/94494491/188943609-4ae8b98e-7a63-446d-adde-a23d4a784f1e.png)
![image](https://user-images.githubusercontent.com/94494491/188943719-e517a09e-9f69-4062-b159-5499e4794cb4.png)
![image](https://user-images.githubusercontent.com/94494491/188943777-d2b2f659-baef-4235-87f1-9dd18c622641.png)

</details>

<details>
<summary>Old search bar enabled - Mobile - Android 10</summary>

<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188944384-7b4f5cde-7b6e-45e4-8764-625aeac40293.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188944425-bf1a346b-69f1-4304-8fe1-ba1ece847f03.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188944470-1ec3ccb6-b524-4ca8-b2ae-b088ee8b64e5.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188944507-b1ffc287-3c41-42b6-89e6-316970013ac0.png">

</details>

<details>
<summary>Old search bar enabled  - Mobile - Android 5</summary>

<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188944611-3c991fb0-f870-49f1-a607-5500678390a0.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188944642-3683c7fa-1dfe-4e8e-9e48-a3f93ad91864.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188944671-1dcfc9f7-7588-41be-9b64-cc7000663f92.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/94494491/188944707-29df73f8-4469-463a-94f8-1f1472309b99.png">

</details>

---

Everything related to the redesign looks perfect 🎉 

I just have one question @latin-panda, how this search actually works? I am asking because, in the `Reports` tab, anything that I type related to the patient's name works perfectly, but if I try to search for something related to the report's name it has some limitations I think. 
For example, I have a `Death report` and an `Undo death report`, if I type the word `death` in the search bar I will expect to see both reports (death report and undo death report) but it is showing only the `Death Report`.

<details>
<summary>Images here</summary>

![image](https://user-images.githubusercontent.com/94494491/188938344-55a60341-a84b-4f39-b3e2-ee0357eb351d.png)
![image](https://user-images.githubusercontent.com/94494491/188938395-1271c01f-bdbf-46ac-9eb3-d73b18337ee2.png)
![image](https://user-images.githubusercontent.com/94494491/188938452-1c506d82-6c7d-4040-a45e-4d117db8d4e8.png)

</details>

And if I search for the word `pregnancy` it will show different reports, even the ones that don't contain the word `pregnancy` in the name on the report, I think that it is also considering the content of the report:

<details>
<summary>Image here</summary>

![image](https://user-images.githubusercontent.com/94494491/188939045-d98eb154-7d1a-497c-9637-1dc45b87d83d.png)

</details>

And if I search for the word `home` (trying to get the Pregnancy Home Visit for example) or the word  `report` (trying to get the death report or the undo death report) it is not showing anything.
 
<details>
<summary>Images here</summary>

![image](https://user-images.githubusercontent.com/94494491/188939655-3a20bd07-93e9-4fca-b91a-eae7c59a5e93.png)
![image](https://user-images.githubusercontent.com/94494491/188939681-55b53c2d-e3c7-4cee-a6ce-6cb50c7cff2b.png)

</details>

I know that if you want to search for the report type, for example, you can use the `filter` section and that will work perfectly, but I am really curious about this functionality, and being honest, the search bar says `Search everything` as the placeholder 😅 

![image](https://user-images.githubusercontent.com/94494491/188940130-09634515-7102-4107-97fc-06ec2de43027.png)

**Comment by latin-panda** [comment]
Thanks @tatilepizs good question

The search is just like any other filter, it uses CouchDB views, the user can filter terms that are available in the "key". 

![Screen Shot 2022-09-08 at 11 36 48 am](https://user-images.githubusercontent.com/66472237/189035496-ca775215-930f-4540-bfb9-36fc60bcb976.png)

For reports tab, it uses [medic-client/reports_by_freetext](https://github.com/medic/cht-core/blob/814ed5cd488d783784959e60c4066a665319accb/shared-libs/search/src/generate-search-requests.js#L185) view. 
For contact tab, it uses [medic-client/contacts_by_freetext](https://github.com/medic/cht-core/blob/814ed5cd488d783784959e60c4066a665319accb/shared-libs/search/src/generate-search-requests.js#L185) view

CHT does a bit more logic with the words you type, you can see it in the links I pasted above.

**Comment by latin-panda** [comment]
[PR For CHT Docs](https://github.com/medic/cht-docs/pull/776)

**Comment by tatilepizs** [comment]
Thank you @latin-panda for the explanation. 

I was reviewing the different keys for the `death report` and the `undo death report` and if try searching for any of those key values it worked perfectly. There are places in the code where I see that it only uses `[0]` the first part, maybe that is why if I search for the report type it only works for the first word.

I tested this same thing in master and it is working exactly the same, so it is not something that changed with this redesign. I will move the ticket to **Ready to merge** because the change that was made for this ticket work perfectly.

For my test, these are the available keys for those two reports (`death report` and `undo death report`) in case anyone is interested:
<details>
<summary>Death Report</summary>

```
56c23c77-bd40-4911-a3db-62edfa695047	[ "1318848b-4c1f-428a-8aa1-c3fc3dc54169" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "27394" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "900" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "contact:e167db56-7e0a-4fc7-bf31-8b2e674decfa" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "content_type:xml" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "death_report" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "form:death_report" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "patient_age_in_days:27394" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "patient_age_in_months:900" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "patient_age_in_years:75" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "patient_display_name:person1" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "patient_name:person1" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "patient_uuid:1318848b-4c1f-428a-8aa1-c3fc3dc54169" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "person1" ]
56c23c77-bd40-4911-a3db-62edfa695047	[ "xml" ]
```

</details>

<details>
<summary>Undo Death Report</summary>

```
4d6414db-4bc7-481e-9627-30614b8260e0	[ "1318848b-4c1f-428a-8aa1-c3fc3dc54169" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "27394" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "70361" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "900" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "contact:e167db56-7e0a-4fc7-bf31-8b2e674decfa" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "content_type:xml" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "form:undo_death_report" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "patient_age_in_days:27394" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "patient_age_in_months:900" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "patient_age_in_years:75" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "patient_display_name:person1" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "patient_id:70361" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "patient_name:person1" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "patient_uuid:1318848b-4c1f-428a-8aa1-c3fc3dc54169" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "person1" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "undo_death_report" ]
4d6414db-4bc7-481e-9627-30614b8260e0	[ "xml" ]
```

</details>

**Comment by latin-panda** [comment]
Interesting 🤔 I think it has room for improvement, I'm going to follow up with CT and see if users has given feedback regarding search terms vs results.
I appreciate the question and extra information I learned more of the CHT depths, thanks @tatilepizs!
