### ISSUE TITLE
Browser compatability notice for some, block access for others

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7770]
**Describe the issue**
In #7448 we added a notice at login and on the about page if your browser was incompatible. However, logged users won't see the login screen, we set a year long cookie and logged users rarely go to the about page.  Further, with the release of 4.2, [we now can have users](https://github.com/medic/cht-core/issues/7770#issuecomment-1728466554) that should be fully blocked, regardless of if they're logged in or not.

**Describe the improvement you'd like**
We should:
* block all access for  Chrome <72 (to be verified)
* warn between 72 and 90

NB - out of scope for this ticket is any warnings about CHT Android (eg `0.9.x`) versions or Android versions  (eg `4.2`)

**Describe alternatives you've considered**
NA

**Comment by mrjones-plip** [comment]
Yeah - still should be done!

@n-orlowski - thoughts on the UX for this? Similar to the work you helped out with in [7448](https://github.com/medic/cht-core/issues/7448).  No rush, but if you wanted to throw some comps here, that'd help move things along!

**Comment by garethbowen** [comment]
Basic thoughts here...

- If you have a browser we know will not work we should not allow the user to log in, and if they're already logged in, not try and load the app. Instead show an error page with links to documentation about how to update your webview.
- If you have a browser that is not supported, we should show a warning with a link to the documentation above, but still allow the user to load the app because it might just work.
- For the first iteration I think we can put the documentation on the docs site. It doesn't need to be offline first because you have to be online to access the play store anyway.
- For the first iteration the warning can be as simple as a modal dialog on load. At some point we can do a full UX review and come up with something more user friendly.

**Comment by mrjones-plip** [comment]
> For the first iteration I think we can put the documentation on the docs site. It doesn't need to be offline first because you have to be online to access the play store anyway.

Agreed as long as we have a translatable msg, `Error - your device needs to be updated before it will work with CHT - see here for more information` (or what ever msging we defaulted to).  This way at least offline users know they need to do something likely out of their control in order to proceed

**Comment by mrjones-plip** [comment]
@michaelkohn  - calling this out per our call earlier today, per [Gareth's comment above](https://github.com/medic/cht-core/issues/7770#issuecomment-1685529921) (emphasis mine):

> If you have a browser we know will not work **we should not allow the user to log in**

So this ticket should handle that use case, as we hoped it would, which is great! However, noting that this is different than the title of the ticket "notice for logged in user".  

Given that the UX now for users who have incompatible browser just see a full screen spinner and will never even [see our new warning message](https://user-images.githubusercontent.com/13026820/182616822-3076446c-158f-4590-b9e3-7c01e6260bbd.png), this ticket means it's doing a lot more work! 

cc @latin-panda @Benmuiruri @n-orlowski

**Comment by mrjones-plip** [comment]
To be clear - we're seeing real world consequences of this ticket. In one national deployment, there were 100s of phones that were purchased which are running an old WebView version.  Many hours (days?) were lost because they thought the CHT Android app was broken:

https://github.com/medic/cht-core/assets/8253488/9f1e4915-f35a-4518-88dd-4c09f1c8db20

**Comment by n-orlowski** [comment]
The dreaded forever spinner 😵‍💫

Agreed for the MVP we can use a modal with a short description of why the error is happening and a clear CTA for the next immediate step

Something like:
**There was an error loading your app**
Please contact your administrator or supervisor and let them know to update your browser.

**Comment by mrjones-plip** [comment]
> **There was an error loading your app**
> Please contact your administrator or supervisor and let them know to update your browser.

This would totally be fine for an MVP!  However, we'll actually be stopping the error so we can fire the modal because we know for certain, they can not continue.  Even for MVP, this is more accurate maybe?

> **Your device needs an update**
> Please contact your administrator or supervisor to continue using this device.

This is different in that:
* We don't talk about errors (there aren't any really anyway!)
* We don't talk about the browser vs the APK - they just need an upate
* we explicitly tell them the only way forward is the update, they can't use the device until then.

thoughts?

**Comment by latin-panda** [comment]
@Benmuiruri, please collaborate with @michaelkohn @n-orlowski and involve QA from the start to design a UX solution for this. 

We have [a browser detector service](https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/browser-detector.service.ts) that uses the `Browser` library for similar things like this. You can see how we're using it and what `Browser` offers. It will give you access to the browser's info.

**Comment by Benmuiruri** [comment]
Hi @tatilepizs  I'd like to include your QA perspective while working on this task. I've started by exploring the work y'all did in #7448 .

Something I have noticed, is I don't see the "warning message" in the about page. But I see it in the Login page. 
1. I am spoofing the user agent in Chrome with `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36`

I see the warning message in the login page. 
![Screenshot 2023-12-06 at 11 54 56](https://github.com/medic/cht-core/assets/2597305/518500f0-d487-4e1c-94d7-bc53d62d7d46)

However, when I login and visit the login page, it shows that the browser is supported.
![Screenshot 2023-12-06 at 11 57 10](https://github.com/medic/cht-core/assets/2597305/1d1506ed-1d8f-4128-bcc3-dc0a68c53f53). 

Am I missing something?

**Comment by Benmuiruri** [comment]
@mrjones-plip I have been brainstorming how to implement this feature, this is what I have so far. 

1. I am thinking we can do a client-side check in app.component.ts ngOnInit where we call the browser-detector.service.ts. 
- If chrome version is < 72 we display a modal that blocks access until the browser has been updated 
- If chrome is version 72-90 we display a modal with a warning but allow the user to continue. 

(The modal approach I got it from [Gareth's comment](https://github.com/medic/cht-core/issues/7770#issuecomment-1685529921), I am not sure if that is what he meant  and whether that's the best UX. @n-orlowski thoughts on whether that is the expectation? )

2. Will that client-side check be sufficient or do we need a server side check ? My thoughts on server-side would be to have a middleware that examines the User-Agent header then set a flag or header to trigger a client-side warning (modal).

Let me know your thoughts on my approach. 

@m5r since you worked on #7448 I welcome any thoughts you may have on this approach.

**Comment by n-orlowski** [comment]
Yeah I think we were aligned on modal for MVP with messaging from [mrjones' comment](https://github.com/medic/cht-core/issues/7770#issuecomment-1730478936)

**Comment by m5r** [comment]
Running the check in the `app.component.ts ngOnInit` is a good start as that's where the app gets initialized. If you run into an issue where that's not early enough to catch what you need, you can move up higher the chain to `main.ts`

I don't think it will be enough to prevent the [forever spinner](https://github.com/medic/cht-core/issues/7770#issuecomment-1728466554) for users using chrome <74 though because the `main.js` script [can't be loaded by the browser](https://github.com/medic/cht-core/issues/8456#issuecomment-1677618103).  
Since the angular app code is responsible for redirecting the users to the login page, checking for browser support in the login page alone is not sufficient either. We would need to check for browser support before even loading the app code.

**Comment by Benmuiruri** [comment]
You were right @m5r  , the check being in `app.component.ts` or `main.ts` does not prevent the forever spinner. [A short video of my attempt](calendar.google.com/calendar/u/0/r/week?pli=1). Any suggestions on what I can try to prevent it ?

**Comment by Benmuiruri** [comment]
@mrjones-plip my bad. here is the right link to [Loom](https://www.loom.com/share/8b9c75db2c214e45b7861187249fb2af)

**Comment by Benmuiruri** [comment]
Hi @michaelkohn I'd like to bring you in on the discussion about the current scope for this issue that is to be fixed by #8744. 

According to this issue's description, we wanted to 

- block all access for Chrome <72 (to be verified)
- warn between 72 and 90

Warning users of version 72 and 90 is minor and you can see how that would look like in [this video](https://www.loom.com/share/8b9c75db2c214e45b7861187249fb2af)

Blocking all access for Chrome < 72 to prevent the forever spinner is currently a challenge as discussed in this other [PR](https://github.com/medic/cht-core/issues/8456#issuecomment-1677618103). 

 I talked to Jenni about it and she suggested probably the fix the forever spinner is we need to understand the error and code the fix in the [bootstrap](https://github.com/medic/cht-core/tree/master/webapp/src/js/bootstrapper). 
 
What are your thoughts on the ideal scope for #8744 do we include both fixes or focus on warning users between 72 and 90 ?

**Comment by m5r** [comment]
The bootstrapper is imported and used by `main.ts`: https://github.com/medic/cht-core/blob/master/webapp/src/ts/main.ts#L21, so it gets bundled in the `main.js` script that cannot be loaded by the browsers we want to block

As far as I know, the only place we can put code in to do things on the client before `main.js` is loaded is in a `<script>` tag inside the `<head>` of https://github.com/medic/cht-core/blob/master/webapp/src/ts/index.html

It's not pretty or fancy but that's the only thing I can come up with at the moment. I suggest bringing up the question in the #product-team slack channel

**Comment by michaelkohn** [comment]
> What are your thoughts on the ideal scope for https://github.com/medic/cht-core/pull/8744 do we include both fixes or focus on warning users between 72 and 90 ?

If we are pretty much already done with the "warn" modal (v72 -> v90), then we should just ship it and it's OK to split off < 72 into a different PR and/or issue.

> Blocking all access for Chrome < 72 to prevent the forever spinner is currently a challenge as discussed in this other https://github.com/medic/cht-core/issues/8456#issuecomment-1677618103.

From what I've gathered, you can be on Chrome < 72 (or even Safari) and NOT get the forever spinner. I've verified that I can access demo-cht.dev.medicmobile.org (v4.5.0) from my iPhone using Safari. I get the warning on the login screen but and am able to log in (and reload once logged in) with no issues. So the forever spinner only happens in some scenarios... is that correct? With that in mind... are there ways to anticipate/know when the forever spinner is going to happen (I'm assuming yes based on your comment about finding the error code and dealing with it in bootstrap)? 

**Consideration**

For logged-in users, this is only going to be an issue _once the updated version of the CHT has been fully downloaded and the update has been applied (by any of [these](https://forum.communityhealthtoolkit.org/t/what-is-the-difference-between-the-update-modal-about-reload-and-reloading-from-browser/2080))._ Is there a way to do some checks and/or notify _**before**_ the update is actually applied on the device?

**Consideration #2 (only if client side is not reliable)**

Are the Chrome versions in Telemetry reliable/usable? Could the upgrade process look at the most recent telemetry entry for all users and warn administrators if there are some with incompatible browsers?

**Comment by m5r** [comment]
> Could the (server side) upgrade process look at the most recent telemetry entry for all users and warn administrators if there are some with incompatible browsers?

There is [this issue](#8462) that allies have planned to work on that will help with this

**Comment by mrjones-plip** [comment]
@m5r - you linked to the issue we're on here - did you mean to link to another issue?

**Comment by mrjones-plip** [comment]
(sorry - clicked "close with comment" instead of "comment" :sweat_smile: )

**Comment by michaelkohn** [comment]
I think he meant this one https://github.com/medic/cht-core/issues/8462

**Comment by m5r** [comment]
Oops, yes that's the one @michaelkohn linked. Thanks!

**Comment by garethbowen** [comment]
@Benmuiruri Maybe I missed it... did you create a new issue for handling users with Chrome < 72?

**Comment by Benmuiruri** [comment]
@garethbowen Not yet. Also, since Mr Jones encountered forever spinner in [Chrome 74](https://github.com/medic/cht-core/issues/8456#issuecomment-1677618103). The [PR](https://github.com/medic/cht-core/pull/8744) I worked on will warning users with Chrome 75 - 90. 

Currently there is no separate open issue for blocking access in Chrome <= 74.

**Comment by garethbowen** [comment]
@Benmuiruri Ok. Can you please the new issue (or issues) to cover that so we don't lose track of it?

Also please update the title and description of _this_ issue to reflect what actually got done. The release notes get generated from the issue title so it's important it's clear.

**Comment by Benmuiruri** [comment]
New issue for blocking users with Chrome < 74 that leads to forever spinner opened #8793

**Comment by michaelkohn** [comment]
@Benmuiruri can you please update the first comment of this issue to articulate the final solution and parameters?

**Comment by Benmuiruri** [comment]
@michaelkohn by first comment do you mean the issue's description that was written by Mr Jones ?
