### ISSUE TITLE
Ensure all services are set up to automatically restart

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7884]
**What feature do you want to improve?**
Currently if api crashes it needs manual intervention to start up again.

**Describe the improvement you'd like**
Add a [restart policy](https://docs.docker.com/compose/compose-file/compose-file-v3/#restart_policy) so all services attempt to restart with appropriate settings. One thing to keep in mind is using an appropriate delay so that the log doesn't fill up the disk and so we don't overload other services.

**Describe alternatives you've considered**
Not having api crash as much, but bugs happen and we should gracefully recover when possible.

**Comment by garethbowen** [comment]
It's not clear if restart policy is used outside of docker swarm. We can use `restart:always` but that doesn't allow delays to spare the log file.

**Comment by garethbowen** [comment]
As I feared, `restart_policy` is ignored. However in testing `restart:always` it became clear that API and Sentinel handle this gracefully with a retry timeout in server checks, so if any couchdb node is unavailable they don't start up but also don't spam the logs.

**Comment by garethbowen** [comment]
AT instructions:

- install images linked [in the PR](https://github.com/medic/cht-core/pull/7888)
- check that when API or Sentinel crashes it comes back without issue

Crashing API and sentinel reliably can be difficult but one way to do it is to stop one of the couchdb nodes (as explained in [this issue](https://github.com/medic/cht-core/issues/7886), and then watch the logs. If you see something like `restarttest_api_1 exited with code 1` that `code 1` means API crashed, and you should see docker-compose attempt to restart it. If you then bring the couchdb node back up API should recover and start responding to requests again.

**Comment by mrjones-plip** [comment]
AT passes! 

---

I did have trouble testing this.  I once got API in a really good state where it was crashing a lot - restart worked well!  Otherwise I had mediocre success by restarting the container with:

`while true; do docker stop deleteme2_couchdb.2_1; echo "DOWN...sleeping for 30";sleep 30;docker start deleteme2_couchdb.2_1;echo "UP\! sleeping for 30";sleep 30; done`

And then checking restart counts with:

`docker logs deleteme2_api_1 2>&1 |egrep 'Starting API|Running server check'|tail -n5`
