### ISSUE TITLE
Update dependencies for 4.2.0

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7904]
Follow [the documentation](https://docs.communityhealthtoolkit.org/core/guides/update-dependencies/).

Due to the 4.0.0 release we can update more dependencies without a breaking change, specifically dependencies in docker images. Bump these dependencies (eg: Node 18) and update the docs with the additional steps.

Update `node-sass` -> `sass` to resolve this deprecation warning:

```
'node-sass' usage is deprecated and will be removed in a future major version. To opt-out of the deprecated behaviour and start using 'sass' uninstall 'node-sass'.
```

Update messageformat to resolve this deprecation warning:

```
WARN deprecated messageformat@2.3.0: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA.
```

NB the enketo-core major update has a [separate issue](https://github.com/medic/cht-core/issues/7599) with more details.

**Comment by latin-panda** [comment]
[Here](https://github.com/medic/cht-core/labels/Upgrade%20dependencies) is a full list of issues addressing upgrade of libraries

**Comment by latin-panda** [comment]
I've fixed the `node-sass` and the `messageformat` has its [own ticket](https://github.com/medic/cht-core/issues/7370).
 
@ngaruko, I reverted [this patch](https://github.com/medic/cht-core/commit/19501b5b4e45855f4706fd380770f1e02dd9db9d) since the new version of pouch has the fix. Can you please do a quick AT of [this ticket](https://github.com/medic/cht-core/issues/6626)? 🙏
 I saw you ATed it before. This is the [PR](https://github.com/medic/cht-core/pull/7972).  Thanks!

**Comment by latin-panda** [comment]
Hi @ngaruko, is this one still in "AT in Progress"?

**Comment by latin-panda** [comment]
Thanks @ngaruko.

This work is merged into the main branch. All other upgrades are tracked on [this list of issues.](https://github.com/medic/cht-core/labels/Upgrade%20dependencies)
