### ISSUE TITLE
create_user_for_contacts unit test flakes

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7980]
**Describe the issue**
A unit test fails occasionally: 
```
 1 failing

  1) create_user_for_contacts
       onMatch
         replaces user when 10 username collisions occur:

      AssertionError: expected 10 to equal 11
      + expected - actual

      -10
      +11
      
      at Context.<anonymous> (test/unit/transitions/create_user_for_contacts.js:307:53)
```
https://github.com/medic/cht-core/actions/runs/3683370354/jobs/6231870648

**Describe the improvement you'd like**
Investigate whether the unit test failing reveals a true problem in the code. Fix the problem or stabilize the unit test.

**Comment by garethbowen** [comment]
I think it's failing because the test is asserting that the number of unique usernames attempted is 11, but the usernames are generated with a random suffix so occasionally there will be a collision. The random suffix for this test is 5 digits (0 - 99999, or 100k options) and we're generating 10 usernames, so once every 10k executions you'd expect it to fail.

Some options for fixing it...

1. Change the test so it doesn't care about unique usernames. This will work, but we won't notice later if the random function starts returning the same random number. I think this is a bit risky.
2. Mock out the random function so we're only testing our code and not JavaScript random number generator. I think this is the correct approach. Ideally unit tests would only test the very smallest function, and we'd use integration tests to assert that each unit is wired together correctly. Currently these unit tests are somewhere between integration and unit tests which make them more complicated than needed, and cause issues like this one.
3. Make the code smarter so it checks for dupes and regenerates if one is found. This is overkill IMO because it's rare that this will occur and the code handles the dupe case just fine by retrying new combinations in another round.
4. Just live with it failing once a year or so. This sets a dangerous precedent - if each of our tests failed occasionally we'd never get a build out. We should deal with flaky tests with extreme prejudice!

My suggestion is we go with option 2.

@m5r It looks like you're the expert on this transition - what do you think?

**Comment by dianabarsan** [comment]
This has just failed for me (again), I think the failure rate is fairly high. 
My vote is to also go for 2.

**Comment by dianabarsan** [comment]
Another failure: https://github.com/medic/cht-core/actions/runs/4263568113/jobs/7420478557#step:11:18448
