### ISSUE TITLE
Training cards are appearing on top of privacy policies

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8131]
**Describe the bug**
I experienced this on first login with a user, where the instance had both an active training and a privacy policy enabled. 

**To Reproduce**
1. Enable privacy policies.
2. Add a training.
3. Login with a new user.
4. See training on top of privacy policy. 

**Expected behavior**
My guess is that trainings should appear _after_ the user has accepted the privacy policy. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/225690319-fb7ade52-6a72-46cf-9abf-c6e176047f10.png)

**Environment**
- Instance: local
- App: webapp
- Version: 4.2.0

**Comment by Elsbokk** [comment]
Hi, could I pick this up? Thanks!

**Comment by dianabarsan** [comment]
Hi @Elsbokk 
You are very welcome to pick this up! Please let us know if we can assist in any capacity. 
Many thanks for taking an interest!

**Comment by latin-panda** [comment]
Hi @Elsbokk, I found out yesterday that the Privacy Policy component uses the [StartupModalsService](https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/startup-modals.service.ts) to display modals after the policies are accepted. Just in case you haven't seen it before and that this service can help with the task 🙂

**Comment by Elsbokk** [comment]
Hi @latin-panda, I actually saw that last night! Unfortunately, I had to step away from the task for a bit due to an urgent personal matter, but now that I'm back I'm working to resolve it quickly. I've tried the simplest solution of simply treating the training cards in the same way that the startup modal service is being treated, and calling their initialization from the privacy policy component/check. This is actually working just fine, but I think that a more elegant solution would be to specifically use the startup modals service to make that call, as their behavior seems to be very similar.

**Comment by Elsbokk** [comment]
Hi @dianabarsan, I have opened [this pr](https://github.com/medic/cht-core/pull/8201), please take a look whenever it's convenient.

One of the only things that I would like to note is that because I'm using the startup modals service to handle training cards, I've made some small changes to the training cards initialization process so they'll fit in with the rest of the startup modals a little cleaner, visually. 

For reference, this would happen if a training was added before setup is completed:

![training-over-welcome](https://user-images.githubusercontent.com/25468153/233226507-f82c0f8a-47b7-4a13-94e6-991a9e764a53.png)

(to reproduce, add a training, include `"setup_complete": false` in your configuration's `base_settings.json`, then compile and upload your app settings.)

and this would happen if a training was added before a new user logs in:

![training-over-tour](https://user-images.githubusercontent.com/25468153/233226550-5fa2a314-5c80-4b6c-9979-77a088557f22.png)

(to reproduce, add a training, create a new user, and log in with that user. If you have uploaded any privacy policies, cancel the training when you log in with the new user, accept the privacy policy, then reload the page.)

I suppose that this isn't _technically_ incorrect behavior, but I think that being able to display them in sequence with the other startup modals is a little less visually overwhelming.

The fix in that PR adds a method to the training cards service which initializes the startup modals, and returns the "shown" modal to be used by the startup modals service (as per @latin-panda's suggestion). I've added more specific implementation details in the PR, but the result is that the training cards would be displayed after the privacy policy is accepted, in sequence with the startup modals.

**Comment by garethbowen** [comment]
@Elsbokk How are you getting on with this? Anything I can do to help?

**Comment by Elsbokk** [comment]
Hey @garethbowen, sorry I've been away from this, I haven't had access to my workspace for a bit. I should be able to get back on in the next day or two when things settle down, sync my fork, and wrap up with those tests. I'll keep you updated!

**Comment by Elsbokk** [comment]
Hey @garethbowen, even though it's taken _way_ longer than I expected, I'm finally able to return to this issue. Since there have been some major changes while I've been away, I've converted my PR to a draft while I update my fix to work with the latest version. I'll update this issue once that process is complete, and when I have some new unit/e2e tests written.

**Comment by Elsbokk** [comment]
The solution and unit tests in the linked PR have been updated, and I am currently updating my local setup in order to properly run my e2e tests.

In the meantime, seeing how @latin-panda has removed everything surrounding the startup modals in [`8190-remove-configuration-wizard`](https://github.com/medic/cht-core/pull/8194), does this mean that there are no current plans to introduce any other modals which might show up when a user logs in? Because if this is the case, then I could simplify my solution here quite a bit.

**Comment by latin-panda** [comment]
@Elsbokk, 

> are there no plans to introduce any other modals which might show up when a user logs in?

We have no plans to introduce multiple modals after login for the time being; it's not a recommended user experience because users may lose track, and going through various modals is tedious.

**Comment by garethbowen** [comment]
Bumping to 4.4.0 as we're almost ready to release 4.3.0 and this has more work needed yet.

**Comment by dianabarsan** [comment]
@Elsbokk are you still available and interested to work on this? Thanks!

**Comment by michaelkohn** [comment]
Bumping to 4.6.0

**Comment by dianabarsan** [comment]
Merged to `master`.
