### ISSUE TITLE
Upgrade Message in Clustered Mode Should Include CouchDB containers (couchdb.1, couchdb.2, etc) - for use by kubernetes upgrade service

### ISSUE THREAD

**Issue by henokgetachew** [medic/cht-core#8215]
**What feature do you want to improve?**

When using the CHT in a cluster, the upgrade message should include a list of the couchdb containers to be upgraded by the upgrade service. This is important when dealing with the [kubernetes upgrade service](https://github.com/medic/upgrade-service-kubernetes) since it can upgrade couchdb even in a cluster on different nodes.

**Describe the improvement you'd like**

The upgrade message includes a list of all couchdb containers (couchdb.1, couchdb.2, couchdb.3, etc) - possibly by querying couchdb for the cluster nodes.

**Describe alternatives you've considered**

Alternative is that the upgrade has to be done manually by editing the deployment manifest. This is not ideal. Especially, since the Kubernetes upgrade service already supports this.

**Comment by dianabarsan** [comment]
As discussed during the infra call, the current API payload sends a `cht-couchdb` container name. This can be used as a wildcard or search term for all k8s nodes, because all CouchDb nodes _should_ use the same image tag. 

Is the `cht-couchdb`  ok with you, @henokgetachew ? 
If so, we can close this, since `cht-core` doesn't need any changes, and all the work can be done in the [k8s upgrade service](https://github.com/medic/upgrade-service-kubernetes).
