### ISSUE TITLE
Send outbound tasks on a schedule

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8229]
**What feature do you want to improve?**
Outbound runs continuously by default, greedily pushing docs as soon as they are received. 

**Describe the improvement you'd like**
Add a configuration, like a cron, when outbound is pushed. 

**Describe alternatives you've considered**
Can a mediator or other interoperability layer serve as an outbound "scheduler"

**Additional context**
[forum thread](https://forum.communityhealthtoolkit.org/t/configure-cronjob-or-batch-processing-for-cht-outbound/2641/3)

**Comment by samuelimoisili** [comment]
# #8229 Design Document

## Context and Scope

The purpose of this document is to provide a concise overview of the implementation approach to for adding cron schedules to Outbound Pushes in Sentinel. Outbound Push enables configurers to trigger outbound REST requests based on the creation or editing of CouchDB documents. 

The scope of this document will be limited to outlining the technical implementation of the new outbound push functionality based on a cron schedule. It will cover aspects such as the integration with CouchDB, transitions, the configuration options for defining cron schedules, and any necessary modifications to the existing codebase.

The changes in the new system will be made in the following files following files: `sentinel/src/schedule/outbound.js` and `shared-libs/transitions/src/transitions/mark_for_outbound.js`.

The new feature request revolves around enhancing the existing outbound push functionality by introducing the ability to schedule outbound pushes based on a cron schedule. This means that “configurers” will be able to define specific time-based triggers for the transmission of data via REST requests. By implementing this feature, the system will provide users with greater flexibility and control over the automation of outbound data flows.

The design document will assume that the readers have a certain level of prior knowledge regarding the overall architecture of the system. However, it will also provide relevant links to more detailed information to ensure comprehensive understanding for those who require it.

## Goals and Non-Goals

**Goals:**

- Enable the system to send outbound pushes based on a cron schedule.
- Minimize the need for extensive code refactoring while implementing the new feature.
- Ensure that the system does not require any persistent storage in the database for the outbound push functionality.

**Non-goals:**

- Introduction of significant code refactoring: The goal is to introduce the new feature with minimal changes to the existing codebase. While some modifications may be necessary, the intention is to avoid extensive refactoring that could introduce complexity or delays.
- Database persistence for outbound push metadata: The system does not require persisting any outbound push metadata in the database. The focus is on triggering REST requests based on the content of CouchDB documents without the need for additional storage or data persistence.

## Design

My design for the outbound push feature has been heavily inspired by the message shared by @jkuester.

The proposed solution for setting outbound pushes functions as follows: Initially, upon creation, all outbound pushes that are not yet due are added to the queue. Subsequently, the queue is checked every 5 minutes to determine if the outbound document is ready to be sent.

To implement this solution, a new property called `cron` is added to the outbound configuration object. When a document is created or updated, the `mark_for_outbound` transition is triggered. This transition verifies if a `cron` field exists in the configuration. If a cron field is present, it checks if the document is due for push. If it is ready, the new document is pushed. If it is not yet ready for push, the document is added to the outbound queue. If the `cron` field isn’t present, then it goes ahead with the previous flow.

When the worker responsible for the outbound push executes, it checks if the task it is working on is ready to be pushed based on the configuration's `cron` field. If the task is ready, the outbound push is performed. If it is not ready for push, the task remains in the queue while other tasks are processed.

To aid in understanding the workflow, a poorly made system context diagram is provided below:

![Implementation flow](https://github.com/medic/cht-core/assets/45266875/7be6c6ba-d744-4048-baa3-4d2f9257b987)

The diagram illustrates the various components involved and their interactions in the outbound push workflow. It provides a visual representation of how documents are processed, queued, and pushed based on the defined cron schedule.

Overall, this proposed design aims to be backward compatible, and ensure efficient processing of documents based on the specified cron configuration.

### APIs

Here is the API for setting the `cron` rule in the outbound object. I considered two name options: `schedule` and `cron.`, I chose `cron` because it offers a more expressive and descriptive representation of the functionality (I’m not hell bent on changes and open to better names).

```jsx
interface Outbound {
	relevant_to: string,
  destination: Destination,
  cron: string, // CRON rule "* * * * *"
	mapping: Mapping
}
```

### Code and Pseudo code

Here’s the code implementation:

```jsx
/* sentinel/src/schedule/outbound.js */

// new
const dueWithin = (cron, frame = 0) => {
  const currentTime = Date.now();
	const dueTime = later.schedule(later.parse.cron(cron)).next().getTime();
  const upperBoundDueTime = dueTime + frame;
  const lowerBoundDueTime = dueTime - frame;
  return currentTime >= lowerBoundDueTime && currentTime <= upperBoundDueTime;
};

// extracted and augmented
const buildPushes = (tasks, configuredPushes) => {
  const pushes = tasks.reduce((acc, {task, doc, info}) => {
    const pushesForDoc =
            getConfigurationsToPush(configuredPushes, task)
              .map(([key, config]) => ({task, doc, info, config, key}))
								// new 
              .filter(push => !config.cron || isWithinTimeFrame(config.cron, FIVE_MINUTES));

    return acc.concat(pushesForDoc);
  }, []);

  return pushes;
};

const batch = (configuredPushes, startKey) => {
  let nextKey;
  return queuedTasks(startKey)
    .then(({ validTasks = [], invalidTasks = [], lastDocId } = {}) => {
      nextKey = lastDocId;
      if (invalidTasks.length) {
        return removeInvalidTasks(invalidTasks).then(() => validTasks);
      }

      return validTasks;
    })
    .then(validTasks => attachInfoDocs(validTasks))
			// new
    .then(validTasks => buildPushes(validTasks, configuredPushes))
    .then(pushes => {
			/**
				Extracted logic to `buildPushes`
			*/

      // Attempts each push one by one. Written to be simple not efficient.
      // There are lots of things we could do to make this faster / less fragile,
      // such as scoping pushes by domain, as well as writing out successes before
      // all pushes are complete
      // For now we presume we aren't going to get much traffic against this and
      // will probably only be doing one push per schedule call
      return pushes.reduce(
        (p, {task, doc, info, config, key}) => p.then(() => singlePush(task, doc, info, config, key)),
        Promise.resolve()
      );
    })
    .then(() => nextKey && batch(configuredPushes, nextKey));
};
```

```jsx
/* shared-libs/transitions/src/transitions/mark_for_outbound.js */

for (const [config, configKey] of relevantConfigs) {
		// new
    if (config.cron && !isWithinTimeFrame(config.cron, FIVE_MINUTES)) {
      failedKeys.push(configKey);
      continue;
    }
		// end new

    p = p.then(() => outbound.send(config, configKey, change.doc, change.info))
      .then(sent => {
        if (sent) {
          // Successfully sent, outbound.send wrote to the infodoc

          return db.sentinel.put(change.info);
        }
      })
      .catch(() => {
        // First realtime attempt failed, queue for later
        failedKeys.push(configKey);
      });
 }
```

## Alternatives Considered

The alternative implementations uses the same logic as stated above the only difference is where the time frame check is happening: 

The first alternative includes the check to determine if a document is within the time constraint inside the reduce function within the build function. This approach is arguably more efficient, particularly when dealing with a large number of documents in the queue. It avoids the need to iterate through the documents twice: once for building the push and then again for filtering the push.

By incorporating the time constraint check directly within the reduce function, the push is constructed while simultaneously filtering out any documents that do not meet the specified time criteria. This approach eliminates the need for a separate filtering step after the push is built, reducing unnecessary iterations and potentially improving performance.

Especially when dealing with a substantial number of documents in the queue, this approach proves advantageous as it avoids the additional computational overhead of iterating through the queue twice. By performing the check within the reduce function during the build process, the number of iterations is minimised, resulting in more efficient processing.

Considering the specific requirements and constraints of the system, it is essential to evaluate the trade-off between performance and code complexity when choosing between these alternatives. Selecting the most appropriate approach will depend on factors such as the expected size of the document queue, the frequency of operations, and the need for optimisation in terms of processing time and resource utilisation.

```jsx
/* sentinel/src/schedule/outbound.js */

const isWithinTimeFrame = (cron, frame = 0) => {
  const currentTime = Date.now();
  const dueTime = later.schedule(later.parse.cron(cron)).next().getTime();
  const upperBoundDueTime = dueTime + frame;
  const lowerBoundDueTime = dueTime - frame;
  return currentTime >= lowerBoundDueTime && currentTime <= upperBoundDueTime;
};

// extracted and augumented
const buildPushes = (tasks, configuredPushes) => {
  const pushes = tasks.reduce((acc, {task, doc, info}) => {
    const pushesForDoc =
            getConfigurationsToPush(configuredPushes, task)
              .reduce((acc, [key, config]) => {
									// checking for the the time frame in the reduce function
                if (!config.cron || isWithinTimeFrame(config.cron, FIVE_MINUTES)) {
                  acc.push(({task, doc, info, config, key}));
                }

                return acc;
              }, []);

    return acc.concat(pushesForDoc);
  }, []);

  return pushes;
};

const batch = (configuredPushes, startKey) => {
  let nextKey;
  return queuedTasks(startKey)
    .then(({ validTasks = [], invalidTasks = [], lastDocId } = {}) => {
      nextKey = lastDocId;
      if (invalidTasks.length) {
        return removeInvalidTasks(invalidTasks).then(() => validTasks);
      }

      return validTasks;
    })
    .then(validTasks => attachInfoDocs(validTasks))
    .then(validTasks => buildPushes(validTasks, configuredPushes))
    .then(pushes => {
      // Attempts each push one by one. Written to be simple not efficient.
      // There are lots of things we could do to make this faster / less fragile,
      // such as scoping pushes by domain, as well as writing out successes before
      // all pushes are complete
      // For now we presume we aren't going to get much traffic against this and
      // will probably only be doing one push per schedule call
      return pushes.reduce(
        (p, {task, doc, info, config, key}) => p.then(() => singlePush(task, doc, info, config, key)),
        Promise.resolve()
      );
    })
    .then(() => nextKey && batch(configuredPushes, nextKey));
};
```

The second approach is the inverse of the first alternative. In this approach, the filtering is performed after the pushes have been built. One could argue that this approach prioritises readability at the expense of performance.

This alternative focuses on constructing the pushes first, without any filtering applied during the building process. Once all the pushes have been generated, a separate step is taken to filter out the desired results. Although this approach may enhance code readability, it may potentially introduce performance overhead due to the need for additional filtering operations after the pushes have already been created.

By deferring the filtering step until after the pushes are built, the code logic may appear more straightforward and intuitive to developers. However, it is crucial to carefully consider the potential impact on performance, especially when dealing with large datasets or time-sensitive operations.

Ultimately, the choice between these approaches should consider the trade-off between code readability and performance efficiency, based on the specific requirements and constraints of the system.

```jsx
/* sentinel/src/schedule/outbound.js */

// new
const isWithinTimeFrame = (cron, frame = 0) => {
  const currentTime = Date.now();
	const dueTime = later.schedule(later.parse.cron(cron)).next().getTime();
  const upperBoundDueTime = dueTime + frame;
  const lowerBoundDueTime = dueTime - frame;
  return currentTime >= lowerBoundDueTime && currentTime <= upperBoundDueTime;
};

// new
const filterDuePushes = pushes => 
  pushes.filter(({ config }) => 
    !config.cron || isWithinTimeFrame(config.cron, FIVE_MINUTES) 
  );

// extracted
const buildPushes = (tasks, configuredPushes) => {
  const pushes = tasks.reduce((acc, {task, doc, info}) => {
    const pushesForDoc =
            getConfigurationsToPush(configuredPushes, task)
              .map(([key, config]) => ({task, doc, info, config, key}));
    return acc.concat(pushesForDoc);
  }, []);

  return pushes;
};

const batch = (configuredPushes, startKey) => {
  let nextKey;
  return queuedTasks(startKey)
    .then(({ validTasks = [], invalidTasks = [], lastDocId } = {}) => {
      nextKey = lastDocId;
      if (invalidTasks.length) {
        return removeInvalidTasks(invalidTasks).then(() => validTasks);
      }

      return validTasks;
    })
    .then(validTasks => attachInfoDocs(validTasks))
			// new
    .then(validTasks => buildPushes(validTasks, configuredPushes))
    .then(pushes => filterDuePushes(pushes))
    .then(pushes => {
			/**
				Extracted logic to `buildPushes`
			*/

      // Attempts each push one by one. Written to be simple not efficient.
      // There are lots of things we could do to make this faster / less fragile,
      // such as scoping pushes by domain, as well as writing out successes before
      // all pushes are complete
      // For now we presume we aren't going to get much traffic against this and
      // will probably only be doing one push per schedule call
      return pushes.reduce(
        (p, {task, doc, info, config, key}) => p.then(() => singlePush(task, doc, info, config, key)),
        Promise.resolve()
      );
    })
    .then(() => nextKey && batch(configuredPushes, nextKey));
};
```

## Cross Cutting Concerns

1. Handling Invalid Cron Rules:
`later.js` does not throw an error for invalid cron types and instead returns the current time as the next schedule. Should I address this?
2. Sharing the `isWithinTimeFrame` Function:
The shared function `isWithinTimeFrame` used in both `shared-libs/transitions/src/transitions/mark_for_outbound.js` and `sentinel/src/schedule/outbound.js` raises a question of code organization. Where do I put this function?

**Comment by samuelimoisili** [comment]
@jkuester @njogz @dianabarsan Can you please review the proposed solution? Thanks.

**Comment by jkuester** [comment]
Very helpful write-up! Thanks @samuelimoisili!  Here are a couple additional thoughts I had:

- I can't believe I am saying this (been listening to @craig-landry too much...) :laughing: but I would lean towards readable/maintainable code code in this case instead of optimizing for performance.  Looking at the `cht_outbound_push_backlog_count` data out on https://allies-monitoring-alerting.dev.medicmobile.org/ it is clear that that normally the max backlog count is "hundreds" and, if there is a problem, it can jump into the "thousands".  But, it is never hitting "tens of thousands" or higher.  Certainly this `cron` change will increase the size of the backlog, but I still doubt the queue performance will be the primary bottleneck to worry about here.
- I like the `cron` name for the config property! I think it makes  it very clear what kind of config is expected there (and basically just follows the naming pattern from [later.js](https://bunkat.github.io/later/parsers.html#cron)).

**Comment by samuelimoisili** [comment]
Do anyone have any suggestions on the cross cutting concerns? 

> Handling Invalid Cron Rules:
later.js does not throw an error for invalid cron types and instead returns the current time as the next schedule. Should I address this?
Sharing the isWithinTimeFrame Function:
The shared function isWithinTimeFrame used in both shared-libs/transitions/src/transitions/mark_for_outbound.js and sentinel/src/schedule/outbound.js raises a question of code organization. Where do I put this function?

**Comment by dianabarsan** [comment]
Thanks for sharing the design doc @samuelimoisili 
I would go as far as iterating over `configuredPushes` in `outbound.js`, and filtering the ones that should not be sent in the timeframe directly, that way will do the interval calculation once per config, instead of once per doc, and keep all filtering upfront. Wo do have this information upfront right? I also think this affects readability and complexity the least. Would that work?

**Comment by jkuester** [comment]
- `#1` - If we can reliably check for an invalid cron rule (maybe just seeing if later.js returns the current time???) then I would say the most helpful thing to do would be to add validation to the `init` function of the `mark_for_outbound` transition and fail the init if any of the `cron` configs are invalid.  Otherwise it could be really confusing for admins to try and debug why their outbound config is not working like expected....
- `#2` - It might not be ideal, but the `transitions` shared-lib is already exporting several shared utilities besides just the transitions.  I would lean towards coding `isWithinTimeFrame` somewhere in the `transitions` shared-lib and then exporting it so Sentinel has access....

**Comment by samuelimoisili** [comment]
@dianabarsan 
> Wo do have this information upfront right? I also think this affects readability and complexity the least. Would that work?

Yes, I think it would work. I'll share a sample implementation once I get it to work.

**Comment by samuelimoisili** [comment]
@dianabarsan Is this what you mean? 

```
const execute = () => {
  const configuredPushes = configService.get(CONFIGURED_PUSHES) || {};
  const dueConfiguredPushes = Object.entries(configuredPushes)
    .reduce((configs, [key, config]) => {
      if (!config.cron || isWithinTimeFrame(config.cron, FIVE_MINUTES)) {
        configs[key] = config;
      }

      return configs;
    }, {});

  if (!Object.keys(dueConfiguredPushes).length) {
    return Promise.resolve();
  }

  return batch(dueConfiguredPushes);
};
```

**Comment by dianabarsan** [comment]
@samuelimoisili 
Yea, and then this becomes the only change you need to make, right?

**Comment by rmayore** [comment]
Nice work  @dianabarsan @samuelimoisili we very much are interested in the scheduling feature.

Just some more questions:

1. Can the feature be improved to set the batch size? Some clients have insane rate limits. In some of our external integrations you cannot send a request if another one is still in flight, which means we can't use the Outbound feature as it is. Batch sizes to be a low as 1.

2. Can we have a way to control the retry period? I.e if the last 5 requests failed with code 500 there's no need to continue barrelling the receiving client with every queued push every 5 minutes.

**Comment by job-isabai** [comment]
I would like to add an additional request on this ticket: 
When the schedulers' conditions are met, can we send data records in bulk as a single payload compared to one outbound payload per record?

**Comment by dianabarsan** [comment]
Merged to `master`

**Comment by rmayore** [comment]
🎉
