### ISSUE TITLE
Research increasing pbkdf2 iterations

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8338]
**Describe the issue**
Best practices for hashing passwords is to use the highest number of iterations possible, with out impacting server performance (too much ; ).  Currently our `iterations` is [set to](https://github.com/medic/cht-core/blob/0c7399770fdcb94dbbc1764f25e3141e6b79b5b9/shared-libs/settings/src/index.js#L139) `10`.  This is considered very low, [it looks like](https://docs.couchdb.org/en/stable/config/auth.html#chttpd_auth/iterations) CouchDB default is 10k and minimum is 100.

**Describe the improvement you'd like**
Increase the  `iterations` to the highest number reasonable for the [server specs we set](https://docs.communityhealthtoolkit.org/apps/guides/hosting/requirements/).

**Describe alternatives you've considered**
NA

**Comment by fardarter** [comment]
Would bcrypt not be a better option in general?

**Comment by garethbowen** [comment]
@fardarter Somewhat, yes. pbkdf2 with high iterations should be good enough though.

We hand authentication off to couchdb rather than implementing it ourselves and the configuration option to change [hash algorithms](https://docs.couchdb.org/en/stable/config/auth.html#chttpd_auth/hash_algorithms) was only added in v3.3.0. So it's not possible currently. We should evaluate this after #6289 lands.

**Comment by garethbowen** [comment]
Bumping to 4.4.0 as we're almost ready to release 4.3.0 and this has more work needed yet.

**Comment by fardarter** [comment]
See: [Public Comments on SP 800-132, Recommendation for Password-Based Key Derivation: Part 1: Storage 
Applications](https://csrc.nist.gov/csrc/media/Projects/crypto-publication-review-project/documents/initial-comments/sp800-132-initial-public-comments-2023.pdf) via : https://docs.python.org/3/library/hashlib.html#key-derivation

Looks like recommended min for `sha1` is 1300000 iterations.

**Comment by garethbowen** [comment]
One significant downside to increasing this number is it will seriously impact anywhere that uses a lot of basic auth, which at the moment is api, sentinel, and cht-conf in particular. What this means is all of these will need to be changed to use session based auth which is not a trivial amount of work.

**Comment by fardarter** [comment]
@garethbowen This seems like a fairly critical thing to address, though?

**Comment by garethbowen** [comment]
> This seems like a fairly critical thing to address, though?

Definitely.

**Comment by garethbowen** [comment]
Yes the load will be on the server, and the iterations need to be increased until it's a noticeable load. Taking cht-conf as an example, we send hundreds of basic auth requests to update the config. Each of these would incur significantly higher load on the server which would make cht-conf much slower if done serially, and risks DOSing the server if done in parallel.

It's the same with the sentinel backlog where we make a range of requests for every doc change using basic auth.

So the load is on the couchdb server. To avoid this the client needs to be updated to log in once and use the session cookie for future requests. Each change is not particularly hard but it will be an issue in lots of places.

**Comment by fardarter** [comment]
@mrjones-plip The purpose of the higher iteration is to make it take longer to check the password value. It's so that it's expensive and time consuming to crack the passwords in the DB if it is leaked. 

I didn't realise that session authentication wasn't being used for the services, but the idea there is that once you acquire the token you are no longer having to run the expensive check.

At the NIST recommended level you'd be placing about a second's worth of delay on every request even if the server stayed up.

Moving to session auth would be the only viable way of using a high iteration value.

**Comment by mrjones-plip** [comment]
Ah ha!  Yes, that makes a lot of sense.  Thanks you two  for taking a sec to walk me through it.

**Comment by fardarter** [comment]
> Ah ha! Yes, that makes a lot of sense. Thanks you two for taking a sec to walk me through it.

Nice resource: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#work-factors

**Comment by garethbowen** [comment]
> Am I correct in saying at present only the admin password needs to be low iterations for perf?

Usually that's the case. You _could_ create different users with permissions and use those in cht-conf for example, and this would be best practice instead of everyone sharing a single admin user, but out of the box there's a single admin that's used in api, sentinel, and cht-conf.

> assuming I'm pre-computing the admin string

Do you mean, once the admin has been created? Yes that would be a good workaround - create the admin with low iterations, then increase the iterations in couch and create all the other users. The downside is the most important account is the least secure, but at least the bulk of users have strong hashing.

**Comment by fardarter** [comment]
@garethbowen 

> Usually that's the case. You could create different users with permissions and use those in cht-conf for example, and this would be best practice instead of everyone sharing a single admin user, but out of the box there's a single admin that's used in api, sentinel, and cht-conf.

We are doing that, but I imagine that doesn't help with the basic auth issue?

>  Do you mean, once the admin has been created?

I'm precomputing the hash.

> Yes that would be a good workaround - create the admin with low iterations, then increase the iterations in couch and create all the other users. The downside is the most important account is the least secure, but at least the bulk of users have strong hashing.

I don't seem to have an option on the core account. At least there I can guarantee a strong passphrase.

**Comment by garethbowen** [comment]
> I imagine that doesn't help with the basic auth issue?

You're right that it's not a workaround for the basic auth issue. If you had admin users that only accessed couchdb through webapps (CHT, app management, or fauxton) then you could increase their iterations because they're already using sessions once they're logged in. But most of the admin use cases are probably automation (cht-conf, api, sentinel) so this doesn't apply.

> Could you elaborate on the best practice a little?

The best practice would be for every human or script to use a different admin login. In practice this may be difficult or impossible  in some cases but should be done everywhere you can. The advantage is being able to revoke credentials which may have leaked without impacting other services, and also for better logging so you can see which script is doing what.

**Comment by fardarter** [comment]
> The best practice would be for every human or script to use a different admin login.

This is what we're doing with humans and also some of our connecting services. Every script is a bit far for us rn.

**Comment by dianabarsan** [comment]
Discussing with @garethbowen , before increasing default iterations, we need to update authentication in some auxiliary services. Bumping this from the 4.5.0 until we've resolved clients using cookies instead of basic auth.

**Comment by garethbowen** [comment]
We're still working on rolling out cookie auth everywhere, so moving this to the next release.

**Comment by dianabarsan** [comment]
Two commits were pushed that added a new PouchDb plugin that changes the behavior of the PouchDb http adapter, making it use session authentication instead of basic authentication, and one that makes e2e test requests to use session authentication as well. 

We still use `request-promise-native` to interact with CouchDb in several places in API and Sentinel, due to limitations of PouchDb APIs. This also needs updating to favor session authentication instead of basic auth. 

I'm proposing to make a shared library that wraps `request-promise-native` to load requests with session cookies, similar to [how we handle this in e2e tests](https://github.com/medic/cht-core/blob/master/tests/utils/index.js#L128-L196). 
This potentially opens up the possibility of swapping `request-promise-native` to `node-fetch` later on.

**Comment by fardarter** [comment]
Hi @dianabarsan, I have a PR consolidating `request-promise-native` coming close to being merged (@garethbowen to confirm). That might suit your purposes?

**Comment by garethbowen** [comment]
Moved to 4.8.0 so as not to hold up the release.

**Comment by mrjones-plip** [comment]
Moved to 4.9.0 so as not to hold up the release.

**Comment by dianabarsan** [comment]
I agree that cashing can be our ticket out of making all the rest of the cascade of changes. If this works, I think no additional changes are required.

**Comment by latin-panda** [comment]
Moving it to 4.16

**Comment by garethbowen** [comment]
With #9303 merged this is now done by default. We should test that this is the case by...

1. Timing how long it takes to log in for 4.15.0 and compare with main - main should be noticeably longer because the hashing cost is greater
2. Timing how long it takes to log in on main for the first time vs the second time in quick succession - the caching in couchdb should make the second login noticeably faster. If this isn't the case then we need to finish off the basic auth -> cookie auth transition (eg: #8737 ) before releasing 4.16.0.

**Comment by dianabarsan** [comment]
Tested with: 

| CouchDb v. | Nb. iterations | 1st request | 2nd request | 10 requests |
|--------|--------|--------|--------|--------|
| 3.3.3 | Default (10000) | 42ms | 4ms | 19ms |
| 3.3.3 | 100000 | 650ms | 650ms | 6700ms |
| 3.4.2 | Default (600000) | 141ms | 3ms | 8ms | 

It seems that even Couch 3.4.2 indeed comes with 600.000 iterations by default. 
But besides being SOOO MUCH faster than Couch 3.3.3, the caching also works to reduce time for subsequent requests. 

I also tried 100 requests with waits in between

| CouchDb v. | Nb. iterations | 100 x 50ms | 100 x 500ms | 
|--------|--------|--------|-------- |
| 3.3.3 | Default (10000) | 610ms | 635ms |
| 3.4.2 | Default (600000) | 552ms | 492ms | 

I believe we can close this issue as-is. 

Just to note, existent accounts will need to change their password to get the new hashes with iterations++.

**Comment by garethbowen** [comment]
> Just to note, existent accounts will need to change their password to get the new hashes with iterations++.

I thought they just had to log in again? (not that people log in often)

**Comment by dianabarsan** [comment]
Yes, unfortunately re-generating the password is required: 

User created from admin app in 4.12:
```
{
  "_id": "org.couchdb.user:user1",
  "_rev": "1-7d43ea7062ae1ecccd8754e7a63f3388",
  "name": "user1",
  "type": "user",
  "roles": [
    "program_officer",
    "mm-online"
  ],
  "password_scheme": "pbkdf2",
  "iterations": 10,
  "derived_key": "0b9d0dcdd25ffc8a7058bafa85f1b5b6485ef0f0",
  "salt": "9bba2dc653fd8819a57e310f68c9a7a9"
}
```

Same user after logging in again post upgrade to `master`:
```
{
  "_id": "org.couchdb.user:user1",
  "_rev": "1-7d43ea7062ae1ecccd8754e7a63f3388",
  "name": "user1",
  "type": "user",
  "roles": [
    "program_officer",
    "mm-online"
  ],
  "password_scheme": "pbkdf2",
  "iterations": 10,
  "derived_key": "0b9d0dcdd25ffc8a7058bafa85f1b5b6485ef0f0",
  "salt": "9bba2dc653fd8819a57e310f68c9a7a9"
}
```

Same user after changing their password: 
```
{
  "_id": "org.couchdb.user:user1",
  "_rev": "2-0248e6601e539f9e2a09847e07704c28",
  "password_scheme": "pbkdf2",
  "pbkdf2_prf": "sha256",
  "salt": "0355a6369f39136d7301b2654009b3d4",
  "iterations": 600000,
  "derived_key": "6f157c340805a4e30871cff5223650d5040e7e492fad18e64e176a00715609b8",
  "name": "user1",
  "type": "user",
  "roles": [
    "program_officer",
    "mm-online"
  ],
}
```

New user: 
```
{
  "_id": "org.couchdb.user:user2",
  "_rev": "1-ffd2b92a95603608786fe90ffb5073bf",
  "password_scheme": "pbkdf2",
  "pbkdf2_prf": "sha256",
  "salt": "6caf5c528987fdf1cb9d6694313c6209",
  "iterations": 600000,
  "derived_key": "d0452dc274173609de1f6e92ed94f5bfe81a2f4f913b71f86568b17b7848a8f8",
  "name": "user2",
  "type": "user",
  "roles": [
    "program_officer",
    "mm-online"
  ],
}
```

**Comment by garethbowen** [comment]
Yes I remembered something from the couchdb release that they didn't want to change it too aggressively because it would mean you couldn't roll back to a previous version of couchdb because it wouldn't understand the new scheme. I suspect in 3.5.x they'll get more aggressive about rolling it out. This is enough for now - at least new users are well protected, and admins can opt in to password resets if they want to roll this change out more widely, and we'll probably get the rest for free in a year when the next couchdb comes out. Thanks for checking!

**Comment by dianabarsan** [comment]
It does seem like the new setting is automatically applied to couchdb admin users. The session cookie becomes invalid after upgrade. Does not affect regular users.

**Comment by dianabarsan** [comment]
Oh, nvm, it was because of my credentials couch volume, that had another user `medic` besides `admin`. 
![Image](https://github.com/user-attachments/assets/5b9b155b-ef1f-478e-84a0-686368572a69)

After cleaning up my Couch admins, this no longer happened, so even the admin remains with the old iteration count.
