### ISSUE TITLE
Add Enketo telemetry events for contact forms

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#8433]
**What feature do you want to improve?**
[Telemetry events](https://docs.communityhealthtoolkit.org/apps/guides/performance/telemetry/) with the format `enketo:*` are recorded when users complete app forms or training forms but are not recorded for contact forms.

**Describe the improvement you'd like**
We are investigating a performance problem related to slow save performance for a contact form. It'd be great if there was telemetry data for contact forms.

**Describe alternatives you've considered**
Shrug

**Additional context**
https://github.com/medic/config-nssd/issues/360#issuecomment-1664178996

I just set breakpoints in telemetry-service on latest cht-core master (~4.3) and confirmed that no telemetry event is created when rendering a contact form by clicking the "+" which opens a health_center contact form. I expected to see a `enketo:*:render` event recorded.

**Comment by latin-panda** [comment]
@michaelkohn We found that there are [telemetry fields ](https://docs.communityhealthtoolkit.org/apps/guides/performance/telemetry/) for when loading report forms inside a contact:`enketo:contacts:<form>:add:<component>`. 

This work is about adding telemetry to the contact forms. What do you think if we prefix it like `enketo:contact-form:<form>:<action>:<component>`? To not mix it with the metrics for the contact's report form

cc: @Benmuiruri to continue with the follow up in the topic :)

**Comment by michaelkohn** [comment]
Couple of questions.... I generally see these prefixes on enketo related telemetry records:

`enketo:contacts:*`
`enketo:reports:*`
`enketo:tasks:*`

I always thought that the second section of that (contacts vs. reports vs. tasks) related to which tab the activity occurred on.  So to stay consistent with that, I would have expected the contact forms to follow that paradigm. Even if not, I don't really think we'd need to differentiate the prefix for contact-specific forms since the name of the contact form will clearly identify what it is `enketo:contacts:clinic_create:add:render` (for example). 
 
Having said that... it also makes me wonder how contact forms will be treated in telemetry since we typically have two different forms* for each contact type....  [one for create / one for edit](https://docs.communityhealthtoolkit.org/apps/reference/forms/contact/). Would the `clinic-create` form only ever have an enketo `add` record and the `clinic-edit` form always just be an enketo `edit` record? 

_* It's not entirely clear to me if it is required to have a different edit form or just common / possible._

**Comment by latin-panda** [comment]
> So to stay consistent with that, I would have expected the contact forms to follow that paradigm.

This was my first thought yesterday. So then, the way we tell apart from contact forms and contact's reports forms is by the form name: `enketo:contacts:<form>:<action>:<component>` Is that okay? 

> it also makes me wonder how contact forms will be treated in telemetry since we typically have two different forms

We need to debug but I think the form name already has a suffix for `edit` and `create`, otherwise we just append it to the form name.  Like this: `enketo:contacts[_edit|_create]:<form>:<action>:<component>` but open to suggestions

**Comment by michaelkohn** [comment]
> the way we tell apart from contact forms and contact's reports forms is by the form name: `enketo:contacts:<form>:<action>:<component>` 
Is that okay?

Yes. So if you had a contact form called `clinic_create`, the telemetry record for creating a new clinic would look like `enketo:contacts:clinic_create:add:<component>`.

> We need to debug but I think the form name already has a suffix for edit and create, otherwise we just append it to the form name. Like this: enketo:contacts[_edit|_create]:<form>:<action>:<component> but open to suggestions

The convention that most projects use (as well as the [default config](https://github.com/medic/cht-core/tree/master/config/default/forms/contact)) is to have a separate create and edit form and the name of the form should be indicative. I would suggest just taking the form name itself, no need for additional suffix. 

Regarding the telemetry docs created  I assume the `clinic_create` form would only ever have "**add**" (`enketo:contacts:clinic_create:add:<component>`) and `clinic_edit`  would only ever have "**edit**" (`enketo:contacts:clinic_edit:edit:<component>`)

**Comment by Benmuiruri** [comment]
Hi @michaelkohn , after the discussion with Jenni, did we agree to record the event as `enketo:contacts:${this.telemetryData.form}:${this.telemetryData.action}:render` ?

**Comment by latin-panda** [comment]
@Benmuiruri yes, please use that format. Thanks for confirming

**Comment by garethbowen** [comment]
@Benmuiruri I've put this in 4.5.0 as it's been merged :tada: 

Before we close the issue can you please confirm that the docs site page is correct? This page specifically: https://docs.communityhealthtoolkit.org/apps/guides/performance/telemetry/#performance-data

**Comment by Benmuiruri** [comment]
Hi @garethbowen , yes that is the correct docs site page which I have updated in this [PR](https://github.com/medic/cht-docs/pull/1228). Just waiting for the review on that.

**Comment by Benmuiruri** [comment]
This has been completed by #8676
