### ISSUE TITLE
Hide forms that the user does not have access to from the FAB menu

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8588]
**What feature do you want to improve?**
We recently added a feature that will prevent a user from opening forms, based on a permissions property in the form context. 
However, these forms still show up in the FAB selection menu. 

**Describe the improvement you'd like**
Hide disallowed forms directly in the FAB. 

**Describe alternatives you've considered**
Leave it as it is.

**Comment by michaelkohn** [comment]
@dianabarsan ... I looked but couldn't find the feature you are talking about, can you share the issue that added that feature to prevent a user from opening forms? I'd like to learn more because when I read your description of this, it sounded liked a bug... but I'm also not sure what you mean by "opening forms".

**Comment by dianabarsan** [comment]
I checked this again and it's working as expected - the form doesn't show up on the FAB menu. Closing.
