### ISSUE TITLE
Error recording telemetry on Firefox

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8777]
**Describe the bug**

On page load we attempt to log some telemetry. On firefox, this fails every time.

**To Reproduce**
1. Log in on firefox
2. Look in the console

**Expected behavior**

No errors. Telemetry is recorded as expected.

**Logs**

```
Error in telemetry service TypeError: _this5.windowRef.indexedDB.databases is not a function
    TelemetryService telemetry.service.ts:293
    Babel 3
    ZoneAwarePromise Angular
    _asyncToGenerator Babel
    _record telemetry.service.ts:303
    TelemetryService telemetry.service.ts:283
    Angular 3
    record telemetry.service.ts:283
    SetLanguageService language.service.ts:74
    Babel 2
    Angular 12
feedback.service.ts:179:17

```

**Screenshots**

**Environment**
- Instance: localhost
- Browser: Firefox
- Client platform: Linux
- App: webapp
- Version: master

**Additional context**

We're using the `indexedDB.databases` function which is [not supported in Firefox](https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/databases) according to MDN.

**Comment by garethbowen** [comment]
@latin-panda I think this is related to the telemetry work you did recently. Can you look at this when you get back from holiday?

**Comment by latin-panda** [comment]
- Related to the job done [here](https://github.com/medic/cht-core/issues/7616).
- [Firefox bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=934640) 

Since Chrome is 99% of our use case, and `indexedDB.databases()` is more elegant and robust. We are going to keep this as it is. We will implement a polyfill, and then when Firefox implements it, we can drop it. 

This polyfill gets the list of database names from _local doc in the database or uses localStorage. This list of db names is updated when a new telemetry db is created or deleted.
