### ISSUE TITLE
Record Apdex score in webapp

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8821]
**Is your feature request related to a problem? Please describe.**
We need a tool to help us understand the performance that CHWs are experiencing. We decided to use ApDex 

**Describe the solution you'd like**
Use telemetry to record the page loads that fall into 'Satisfied', 'Tolerating', and 'frustrating' categories. 

[Docs PR](https://github.com/medic/cht-docs/pull/1278)

**Comment by jkuester** [comment]
What is the current status of this issue?  I see we have a PR open, but are there any blockers on that?  Just wondering because this is one of the 4 remaining open issues for the `4.6.0` Milestone.  At this point, I don't know of any pressing need to rush the release out, but I am just trying to gauge where we are with the remaining projects.  Thanks!

**Comment by latin-panda** [comment]
Thanks @jkuester, these are the pending items before we can merge and close this:
- Resolve and merge the task bug that @Benmuiruri is working ([ticket](https://github.com/medic/cht-core/pull/8838))
- Write the SQL that will consume these telemetry entries ([ticket](https://github.com/medic/care-teams/issues/3))
- See it behaving with way more data on bigger test party ([ticket](https://github.com/medic/care-teams/issues/11))

On Monday, we agree to not hold 4.6 release if this is the last open item. cc: @michaelkohn
