### ISSUE TITLE
Support Android validation URL endpoints for registering an intent

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8917]
**What feature do you want to improve?**
In Android 12+ you can't just register a URL as an intent and have it work.  You now need to have the domain you're pointing to [be able to validate](https://doordash.engineering/2022/01/25/your-deep-links-might-be-broken-web-intents-and-android-12/) it is knowingly participating with the app. Otherwise, these URLs won't register in the app without manual intervention.

**Describe the improvement you'd like**
Allow the CHT Core to have an API endpoint that can be configured with the correct response to validate URLs that are in the corresponding CHT Android app.  Presumably this will be in the app settings file, but TBD.

**Describe alternatives you've considered**
You can [manually approve URLs](https://github.com/medic/cht-android/issues/308#issuecomment-1560074617), but this scales poorly with non-technical users and may only work for side-loaded apps.

**Additional context**
With out this feature, all token login [links are broken](https://github.com/medic/cht-android/issues/308).

**Comment by m5r** [comment]
Saving the contents of `assetlinks.json` in the project's `app_settings.json` makes a lot of sense since both are in json format and is pretty straightforward for admins to configure.
I've opened a draft PR #9021 with the changes required to get this working and they're very minimal. It's essentially an express handler for `/.well-known/assetlinks.json` that reads from the project's app settings. 
Pending the :vertical_traffic_light: green light/red light from @garethbowen or @dianabarsan, the next step would be to write docs for this new settings and how we're planning to relay the info to partners before they upgrade their users' phones to Android 12.

As an aside, I managed to test this feature *almost* competely locally by using a domain I own and a VPS by building the unbranded apk with the `app_host` string set to my domain and forwarding the CHT API port via SSH `ssh -R 5988:localhost:5988 hetzner` :eyes:
