### ISSUE TITLE
CI broken due to out of date package version

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9133]
**Describe the issue**
We need to bump versions in `master` as well, not just our feature branches. 

**Describe the improvement you'd like**
Bump version in `master`. 

For the future, I think this should be a step of our release process where, when we branch off of `master` for our release branch, we also bump the version in `master`. 

For example: when branching `4.8.0`, `master` should be bumped to `4.9.0`

**Comment by garethbowen** [comment]
> For the future, I think this should be a step of our release process

In an attempt to reduce the manual steps in the release process I'd rather think about how we can have this stamped on at release time, rather than manually updated in the package.json. I don't think we need it set in development at all. This might be as easy as setting running `npm --no-git-tag-version version <major|minor>` in CI just before building the docker image.

**Comment by dianabarsan** [comment]
Right now we have a bespoke test that checks the version and fails the build on mismatch: https://github.com/medic/cht-core/actions/runs/9159989408/job/25181646152#step:11:26

https://github.com/medic/cht-core/blob/2d8e10c78357d4d3a43b7a53dc78b59184087fa5/scripts/ci/check-versions.js#L7

I'm not sure how this ended up being reported on a `master` build.

**Comment by garethbowen** [comment]
Issue raised: https://github.com/medic/cht-core/issues/9136

**Comment by dianabarsan** [comment]
I believe this was fixed.
