### ISSUE TITLE
Add e2e test coverage to tasks for offline user

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#9443]
**Describe the improvement you'd like**
[As part of the effort to automate more cases with users type offline](https://github.com/medic/cht-core/issues/5704). 
Automate the following scenarios for Tasks: 

[tasks.wdio-spec.js](https://github.com/medic/cht-core/blob/master/tests/e2e/default/tasks/tasks.wdio-spec.js)

- [x] `should remove task from list when CHW completes a task successfully`

  - Steps:
    - The CHW has 3 tasks from different households
    - CHW opens tasks and fills up form.
    - submits form
    - The task disappears from the list
    - The newly submitted record (form) should appear on Reports List page, indicating it was correctly saved.

- [ ] `should add a task when CHW completes a task successfully, and that task creates another task`
  - Steps:
    - The CHW has 3 tasks from different households
    - CHW opens tasks and fills up form.
    - submits form
    - The task disappears from the list but a new one is created with the correct data display in list (form name, hh name, etc)
    - The newly submitted record (form) should appear on Reports List page, indicating it was correctly saved.

- [x] `should load multiple pages of tasks on infinite scrolling`
  - [See example here](https://github.com/medic/cht-core/blob/master/tests/e2e/default/reports/infinite-scrolling.wdio-spec.js)
  - Steps:
    - Create 200 tasks with different data
    - Make it scroll 3 times
    - Very every single task is displayed

**Comment by ralfudx** [comment]
Two of these tasks have been completed:
- should remove task from list when CHW completes a task successfully
- should load multiple pages of tasks on infinite scrolling
The last test for `should add a task when CHW completes a task successfully, and that task creates another task` was not completed because the validation step was incomplete as new task was not created after completing another task due to the task configuration used

**Comment by jonathanvq** [comment]
> Two of these tasks have been completed:
> 
> * should remove task from list when CHW completes a task successfully
> * should load multiple pages of tasks on infinite scrolling
> 
> The last test for `should add a task when CHW completes a task successfully, and that task creates another task` was not completed because the validation step was incomplete as a new task was not created after completing another task due to the task config used.

@ralfudx, I did not understand why the third-case scenario was not completed. Can you elaborate or rephrase your explanation, please? Also, given that it is not completed in your PR, what are your plans for it so it gets done?

**Comment by ralfudx** [comment]
Hey @jonathanvq the last test was not implemented as part of this PR because I was unable to create a task config that will produce the precondition for the test (creating a task that creates another task after completion)
I had previously reached out to other team mates on how to accomplish this but was unable to get a clear explanation on how to create this precondition before adding the validation steps - I have now created this [ticket](https://github.com/medic/cht-core/issues/9594) to handle the last test and I'd be happy if anyone else with more domain knowledge on the task configuration wants to pick this up.
