### ISSUE TITLE
Flaky e2e test: `incorrect-locale` has been failing constantly in "after each" hook

### ISSUE THREAD

**Issue by tatilepizs** [medic/cht-core#9543]
**Describe the issue**
E2e test /tests/e2e/default/translations/incorrect-locale.wdio-spec.js has been failing constantly in the "after each" hook due to timing

```
------------------------------------------------------------------
[chrome 90.0.4430.72 linux #0-5] Running: chrome (v90.0.4430.72) on linux
[chrome 90.0.4430.72 linux #0-5] Session ID: 62d09db66cd013a39458898546df0548
[chrome 90.0.4430.72 linux #0-5]
[chrome 90.0.4430.72 linux #0-5] » /tests/e2e/default/translations/incorrect-locale.wdio-spec.js
[chrome 90.0.4430.72 linux #0-5] Testing Incorrect locale
[chrome 90.0.4430.72 linux #0-5]    ✖ should work with incorrect locale
[chrome 90.0.4430.72 linux #0-5]    ✖ "after each" hook for Testing Incorrect locale
[chrome 90.0.4430.72 linux #0-5]
[chrome 90.0.4430.72 linux #0-5] 1 failing (5m 5.1s)
[chrome 90.0.4430.72 linux #0-5]
[chrome 90.0.4430.72 linux #0-5] 1) Testing Incorrect locale should work with incorrect locale
[chrome 90.0.4430.72 linux #0-5] Timeout of 120000ms exceeded. The execution in the test "Testing Incorrect locale should work with incorrect locale" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/runner/work/cht-core/cht-core/tests/e2e/default/translations/incorrect-locale.wdio-spec.js)
[chrome 90.0.4430.72 linux #0-5] Error: Timeout of 120000ms exceeded. The execution in the test "Testing Incorrect locale should work with incorrect locale" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/runner/work/cht-core/cht-core/tests/e2e/default/translations/incorrect-locale.wdio-spec.js)
[chrome 90.0.4430.72 linux #0-5]     at createTimeoutError (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/errors.js:498:15)
[chrome 90.0.4430.72 linux #0-5]     at Test.Runnable._timeoutError (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runnable.js:429:10)
[chrome 90.0.4430.72 linux #0-5]     at Timeout.<anonymous> (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runnable.js:244:24)
[chrome 90.0.4430.72 linux #0-5]     at listOnTimeout (node:internal/timers:573:17)
[chrome 90.0.4430.72 linux #0-5]     at processTimers (node:internal/timers:514:7)
[chrome 90.0.4430.72 linux #0-5]
[chrome 90.0.4430.72 linux #0-5] 2) Testing Incorrect locale "after each" hook for Testing Incorrect locale
[chrome 90.0.4430.72 linux #0-5] Timeout
[chrome 90.0.4430.72 linux #0-5] Error: Timeout
[chrome 90.0.4430.72 linux #0-5]     at listOnTimeout (node:internal/timers:573:17)
[chrome 90.0.4430.72 linux #0-5]     at processTimers (node:internal/timers:514:7)
------------------------------------------------------------------
```
 
[This](https://github.com/medic/cht-core/actions/runs/11255733499/job/31296886450) is an example run

Here is the artifact in case it is helpful -> [incorrect-locale-ci-webdriver-default-core-minimum-browser.zip](https://github.com/user-attachments/files/17369579/incorrect-locale-ci-webdriver-default-core-minimum-browser.zip)

**Comment by garethbowen** [comment]
@tatilepizs Could you please include the log as a text snippet rather than a screenshot so we can find this issue when doing a text search?

**Comment by tatilepizs** [comment]
Sure, I updated the description.

**Comment by dianabarsan** [comment]
I think the failure is both in the test and in the hook. 
Looking at the reported screenshots, it looks like the language actually never changes: 

![Image](https://github.com/user-attachments/assets/11599fe2-ecdd-4c4c-a69f-ff8a23441144)

**Comment by ralfudx** [comment]
The way the test was written, only a few components on the page will have translations as seen in the `createLanguage` method at the top of the spec file:
```
'n.month': '{MONTHS, plural, =1{1 luna} other{# luni}}',
'n.week': '{WEEKS, plural, =1{1 saptamana} other{# saptamani}}',
'reports.none.n.months':
  '{MONTHS, plural, =1{No reports in the last month.} other{No reports in the last # months.}}',
'task.days.left': '{DAYS, plural, =1{1 day left} other{# days left}',
'tasks.none.n.weeks': '{WEEKS, plural, =1{No tasks in the next week.} other{No tasks in the next # weeks.}}',
'Reports': 'HilReports',
'view.all': 'View all'
```
So the expected screenshot when the  test runs successfully will look like this:
![Image](https://github.com/user-attachments/assets/ce3974a1-e8db-4a0b-b4b0-b5137c6d55a3)

Also, the validations for the language translations are only for the `Tasks` filter and the `HilReports` filter.

From my investigations I noticed intermittent failures happening in the afterEach hook majorly because of a timeout which seems to happen in the `revertSettings`.
```
Timeout of 120000ms exceeded. The execution in the test "Testing Incorrect locale should work with incorrect locale" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/runner/work/cht-core/cht-core/tests/e2e/default/translations/incorrect-locale.wdio-spec.js)
```
Moving this method from the afterEach block to the main test block seemed to make the test more stable and we can accommodate this fix for now because we have only one test in the spec file - /tests/e2e/default/translations/incorrect-locale.wdio-spec.js

After executing the test about 20 times [here](https://github.com/medic/cht-core/actions/runs/11702447843/job/32601037252), there was no failure related failure  - the only failure on [Attempt#5](https://github.com/medic/cht-core/actions/runs/11702447843/job/32593445666) & [Attempt#20](https://github.com/medic/cht-core/actions/runs/11702447843/job/32600281071) happened because of this error - `A previous test did not call revertSettings` which happened in the `createLanguage` method and isn't one of the methods in the afterEach block.
